### ISSUE TITLE
named time zone support

### ISSUE THREAD

**Issue by bdenckla** [YOURLS/YOURLS#1344]
It would be nice if YOURLS supported named time zones, e.g. "America/Los_Angeles" in addition to numbered time offsets (from server time zone), as it does currently.

This way daylight savings time would be handled correctly.

This can be done without complicating the PHP code, by letting MySQL handle it, by explicitly setting the time zone when the MySQL connection is made.

**Comment by My1** [comment]
by the way talking about DST what to input in the tmezone number? the base, the DST or should I change it every half a year?

**Comment by partyzant** [comment]
What about this issue? When I live in variable time zone (Europe/Warsaw) do I have to change this setting every 6 months?

**Comment by ozh** [comment]
At this moment, I see 3 options : 
- you change the setting twice a year
- you don't give a fuck about links being 1 hour off during 6 months
- you submit a patch to fix this

:)

**Comment by PopVeKind** [comment]
@bdenckla - I am working on a DB Config Page and Installer Project #2380 and wondered if you would take a look at the demo page and tell me if that is what you mean?

Look for **`Time Zone`** on this page...
[http://a.fil.net/s/admin/db-config.php](http://a.fil.net/s/admin/db-config.php)

**Comment by bdenckla** [comment]
I no longer use YOURLS. This looks like what I was looking for, but it is a little hard to tell what's happening under the hood. In particular is this interface setting/storring a symbolic time zone, e.g "Australia/Eucla" or is it just using that string in the user interface but underneath setting/storing a numeric time offset, e.g. +08:45?

**Comment by PopVeKind** [comment]
@bdencklaHey Ben, I was just wondering, if you no longer use YOURLS, what do you use?

**Comment by bdenckla** [comment]
@PopVeKind I haven't ditched YOURLS for another shortener; rather, the project I used it for was a limited time project and is now done (web site taken down).

**Comment by My1** [comment]
why that? especially if Yourls already has the partial TZ support, we dont need to kill it and yourls can use UTC internally for everything for obvious reasons, and the timezone would be obviously only for display.

**Comment by PopVeKind** [comment]
@My1 
**Truth is, YOURLS does not have any timezone support.**

TimeZone support incorporates many different things. For example, many time zones have a `Daylight Savings Time` or `Summertime` for part if the year. In spring the clocks are pushed forward an hour and in fall they are moved back.  These timezone changes are based on local government laws and in most cases must be observed by law. Not all governments have these laws. In others, the exact date and time to change the clocks varies by law.

Likewise, the governments approve timezones that are NOT in a whole hours offset.  For example, Australia/Eucla has an offset of +08:45.

Fortunately PHP has functions for all these.  PHP can properly adjust the timezone and offset based on the word based official time zone. For example, a function that turns the timezone into an offset from UTC (which is why WordPress uses this).  This offset can be expressed in hours or seconds (as used in YOURLS.

> the timezone would be obviously only for display.

These times are used for legal purposes, for example for creating the YOURLS log entries.

In some countries, like where I live in the Philippines, the time is always UTC+08:00 but does that mean YOURLS should abandon people in America or Europe or elsewhere who do not have a constant **hours** offset?

It has been stated by @ozh that changing from the YOURLS_HOURS_OFFSET to the PHP Time Zone is a low priority project.  However, low priority does not mean "no priority".  Likewise, ozh has stated that YOURLS should seek to delete options and delete constants and move these into plugins.  A TimeZine Plugin would do both of these.

**Comment by My1** [comment]
I know DST, we have it as well, that's why I said PARTIAL TZ support

the good thing is that at in the current Yourls Release, Agent Ransack hits only 11 times onto the constant, of that 2 instances are in the readme, and another one is in the config sample, making it a RELATIVELY easy change, because you dont have the whole thing collapsing like a bunch of dominos.

**Comment by PopVeKind** [comment]
@My1
I am trying to understand why you oppose FULL TZ Support? Can you explain why you are opposed to reducing YOURLS_ constants?  Likewise, what is your reason to oppose reducing core options in favor of core plugins which are more noob friendly?

ozh and others have frequently been the proponent of reduced options in favor of replacing them with Plugins.  Why are you opposed to replacing the YOURLS_HOURS_OFFSET Option with a more accurate Timezone Plugin?

ozh and others have frequently commented on the need to reduce or eliminate YOURLS_ constants use in YOURLS.  What exactly is your opposition to improving YOURLS and deleting another constant in the process?

In the second post (above) ozh stated he added this to the YOURLS Roadmap.  What is your opposition to this?

 In #2387 a working prototype of moving the ten options from constants in config.php to a config page in the admin area was presented.
### See http://a.fil.net/s/admin/db-config.php Option No. 5
This was rejected because there were _too many **options**_. Each of these Core Options should have been presented as Core Plugins.  Therefore reducing both the Option count that every noob must configure, and reduce the number of YOURLS_ constants.  Are you opposed to reducing the number of core constants or options and replacing them with plugins?  Are you opposed to an advanced FULL TZ feature as presented in the above demo, except packaged as a core plugin?

#2387 above was marked by  LeoColomb as:

> Closing in favor of #2388

Delete All Core Constants and Delete All Core Options #2388

Are you opposed to deleting all cire constants and deleting all core constants and replacing them with core plugins?

The above are all reasons to change to a FULL TZ Support.  Perhaps you would like to post on each of these why YOURLS should not be improved? Searching past issues, the TZ problem comes up and was never fully solved.

I agree with ozh that the TZ issue is not a high priority issue.  However, if someone within the YOURLS community wants to put forth the effort to improve the TZ handling and improve YOURLS, then shouldn't we of the YOURLS community support that effort?

As to the Agent Ransack comment, this would not change the number of times the UTC seconds offset would be accessed. It would only change the accuracy of the offset and the ease to configure it for noobs. (See the pull-down Time Zone menu ib the demo page.)

One additional point, the only full-fledged installer to ever do to prototype (beta) has done so after options were removed from the config.php page.  Is it your opinion that YOURLS should not have a full-fledged installer? See the full-fledged installer demo at:
### http://a.fil.net/s/admin/setup-config.php

**Comment by My1** [comment]
where did I say that I oppose TZ support?

I only oppose pushing TZ support *into a plugin*

if we do it it should be core.

**Comment by PopVeKind** [comment]
Ok @My1  maybe I misunderstood you.

The current default is to set the hours offset to 0, which is equal to UTC. a large number of Average Joe users never change this.  Others have problems with timezones that are not whole hours from UTC or that use DST or Summertime.  These result in support issues for noobs that do not understand.  Using the PHP DateTimeZone functions in PHP solves this, this is what WordPress does.

YOURLS_ constants are a problem and it is well discussed the need to delete these from the core code.

Many **options** are a problem for noobs.  ozh has stated that the ten options we now have are too many, in his opinion.  Would you care to look at
**http://a.fil.net/s/admin/db-config.php**
And state your opinion on which of these options should be moved to Core Plugins?

The trend at YOURLS is to delete Core Constants and replace Core Options with Core Plugins.  Some developers recommend changing All Core Options to Core Plugins as this would be easier for noobs to configure their site properly.

> I only oppose pushing TZ support into a plugin

Would you explain the reasons you oppose moving TZ support into a Core Plugin?

**Comment by josowa** [comment]
Hello everyone, regarding this request about settings PST intead of a given number. Was this feature updated/added?
I have PST and now I set -7 in order to have correct time but when time comes I will have manually to change again to -8... 
Please point to the right direction where I can change this.

Regards.

**Comment by PopVeKind** [comment]
It is not important to the community. Just change the time for summertime
and back again for winter. Or do what most do and run GMT year round. Or
move to a country that has no DST/Summertime.

**Comment by JeremyKeusters** [comment]
I was surprised to learn that an awesome script such as YOURLS doesn't have support for timezones/summer time (daylight saving time). I think that this is an essential feature and that it's really short-sighted to tell users to manually change this or move to a country that has no DST/Summer time (most bull-shittish comment I've ever read on GitHub, and totally inappropriate).

Thanks in advance for reconsidering the addition of this feature to the roadmap.

**Comment by ozh** [comment]
I for one have absolutely zero interest in wrapping my head around the complete BS that timezone management is, just to make sure that hits are a couple hours adjusted. Pull requests welcome, or don't expect too much :)

**Comment by dgw** [comment]
@ozh But pull requests _are_ welcome; we aren't _against_ implementing timezone support, only having to write it ourselves. 😉 PHP supports named timezones in its date/time function library, so we just need someone willing to make any tweaks YOURLS needs to also support named zones.

> (most bull-shittish comment I've ever read on GitHub, and totally inappropriate)

I'd just like to point out that the referenced comment was made by a _contributor_, but not a YOURLS project _member_. It isn't an official stance.

**Comment by My1** [comment]
stupid question what's the big problem with timezone management?

I mean in short it consists of 3 things:
1) store all times in a timezone-independent format (UTC or unixtime)
2) have a timezone setting
3) pipe all times into a function to convert them into the desired time zone (and maybe even date/time format) before display.

**Comment by dgw** [comment]
There's no "big problem". It's just that nobody on the YOURLS team seems interested in implementing the changes right now. All of us have other projects, too, plus adapting to the impact on our normal lives from COVID-19 changes at work/home.

**Comment by My1** [comment]
> plus adapting to the impact on our normal lives from COVID-19 changes at work/home.

nobody said "right now", on an issie 7 years old by now waiting for covid to pass wouldnt kill anybody

**Comment by PopVeKind** [comment]
IMHO - timezones should be removed from the core and default to UTC.
Then a *"Set
your timezone plugin"* could be added for this purpose.

I've actually looked at the code a little bit. It would not be too hard to
put the time zone into the database. PHP can convert this to an offset to
replace the current code. That is the easy part. The hard part is forcing
all existing admins to change over and use the new code, unless you force
everyone to UTC first and allow people who want a timezone offset to use
the plugin.

For example, I live in the Philippines. +08:00. How can I write a change
over code without forcing every YOURLS admin to change their YOURLS
settings?

If I search for a +08:00 timezone I'd come up with places like:

+08:00
Australia
Mandurah
Perth
Western Australia

Brunei
Bandar Seri Begawan

China
Beijing
Chengdu
Chongqing
Dongguan
Guangzhou
Nanjing
Shanghai
Shenzhen
Tianjin
Wuhan

Hong Kong

Indonesia
Banjarmasin
City of Balikpapan
Makassar
Macau

Malaysia
Klang
Kota Bharu
Kuala Lumpur

Mongolia
Erdenet
Ulan Bator

Philippines
Antipolo
Bacolod City
City of Cebu
Dadiangas
Davao City
Manila
Zamboanga City

Russia
Irkutsk

Singapore

Taiwan
Kaohsiung
Taipei

*Some of these have summertime/DST and others do NOT.*

The question is, which One is the right place we would select to represent
the current YOURLS offset 8?

To do this requires changing EVERYONE to UTC first, then allowing 200,000
admins to change this to their timezone, or to just guess!

If you guess Perth for +08:00 it will be wrong for any city in the
Philippines who has no DST. If you guess any city in the Philippines (no
DST) it will be wrong for any city in Australia.

To top that off, I think most people leave the timezone blank or set it to
0 (zero), meaning UTC. Others like me don't want or need a DST/ST setting
as our countries don't use them.

Making this change will cause many of the 200,000 admins to write trouble
tickets that say something like "it used to work fine before I updated..."

This is why many programs have a small diagnostic package to handle these
events, YOURLS does not. Perhaps a diagnostic plugin would be a good
project, but how would you get Admins to use that Plugin before writing a
trouble ticket?

Personally, I would recommend defaulting all YOURLS to UTC and have a
Plugin to set a timezone for those who want it.

**Comment by JeremyKeusters** [comment]
I appreciate all of your comments and understand that indeed now is probably a busy time for a lot of people. I'll take a look into the project and see if I can warp my head around timezones.



>The question is, which One is the right place we would select to represent the current YOURLS offset 8? 
To do this requires changing EVERYONE to UTC first, then allowing 200,000 admins to change this to their timezone, or to just guess! 
If you guess Perth for +08:00 it will be wrong for any city in the Philippines who has no DST. If you guess any city in the Philippines (no DST) it will be wrong for any city in Australia. 
To top that off, I think most people leave the timezone blank or set it to 0 (zero), meaning UTC. Others like me don't want or need a DST/ST setting as our countries don't use them. 
Making this change will cause many of the 200,000 admins to write trouble tickets that say something like "it used to work fine before I updated..." 
> […](#)

You can just keep the current 'YOURLS_HOURS_OFFSET' config value in the config file and add an extra config value for timezone (which you keep empty). If the timezone param is empty or not present in the config file, you use the 'YOURLS_HOURS_OFFSET'. If it is present and contains a value, you use it and just ignore the offset. This allows a gradual transition to get everyone using a timezone.

**Comment by PopVeKind** [comment]
@Jérémy K
My first reaction was "code bloat!" But the second look was "this idea may
be doable."

=== Logic
If Plugin use it, break.
If Constant (config), use it, break.
Default use UTC.
===

That would put the control code for adding a timezone in the plugin.

I'm in a Covid-19 city in quarantine right now, so no promises on a
timezone timetable, but I'll add this to my personal TODO list to take a
look at.

**Comment by JeremyKeusters** [comment]
@PopVeKind :  not sure if you saw it yet, but I worked a couple of hours on building it into the core yesterday and suggested a PR.

**Comment by PopVeKind** [comment]
@Jérémy K

I'll take a look at your PR in the morning. It is not mine to decide but I
imagine your code involves adding a Constant in the config.php page and
adding some extra code to the core that is forced on everyone (AKA: Code
Bloat). (That is what I did in my first attempt to fix this.)

Friendly advice: It likely won't be accepted. The reasons:

1. It adds a constant.
2. It adds to the core bloat for "features" most people won't use.
3. It belongs in a Plugin.

As I said, I am not on the core team, I do not decide, but I do see their
points!

Adding anything to config.php also requires people to make an admin change
in the config.php file that noobs are likely to not understand and/or ask
for help. That adds burden/work to the core developers. So don't be upset
if your PR is not accepted.

We should be removing all Constants from config.php that are not related to
the database.

The good news is that you've got a work around that can be used as a
roadmap to build a Plugin! I've had one too. But this really does not
belong in the core. It belongs in a Plugin. Likewise, without looking at
it, I half expect you to add a timezone to a constant. It really should add
an entry to the database. And a noob should be able to select their
timezone in a self building menue, something like WordPress does. That
added code goes in a Plugin.

But as I said, what you have working could make a fine roadmap to building
a plugin and removing a constant at the same time!

I do think your idea can be done.

**Comment by JeremyKeusters** [comment]
@PopVeKind thanks for your feedback.

> adding some extra code to the core that is forced on everyone (AKA: Code Bloat)

It's about 15 extra 'real' lines of code, I don't think you can consider it as code bloat. The code could also be a first step into standardising the date/time code and making it more uniform.

> Adding anything to config.php also requires people to make an admin change
in the config.php file that noobs are likely to not understand and/or ask
for help. That adds burden/work to the core developers.

I made it such that you don't necessarily need to add the new config parameter to your config file.
People can just keep using the offset config parameter (for now).

> We should be removing all Constants from config.php that are not related to the database.

2/3 of the config file is not related to the database? Why should these be removed?

> But this really does not belong in the core. It belongs in a Plugin.

I simply do not agree. Most frameworks/projects that I have used in the past have a timezone config parameter in a configuration file instead of an 'offset' parameter. It makes much more sense that people just configure a timezone instead of an offset value.

**Comment by My1** [comment]
Well if you think a timezone setting is something that belongs into a plugin let's remove the offset altogether as both are essentially the same thing. A way to get local times. Just one more proper than the other.

**Comment by PopVeKind** [comment]
@Jérémy K

As I said, I'm not a core developer of YOURLS. My thought was only about
helping you to get a working TZ  Plugin.

Good luck with your PR.

**Comment by PopVeKind** [comment]
Hi @My1

Well, *I would certainly agree!*

I would just default to UTC. Then use the Plugin to set the timezone into a
database entry with a select list for easy use by noobs (WordPress style!).

The problem is, some people are used to using the offset. If you eliminate
the offset, then you "change" their offset to 0 (UTC) without them knowing
it (assuming noobs who don't read the docs!). And you require that those
few people install the TZ Plugin.

Then they generate bug reports, or trouble tickets.

I still like this option the best as it is cleaner, more professional and
easier to code.

*What does the rest of the community think?*

PS: One other issue... in my part of the world, not only do some countries
use summertime/daylight savings time (and some don't). Some countries
offset is also hours and minutes. Like 9 hours and 45 minutes. Whole
integers don't accept that. Perhaps floating point 9.75 might work for
+09:45, never tried it. The timezone plugin would do this automatically in
Php.

**Comment by My1** [comment]
I think dst and non-integer offsets are precisely why this was raised because offsets clearly cannot deal with that.

But to add timezones as a plugin you kinda have to expose some interface for a plugin to get in to change the times so core (and other plugins doing time) would need changes none the less, so the question is which is more effort.

**Comment by PopVeKind** [comment]
*@*My1

*"as a plugin you kinda have to expose some interface for a plugin to get
in to change the times"*

That statement is not correct. However, a couple minor changes to core
would be needed for full functionality.

One could just replace the time offset to one calculated by timezone and
default to UTC (0) perhaps a TZ offset in minutes or seconds? That would be
a very minimal change to the core. In fact the current program does that if
there is no offset. Therefore, the offset, if set in config.php, could be
ignored.

*"so the question is which is more effort."*

There are issues like this that say this goes back 7 years without a fix,
so it seems there is little to no effort! Ozh has stated he has almost no
interest in this.

Perhaps a better question might be "which is wasted effort?"

If a PR is suggested that adds constants and extra lines of code (bloat?),
and is more confusing for noobs to configure, and then gets rejected by
Core. That is wasted effort. There is a PR submitted now and ideas tossed
around before, maybe a rejected PR or two? Don't  know.

This is not the first fix that was proposed. I remember talking about it
years ago before I got so sick. Perhaps Core will change their minds? Or
maybe Core is waiting for a PR that meets their coding standards?

A couple years ago I read somewhere (I think Ozh wrote it) that most YOURLS
sites do not use an offset or wrongly configure it to "0". Without
configuring it to "0" it defaults to "0", so that is a waste of time, yours
and the computers!

Maybe the real question is, will core allow a PR that allows a Timezone
Plugin to replace the offset, with default to UTC?

Remember this is *not* used on the majority of YOURLS sites.

**Comment by JeremyKeusters** [comment]
Removing the offset (setting it to 0) would be a step backward. I'm sure that some users want/require a precise display of time. For example to see at what times campaign links were most clicked.

I think we are massively over complicating this by trying to form it into a plugin. This is still IMO a core feature, just as offset is at this moment. As I see it, offset should be phased out and users should be encouraged to switch over to timezone, in such a way that we can remove the offset parameter in a few years.

Let's just wait for the core-team to give feedback on my PR and we'll see from there. 😄

**Comment by My1** [comment]
>>as a plugin you kinda have to expose some interface for a plugin to get
in to change the times
>
>That statement is not correct. However, a couple minor changes to core
would be needed for full functionality.

well if we do not want literally every place that uses the time to check for the existence of a plugin and deal with it, core would need to add a function which does time and where the timezone plugin can just chime in and intercept and do something else.

>I think we are massively over complicating this by trying to form it into a plugin. 

full ack

>As I see it, offset should be phased out and users should be encouraged to switch over to timezone, in such a way that we can remove the offset parameter in a few years.

maybe even something one could do is for a few releases if the offset is defined but the timezone not, then to tell the admin to update the config to enter a real Timezone, just as example

**Comment by PopVeKind** [comment]
*Perhaps there is a better solution.*

I have a few YOURLS test sites. One is set up for refactoring the
http/https code, it is stalled due to a long illness, I hope to revive this
and finish it now.

This reads the config.php file *one time only*, then sets a DB entry to
replace the the constants, *one time only*, with a default of "http://". In
otherwords, it automatically converts from constants to DB, *one time only!*

Although this adds some code to the core, the code is *usually dormant*,
and therefore does not slow YOURLS down nor reduce YOURLS performance (an
essential component of "code bloat" is reduced performance). This code
improves performance and removes two problematic constants.

To change the http/https settings I use a plugin to read and modify the DB.

*This could be done for a shift to timezone.*

The default timezone for new sites would be UTC. Set in a DB entry. (Just
as offset = 0 does now).

For existing sites, evaluate the offset and set a DB entry appropriately
with PHP (newer timezone stuff in later versions of php5.x and 7.x allows
this). The timezone, used by 100% of sites, would then be in core, a
replacement for the offset code.

*The Timezone Plugin*, used by a minority of sites, would be used to Change
the DB Timezone entry.

*The Timezone Plugin* would also contain the PHP to create an easy pulldown
menu to simply select the new timezone (the code could be stolen from
WordPress). This would make timezone use easy for noobs.

Would anyone like this permanent solution?

The conversion from constant to DB entry would be automatic for all
existing sites.

Per the request of the PR developer, we can wait for the YOURLS Core Team
to decide on his PR.

Likewise, we should all add Pros and Cons to his PR.
