### ISSUE TITLE
How To Change Admin URL

### ISSUE THREAD

**Issue by decentguy49** [YOURLS/YOURLS#1611]
I had installed YOURLS on my domain and my admin panel is at myurl.com/admin now  for security i want to change my admin URl to something like myurl.com/myself or like so.

Is it possible to do?? if yes then how???

Another thing i want to know as i had installed YOURLS on my domain what are the security features i need to enable via .htaccess file or any other  file or like so

**Comment by philhagen** [comment]
The two referenced commits appear to focus solely on changing the "/admin/" portion of the URI.  Unless I'm mis-reading these, they would not allow a different URI altogether.  I see #1174 (closed), but I feel there is an important use case for this functionality.

I'd like to host admin functions on an HTTPS URI, to prevent authentication information from being passed in the clear.  However, hosting a separate SSL host for all redirection would be unnecessary overhead.

**Comment by TuKod** [comment]
@philhagen - Now that SSL is no longer such a large overhead, and with Google pushing Encryption Everywhere do you think there is still a need to split host the admin files like this?

As an experiment, I installed two copies of YOURLS on different servers, but they shared the same network database.

**Admin Server**
I did not add any .htaccess file entries, effectively disabling the YOURLS forwarding on that server.  I also changed the /admin directory to something like /Top-Secret.

This allowed me to do the admin functions here and write the information into the database. Data is stored as a keyword and the forwarded URL in the database.  I can think of no reason this could not have been HTTPS.

**Redirect Server**
On the second server, I loaded the second YOURLS, pointing to the same DB.
On this server, I disabled the admin area (delete or rename the files).  This server did the actual redirection.  I see no reason why this server could not be HTTP.

It worked but it brings me back to why?  The major URL shorteners are moving to https for everything, shouldn't we? Advances in SSL have brought the overhead.down to virtually nothing, and major sites are all going this way.  Encryption Everywhere is really mainstream now!

Pop VeKind

**Comment by philhagen** [comment]
I would only suggest that forcing administrators to make this move is a bit heavy-handed.  I think the way Google is doing this with Chrome is really unfortunate and unnecessary.  Google is a provider, not a standards body.  Not bashing G specifically here, but if moving to HTTPS everywhere is a good thing overall (and it very well may be), then the discussions should be made with the various standards bodies and not driven by commercial entities with browser (or service) market share.

I do still see a broader value in splitting the URLs, as it would provide administrators with flexibility to run the service as their requirements dictate rather than driving their requirements by the code's capabilities.

**Comment by PopVeKind** [comment]
@philhagen - To quote from Star Wars, "I feel your pain!"

I actually agree with your view on Google et al.  But after 50+ years of writing computer programs, I can tell you that industry is in full control (used to be the government, but they have been supplanted).

**Internet History - Off Topic!**

The reality is, Google has the power to get its way and with everyone following the piper, it will be a very difficult job for those who do not.  Early adopters will be rewarded, just as Google is rewarding higher page rank for people using https right now.  Remember history.  Back in the day, my friend Jon Postel from USC was really Iana.  One day he realized the root servers were being taken over by the government, so he switched the servers! Within hours the men in black appeared.  The root was switched back, and within months, Jon was dead.  Funny how things just happen!  Point being, those with the power got their way.  Most people today do not even realize that the internet is actually designed to run without any root server (kind of puts the ICANN root out of business!).  Google has great pull at ICANN.

Consider historically that "standards bodies" are largely backward compatible.  More than a decade ago the inventor of the Internet protocol in the URL publicly apologized for the separator `://` and stated that a single `/` is what he would use if he did it again.  `https://vekind.org` would become `https/vekind.org` saving two unnecessary characters in the URL. He went on further to say that popular protocols could be further reduced to a single character with a fall back to the colon-slash-slash format.  When is the last time you typed something besides `http://` or `https://` the above example would be something like `s/vekind.org`.  In a URL shortener that would save seven characters!  This simple idea, which many, or most, agree with, has been in a standards body for more than a decade!

  Well enough politics, let's look at **a solution.**

**Change Admin URL**

Under your last stated circumstances, the split admin solution would mean you would need 14 instances of YOURLS.  Seven on the HTTP servers and seven on the HTTPS servers.  Sounds sort of ridiculous, I agree.

Questions:
Do you use seven databases or just use seven different prefixes?
Do your seven YOURLS currently ALL have access to the database(s) you use?
  _In other words, If your seven instances of YOURLS are working on seven different physical servers, all using localhost as the DB address, what I am about to suggest likely won't work._

Did you see **YOURLS Multisite** (AKA: YOURLS-PV) [#2306](https://github.com/YOURLS/YOURLS/issues/2306)

If you follow the offsite link there you will see a Proof-Of-Concept site that that is running six domains into one instance of YOURLS-PV.  These six YOURLS sites share the same DB with different prefixes, but the configuration will allow different DB's on a per-site basis. the same Proof-Of-Concept demonstrates the /admin directory was easily renamed.

Farther down the same page are links to a production site I am building using YOURLS-PV.  These links demonstrate the added feature that YOURLS-PV will happily run side-by-side with WordPress on the same document root.

**Problems:**

The main problem is this is a hack - a drop-in work-alike replacement for YOURLS.  and it is not extensively tested.  I tried for months to write this as a multisite plugin.  It appears by the closed issues that many others have had this idea before me.  YOURLS is designed as a stand-alone, one domain per YOURLS, program.  This is why it does not play nice with WordPress or with multisite.  A plugin would be almost the size of the YOURLS program itself.

However, YOURLS-PV is about 99% YOURLS!  It is just a lot of tiny little critical code changes to many parts of the code that makes the difference.  My goal is not to replace YOURLS with YOURLS-PV.  My goal is to prove the safety and effectiveness of YOURLS-PV and merge it into the YOURLS core project - but it needs more testing!

Problem with Split HTTPS Admin...

YOURLS-PV is a slight modification of YOURLS and therefore like YOURLS, expects the /admin directory (or the renamed directory) to be on the same domain server as the redirect server.  To have one YOURLS-PV Redirect Server (HTTP) and one YOURLS-PV Admin Server (HTTPS), you would need to tell the Admin Server the domain name you were working on (if I understood you right, it would be a different domain name).  In YOURLS-PV this would have to be BEFORE the config file loads.  Likely as a query string `?domain=vekind.org` or a time-limited cookie, or maybe an additional entry at login.

It is an interesting thought...

**Comment by PopVeKind** [comment]
@philhagen - I had up on my whiteboard an idea of a YOURLS-PV **admin panel**.  The idea would be to allow something like https://abolitionistapproach.info/admin to control the databases for many YOURLS or YOURLS-PV sites.  For example, the domains http://fyuel.org and http://vekind.org and http://tait.asia  - as sort of a stand-alone HTTPS controller.

This sparked a conversation with one of my students.  What if you allowed the same domain and same files (YOURLS) to be served on one physical box.  In Apache, it would be something like this...

```
<VirtualHost *:80>
    ServerName your-domain.com
    DocumentRoot /var/www/your-domain-root
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot /var/www/your-domain-root
    ServerName your-domain.com
    SSLEngine On
    SSLOptions +StrictRequire
    SSLCertificateFile /path/to/server.crt
    SSLCertificateKeyFile /path/to/server.key
    SSLProtocol TLSv1
</VirtualHost>
```

Then in .htaccess you:
Redirect any HTTP traffic going to the /admin directory to the same place with HTTPS.
Redirect any HTTPS traffic _not_ going to the /admin directory to the same place with HTTP.

Of course "/admin" could be any directory of choice.

The result would be YOURLS Admin being served as HTTPS and the YOURLS redirect engine would run in HTTP.

It might even work with YOURLS as is (out-of-the-box).

Good Luck,

Pop VeKind

**Comment by ozh** [comment]
@PopVeKind I'd be curious in the end to see what code in your project cannot be packaged as a plugin. I'm not sure your long term goal should be that your YOURLS-PV be merged with YOURLS.

**Comment by PopVeKind** [comment]
@ozh  - Humm, That's interesting. OK - Will do.

Sincerely,

Pop VeKind

**Comment by PopVeKind** [comment]
@ozh - Ok. here is the _YOURLS-PV_ update for the last couple weeks.

As I mentioned (as TuKod) in [YOURLS MultiSite #2306](https://github.com/YOURLS/YOURLS/issues/2306), I am new to the GitHub environment.  Also, due to my retirement, I have released the TuKod account to the TuKod Team.  So anyway, I took the time to learn the basics of Git.   I realized I need to give you just the code adjustments for the added options.  When I had Git compare _YOURLS-PV_ to YOURLS there were hundreds of changes!  I was shocked.

The changes were made due to my closed system work habits.  For example, I automatically remove all trailing whitespaces (spaces, tabs, etc.) from each line.  This triggered dozens of Git changes.  Likewise, I have a "clean as you go" work habit.  Without thinking I make things pass the _W3C Validator_ for HTML5, CSS3, and links.   And I adjust code with _WordPress Code Standards_ for readability.   Altogether, these simple clean up generated hundreds of Git changes and masked the real code adjustments, buried in all the cleanup.

So I forked YOURLS and focused on just the _YOURLS-PV_ adjustments. There are only 17 and most are tiny.  They center around five defined constants, **YOURLS_SITE**, **YOURLS_CONFIGFILE**, **YOURLS_ABSURL**, **YOURLS_PROTOCOL**, and **YOURLS_ADMIN_DIR**. The first two were redefined, the last three were added.

I have now started to build a website to support **_YOURLS-PV_**, for the time being, [**yourls.y143.net**](http://yourls.y143.net/)

The 17 code adjustments are cataloged on the **[YOURLS Code Adjustments Page](http://yourls.y143.net/yourls-pv/yourls-code-adjustments-page/)**.

The _YOURLS-PV Road Map_ was moved to this site.  I am now in the process of adding _Configuration Pages_ to show how to use each of the new features.  As I get these Configuration Pages written, I hope others will help me test these tiny adjustments. My test platform is currently limited to Apache in HTTP. However, I am planning to move all my project sites to an nginx server and HTTPS by next year.

Sincerely,

Pop VeKind

**Comment by PopVeKind** [comment]
## After more consideration...
After more consideration, I would suggest less change to the core, and put this in a plugin.  That is what I am currently doing on my production sites.

The small patch _Splitting YOURLS_SITE - Added Features_ **#2335** automatically calculates YOURLS_ABSURL  (the Absolute URL where the YOURLS Files are). This replaces one purpose of YOURLS_SITE (the other purpose is to create shortened URLs).  Thus, it allows YOURLS_ABSURL and YOURLS_SITE to have different values.

The **_Rename The Admin Directory Plugin_** (number 7 on the List of Benefits for **#2335**) uses YOURLS_ABSURL and adds this feature in a plugin.

**Comment by paulgailey** [comment]
i followed the guidance from @ozh  and recently set my installation to https

it seems to work ok but

the point of failure is when i attempt to browse to the short url (without the http://) with a + appended to view the general stats. 

At that point the browser demands i login to my yourls with https even though i am already logged in.

im unsure where within the installation code i can amend a line of code to mitigate that. 

any ideas?

**Comment by ozh** [comment]
Closing - see #2747
