### ISSUE TITLE
Error creating YOURLS tables

### ISSUE THREAD

**Issue by vahost** [YOURLS/YOURLS#1636]
I did a fresh installation to the domain root (no other files present). When the installation completed, I received the following message:
    Error creating table 'yourls_url'.
    Error creating table 'yourls_options'.
    Error creating table 'yourls_log'.
    Error creating YOURLS tables.

```
File .htaccess successfully created/updated.
```

I checked phpmyadmin and found the three tables listed there.

When I visit the home page of the site, I get the following:

The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

```
This problem can sometimes be caused by disabling or refusing to accept cookies.
```

Cookies are enabled in Firefox.

Suggestions?

**Comment by dansdrivers** [comment]
Sorry if this is out of place and an old ticket. But the same thing just happened to me. 

When I moved one of my yourls instance and database to a new server, I imported the old database as the root user.

    mysql -e "source /home/user/yourlsdb.sql" -u root -p

Then I made a the existing user with the same pword it had on the old server.

    mysql -e 'CREATE USER 'yourlsuser'@'localhost' IDENTIFIED BY "apassword";'
    mysql -e 'GRANT ALL PRIVILEGES ON 'yourls'.'*' TO 'yourlsuser'@'localhost';' -u root 

Then I had the exact same result as original post by vahost.

Another symptom of the issue was that if I queried the db as 'yourlsuser'@'localhost' I got no result from the database. Ex:

    mysql -e "show tables from yourls;" -u root -p
    +------------------+
    | Tables_in_yourls |
    +------------------+
    | yourls_available |
    | yourls_log       |
    | yourls_options   |
    | yourls_url       |
    +------------------+
    
    mysql -e 'show tables from yourls;' -u yourlsuser -p
    Empty set (0.00 sec)

## My Solution:

The problem in my setup was that I put the quote or backtic on the database name when granting privilege on the new server. Mysql treated them literally as the db name. After the following grant statement, the install reported "already installed" and everything was back to normal on the new server.

    mysql -e 'GRANT ALL PRIVILEGES ON yourls.* TO 'yourlsuser'@'localhost';' -u root -p
    #                                ^ --- ^ no single quote,backtick used.

This might be a MySQL noob error. But I normally made a website and database users on a server with a "cpanel" or similar interface. In this case I moved everything by bare files to a minimal server with no options by command line to work on the files, apache and mysql stuff.

Just for clarity, the following grants failed. 

    mysql -e 'GRANT ALL PRIVILEGES ON 'yourls'.'*' TO 'yourlsuser'@'localhost';' -u root -p
    mysql -e 'GRANT ALL PRIVILEGES ON `yourls`.`*` TO 'yourlsuser'@'localhost';' -u root -p

**Comment by LeoColomb** [comment]
@dansdrivers Oh, interesting! Thanks for your feedback!
May need a review.

**Comment by abazapa** [comment]
Hi guys!

I had the same issue with the installation, but then I have modified the file deleting a line and adding three others. After that, I have tried to TRIGGER the installation once again - it just shows a blank page. 

Then I have removed the database, cleaned the files up, made a fresh file and db creation, navigated to the mysite.com/admin/ and yet it shows the blank page. Any advice?

**Comment by zaghost** [comment]
make sure your mysql user has the appropriate privileges to use the database and create tables.
