### ISSUE TITLE
"Please Log In" After entering correct password

### ISSUE THREAD

**Issue by blueone1** [YOURLS/YOURLS#1652]
Hello,

My issue is similar to: http://code.google.com/p/yourls/issues/detail?id=1262

I'm using PHP v 5.4.9 ... All tables were installed correctly. I inserted a cookie from http://yourls.org/cookie .. I also deleted the username, password, cookie and replaced to see if that fixed the problem. It did not. I only have 1 username and PW in the config.php file.

Basically, when you enter the correct information into the admin login it says "Please Log In" ... anything incorrect entered gets an "Invalid Username / Password" ... 

I see the request for var_dump() in functions-auth.php or auth.php but I am not necessarily an expert - I was wondering if anyone might point me in the direction of the lines to place the var_dump on and on what variable so I can see where exactly it is breaking.

I am using the latest 1.7 master because I had to use the master as it fixed a table install issue I believe w/ the version of MySQL I saw on another issue. So tables were removed and now appear as installed correctly. 

I also tried this: define( 'YOURLS_NO_HASH_PASSWORD', true ); .. but no help .. to see if it was something to do with the password not being hashed in config.php

Finally, I am running nginx w/ the following config, although this may be unrelated (running varnish, hence 8080 - excluded yourls domain/directory in varnish config w/ pass):

server {
  listen 127.0.0.1:8080;
  server_name site.us;
port_in_redirect off;
  access_log off;
  error_log /var/log/nginx/site.us.error.log;
  root /usr/share/nginx/www/site;
  location / {
rewrite ^/([0-9a-z-]+)/?$ /s/yourls-go.php?id=$1 last;
        location ~ .php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }

  }
}

Thank you in advance for any guidance on how to identify this problem exactly. I am new to using var_dump.

**Comment by rashadkkar** [comment]
I am facing the same issue. I configured correctly the config file. but I am not redirecting to main page it keeps asking me the "Please log in". As mentioned in the olde post Line number 90  include/functions_auth.php i just disabled it, then it is redirected to the main page. but all time I need to login if i click any link. please help me.

**Comment by stevep4** [comment]
I just wanted to thank @ablanken for his comment on Mar 26 2014 which fixed the issue for me.

I'm running IIS8.5 with PHP5.6 and was having the issue as described above... but only when using IE. With Chrome it worked fine, but no joy with any version of IE that I managed to try logging in with.

The removal of the code snippet suggested fixed it for me, and now IE (and Chrome) both log in and work as expected.

Thanks!

**Comment by DaneOLeary** [comment]
I'm having this same issue. Can't log in with correct password. I know the issue has to be something related to the login process because I can go in and change to this: `define( 'YOURLS_PRIVATE', false );` and it'll bypass the login completely and go right to my list of shortened URLs. Once I'm in there, everything works exactly as it should. So I guess until this issue is resolved, I'll just make it public for a few minutes while I do what I need to do and put the broken login back on when I'm done.

What a pain.

**Comment by GTMAN** [comment]
Check for any caching issues.

**Comment by DaneOLeary** [comment]
@GTMAN how can I check for caching issues? Where do I look?

**Comment by mohsinr** [comment]
I installed on Kinsta Nginx , then I changed the main domain and had same issue , Please login... in Config.php file changing the Cookie Random value fixed the issue for me. i.e. define( 'YOURLS_COOKIEKEY', 'asdfsafs868768afsafsaf9sksjdlfk87rjsadlkfjasl8' );

**Comment by planetahuevo** [comment]
Hi,
I had this problem today on a server with 2 installs of Yourls. 
The funny thing was that only one of the install had the problem. The other one was working fine. 
Because of this I was able to debug it this way:
- I replaced the files downloading the latest one from github. No luck.
- I replaced the files using the other install that was working. Again, no luck, same issue. 
- I replaced the cookiekey and clear caches on my computer. Same thing.
Because I know that is the same server, I discarded issues with the cache on my server or nginx config issues. 
So the only thing to test was the database. 
I was going to dump it and upload it again but I decided to go to this url first:
myyourls.com/admin/upgrade.php
first time it did nothing, I reloaded it, and nothing, just the login page. 
I put my credentials there and done! I was in on a page that said: You do not need to upgrade. 

After this I can use the admin but the funny thing is that I cannot logout anymore. 
When I logout and go to /admin/ the session is still open.

So this is clearly a problem with the cookies. It does not store the login cookie when accessing from admin/ but it does work with the url /admin/upgrade.php and it does not remove that one  when going to logout/ either.
I am considering to go back to 1.6 or 1.7 but I will try this next time. 
Hope you can use this to find the issue.

I have also tested with PHP 5.6, 7.0 and 7.1 and the issue is still there. 
This is a server setup with serverpilot.io, in case you want to test.

**Comment by planetahuevo** [comment]
More info. 
I compared both databases to try to find the issue. 
On the table short_options on the field version, it is a 1.7 for the install that works and a 1.5 for the one that does not work.
So it seems that the upgrade is needed on the database but the system is not able to do it. 

Any idea on how to upgrade the database? or how to export my redirects to a new database updated?

**Comment by dgw** [comment]
@planetahuevo It might be that YOURLS's database user does not have the required permissions to upgrade the database. That's the low-hanging fruit answer, at least.

**Comment by planetahuevo** [comment]
What does need to be upgraded on the database? The urls and redirections works all the time and I can add new one. I really do not know where to look.

**Comment by Trigone** [comment]
Hello. I just installed Yourls in a subfolder /s/ on my Web site and I faced the same problem... but I solved it.

In fact, I have 2 domain names: mywebsite.com and my-website.com (FAKE examples ;) ).
And for some historical reason, mywebsite.com automatically redirects to my-website.com.
But I wanted to use the "short" version with Yourls, so I configured like this:
define( 'YOURLS_SITE', 'http://mywebsite.com/s' );

As there's a redirection, it doesn't work. So I had to use the "long" version, and now it's OK:
define( 'YOURLS_SITE', 'http://my-website.com/s' );

Hope this can help one of you.

**Comment by planetahuevo** [comment]
I am going with the fresh new install. I gave up to fix this one. 
Any ideas on how to export and import the data?

Thanks

**Comment by planetahuevo** [comment]
After some more tests, I am not sure anymore that the database is the problem, but the management of the cookies.

**Comment by LeoColomb** [comment]
@planetahuevo Thanks a lot for your feedback. Could you elaborate the cookie issue?

**Comment by planetahuevo** [comment]
You can read my reply 27 days ago: https://github.com/YOURLS/YOURLS/issues/1652#issuecomment-282912109
"So this is clearly a problem with the cookies. It does not store the login cookie when accessing from admin/ but it does work with the url /admin/upgrade.php and it does not remove that one when going to logout/ either."

**Comment by medikiaei** [comment]
Hi,
I had this problem and i've solve it.
in confiq.php file i 've only changed define( 'YOURLS_SITE', 'http://www.my website.com' ) to define( 'YOURLS_SITE', 'http://mywebsite.com' ). so I've only deleted www. from my website name .

**Comment by jcormir** [comment]
I have been experiencing the issue. I have been trying to use YOURLS as an enterprise / internal URL shortener. Doing a bit of digging in to the cookie that is to be set when logging in to the admin page.

The following code in the function `yourls_store_cookie` sets the cookie using a domain:

`$domain = yourls_apply_filter( 'setcookie_domain', parse_url( YOURLS_SITE, PHP_URL_HOST ));`

But in my case I wasn't referencing the short URL with a domain. For example, short URL hostname could be XX.corp.example.com, but in the browser XX/shortcode would work because corp.example.com is part of the DNS search. The above code was failing to set the cookie because in my case there was no domain.

When setting the YOURLS_SHORTURL to http://XX.corp.example.com allowed me to login to the admin section, but resulted in some weird redirect issues when using XX/shortcode.

As a work around I set the domain to an empty string, instead of trying to parse it from PHP_URL_HOST.
`$domain = '';`

Hope this helps someone else with their efforts.

**Comment by peepntom** [comment]
medikiaei saves the day thanx!!!

**Comment by b-hayes** [comment]
Same problem here trying to run this inside a docker container. Always returns true when checking the password but then says please loging afterwards. Suck in a loop. Yes I should upgrade to a newer version, but I wont even try taht until I can get a working test environment with the current version that is running in production. This code is really ahrd to follow cant find where its spazzing out.
