### ISSUE TITLE
403 Permission Denied. At wits end, lol.

### ISSUE THREAD

**Issue by jscottelblein** [YOURLS/YOURLS#1661]
Whenever I try to visit a shortened URL I get the 403 error:

> 403 Permission Denied
> You do not have permission for this request /!/

I've got these settings so far ...

**File permissions:**

```
directories: 755
files: 644
config.php: 400
```

**.htaccess:**

```
# Prevent .htaccess and .htpasswd files from being viewed by web clients
<Files "^\.ht">
    Order allow,deny
    Deny from all
</Files>

# Protect files
<Files ~ "^(.)\.(inc|inc\.php|tpl|sql|bak)$">
    Order deny,allow
    Deny from all
</Files>

<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteBase /!/
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /!/yourls-loader.php [L]
</IfModule>
```

I have _no_ index.php in the root folder; in the server error log it shows that I'm trying to view the root folder, with the error:

> Directory index forbidden by Options directive: /home/mydomain/public_html/!/

**I've tried:**
- Playing with all kinds of file permissions on yours-loader.php, no change.
- Ditto on the config.php.
- Tested and confirmed rewritecond _does_ work on my server.
- Adding ?blah=http:// to make sure my host isn't blocking out params with http:// in them, which it isn't.
- And a handful of other things that I can't remember at this very moment.

Any ideas on a solution?

Thanks

**Comment by chaosratt** [comment]
I arrived from googleing this exact same problem and thought I'd chime in with a fix, sorry for the thread necro.

Adding `Options FollowSymLinks` to the side conf resolved the issue for me when migrating from one server to another. Reviewing the log files for the site eventually led me to that solution:

` AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions`
