### ISSUE TITLE
Add lighttpd rules

### ISSUE THREAD

**Issue by heubergen** [YOURLS/YOURLS#1809]
Hi Devs

Maybe you will add the follow informations to your wiki:
To run YOURLS with lighttpd you have to add the follow lines to your lighttpd.conf:
`# Rewrite rules for YOURLS`
`url.redirect = (`
`"^/([0-9A-Za-z]+)?$" => "/yourls-go.php?id=$1",`
`"^/([0-9A-Za-z]+)?\+$" => "/yourls-infos.php?id=$1" )`

**Comment by gsdefender** [comment]
Hi,
I have found that the rewrite rules found [here](https://mati-ck.pl/index.php/tag/yourls-lighttpd/) work.
As I have enabled the dash support plugin, I had to add the dash in the set of matching characters.

`url.rewrite-once = (
"^/([0-9A-Za-z-]+)?$" => "/yourls-go.php?id=$1",
"^/([0-9A-Za-z-]+)?\+$" => "/yourls-infos.php?id=$1" )
`

**Comment by jaquer** [comment]
@okoestner: I know your request is old, but I believe it's because you are using `redirect` instead of `rewrite`.

Back to the original issue, I wanted to keep the functionality as close to the Apache one, and so far this seems to work for me:

```
url.rewrite-if-not-file += (
  "^/$" => "$0",
  "^/admin/.*$" => "$0",
  "^/.*$" => "/yourls-loader.php"
)
```

The `if-not-file` takes care of anything under the `css`, `images` and `js` directories, the `^/$` entry stops a redirect loop, `^/admin/.*$` lets anything under admin pass untouched, and finally `^/.*$` duplicates the behavior of the official [.htaccess](https://github.com/YOURLS/YOURLS/wiki/.htaccess) file, as far as I can tell. It even handles the `/robots.txt` and `/favicon.ico` special requests properly.

I'm using `lighttpd-1.4.49`. Hope it helps somebody out there.

**Comment by okoestner** [comment]
One Covid pandemy later...
Sorry, since the last answer did not solve my issue I postponed that to later. And later is now ;)

The base URL (like go.server.com) works. Even the /admin URL works.
But if I try to redirect with sth. like "go.server.com/fun" which was successfully written to the database I will not be redirected successfully.
Instead I can see the following error message in the log file:

2020-10-01 23:11:17: (mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Fatal error:  Uncaught RuntimeException: The gmp or bcmath extension must be installed to read this database. in /mnt/nas/maschine/www/go.server.com/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php:295

Any idea?

**Comment by dgw** [comment]
The error message tells you what's missing. Install either gmp or bcmath PHP extension.

**Comment by okoestner** [comment]
> The error message tells you what's missing. Install either gmp or bcmath PHP extension.

But how? How do I determine what is missing? And how can I install it?

**Comment by dgw** [comment]
Both of those extensions are missing. You need at least one of them.

**Comment by okoestner** [comment]
Thanks a lot, "dgw".
I installed both needed packages and everything works fine, now!
