### ISSUE TITLE
Forward Main Domain and Forward 404

### ISSUE THREAD

**Issue by jesse9212** [YOURLS/YOURLS#1843]
How do I forward the "home page" of the shortener URL (ie. example.com/) to anotherdomain.com (or a directory of anotherdomain.com).

And how do I deal with 404 errors so I can trouble shoot them?
For example example.com/1a forwards to anotherdomain.com/does-not-exist/ (should be the 404 page if the redirect URL doesn't exist). How can I monitor these 404 issues so I can try to troubleshoot where the link was suppose to go or at least where the user was referred from so to try to find the context?

**Comment by ColtonDRG** [comment]
I have never found how to deal with 404, but I haven't really cared. As far as the homepage, just make a file in the root of your YOURLS install called index.php and put the following code in it.
<code><?php header('Location: http://anotherdomain.com/'); ?></code>
By default, 404s will redirect to the same address as well because that is default YOURLS behaviour.
You can see an example of this in action on http://drg.li/

**Comment by jesse9212** [comment]
Thanks.

**Comment by jesse9212** [comment]
It would be nice if the yourls 404 forwarded to the same extension (ie. short.com/asdf goes to anotherdomain./asdf) so wordpress 404 handlers can pick it up. At least this would give you a chance to google search short.com/asdf to try and locate the context of the referral.

**Comment by LeoColomb** [comment]
As always, see [Plugin list](https://github.com/YOURLS/YOURLS/wiki/Plugin-List) where you will find everything you need for what you want to do.
