### ISSUE TITLE
No traffic sources (referres)

### ISSUE THREAD

**Issue by Steffov** [YOURLS/YOURLS#1847]
Hi,

I'm not 100% sure if I'm on the right place here. If not, big sorry! But I searched a lot and could find any reason or any solution.

I installed a fresh 1.7. The issue: I din't get any referrer. In every case it's "direct" but I tested my short links by me own from other sites. During some testes I notices that I get a referrer if I click the link direct from the admin panel. In this case I see my short URL as referrer in my stats. But from other sites, no more information about the traffic source.

Any idea what went wrong?

Best,
Steffov

**Comment by ozh** [comment]
Referrers are not always reliably passed on. Browsers do not necessarily send a referrer depending on addons/plugins/config settings, referrers are not passed from HTTPS to HTTP, some proxies strip it, etc...

Simply put, it's not a mandatory header. If it's present, YOURLS uses it. Otherwise, it's "Direct". Nothing we can improve there.

**Comment by Steffov** [comment]
Yes, that's clear for me but I didn't get any referrers and I thing it's really strange. So I thought I've set up something wrong or I've to set up something special to use it?

**Comment by alexsorokoletov** [comment]
Did you resolve the problem? What was the solution?
