### ISSUE TITLE
Is it possible and is it a good idea to use the same domain for your website & yourls

### ISSUE THREAD

**Issue by fabvr** [YOURLS/YOURLS#1874]
The Yourls FAQ says: You cannot install YOURLS and, say, WordPress, in the same directory. Both need to handle URLs differently and need their own .htaccess file.

If i install YOURLS and my Wordpress site in different directories, is it then possible and is it a good idea to have the same domain for my website & yourls?
If I use mywebsite.com/y for the YOURLS, will the short URLS then also be mywebsite.com/y/myurl or can it be like mywebsite.com/myurl
And if so, can my Wordpress site also have URLS like mywebsite.com/webpage ?

**Comment by chtaube** [comment]
It is perfectly ok to run Wordpress and YOURLS in different directories under the same domain (or, say Wordpress from the root directory and YOURLS from within a subdirectory). Wordpress and YOURLS would not care, but you have to configure your webserver accordingly.

Anyway, there is no this turnkey solution for this as this is definitely advanced webserver configuration stuff and you – or whoever manages your webserver – should really know what you are doing.

**Comment by ozh** [comment]
As  @chtaube says, yoursite.com/ for WP and yoursite.com/y/ for YOURLS is OK, but you cannot then have yoursite.com/shorturl because then WP will think it's a WP page.

A workaround would then to make a WP plugin that, if yoursite.com/shorturl doesn't match a WP page, handles things to YOURLS, but it can be more or less complex depending on your WP site.
