### ISSUE TITLE
yourls meta description and image not displayed when share on facebook

### ISSUE THREAD

**Issue by dipenpatel235** [YOURLS/YOURLS#1919]
Hello....
i am using yourls.
when i generated shortlink and paste that uri on facebook so it is not displayed image and metadescription of that website...
So is there any setting or plusin required for that?

Help Me...
Thanks......

**Comment by LeoColomb** [comment]
OK.

**Comment by LeoColomb** [comment]
It works for me.
Could you comply with [Contributing Guidelines](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) if your issue still occur?

**Comment by LeoColomb** [comment]
![image](https://cloud.githubusercontent.com/assets/846943/8190303/155de40a-1462-11e5-9c75-b993a3c0756f.png)

**Comment by dipenpatel235** [comment]
hmmm...correct..it is working for you...
but not working for me...so can you please short out my problem?
i am using nginx and your yourls 1.7...but now shown to me...
is there any special setings required for that?

**Comment by ozh** [comment]
Definitely works out of the box : 
![l6p4xd3](https://cloud.githubusercontent.com/assets/223647/8206541/cbd195d6-14fa-11e5-8ae6-8e9521dfcc6e.png)

When Facebook check links, it follows redirects. If it's not working for you, it's because something hinders this on your setup (YOURLS plugin, server setup?) or is specific to the URL you share. Either way, you're on your own to resolve this.

**Comment by baconbrad** [comment]
I couldn't get this to work and everything seemed properly configured. I wrote a [plugin](https://gist.github.com/baconbrad/6f6ea5bafbae869d3a2ce586dd2e482a) that checks if it is Facebook's scraper bot. If so it will give them an HTML page with `og:url` assigned to the destination. It performs a meta redirect just in case some poor soul finds their way there. Otherwise they will still 301 redirect.

**Comment by ozh** [comment]
@baconbrad neat! Feel free to submit it to https://github.com/YOURLS/awesome-yourls
