### ISSUE TITLE
yourls_apply_filter returns the last run filter's value

### ISSUE THREAD

**Issue by davidzoli** [YOURLS/YOURLS#1962]
I can show the bug through an example.

If you use the "Don't Log Bots" and "Don't Track Admins" plugins, you add filters several times. 
When the code run into function yourls_update_clicks() and call yourls_apply_filter() all the added filters are called. In yourls_apply_filter() function the foreach set the value to return more times, but return the last one. So the yourls_apply_filter() call's value will be the last called filter's value.
That is not so good. 

Back to the example if the visitor a bot, but not an admin the visit will be logged according to the last examined (is admin) filter's value.
I think, somehow, the foreach should be in the caller function of yourls_apply_filter() or yourls_apply_filter() should return an array/object.

**Comment by ozh** [comment]
Expected behavior, filters filter a value and return a value. Testing for an array in filters instead of a value would make code very awkward in places where it's very simple. Have an array and then what? Filter last value? Filter all values? This depends on the scenario and use case, hence should go in custom code.

When using multiple filters on the same hook, you can change the filter priority.
