### ISSUE TITLE
Problem with long URL edition.

### ISSUE THREAD

**Issue by stonealone** [YOURLS/YOURLS#1964]
Hello. I have issue with edition my urls.
Example:
I shortened link "xxx.com" and used short url - 1231
I changed long url to "zzz.com" but short url stay the same. I changed it positive, got green information "link updated in database", but when anfter all I going to my-website//1231 it moves me to xxx.com as nothing has changed. 
Any sugestions?
Regards.

**Comment by dgw** [comment]
When editing long URLs, your browser or a cache/proxy between you and the server may continue to use the old long URL for a while.

This is because, by default, YOURLS sends 301 Moved Permanently redirects, which are meant to be cached by clients. If you will be editing long URLs often, consider using a plugin to send 302 Temporary Redirect instead. That will reduce or eliminate the cache update delay.

**Comment by dgw** [comment]
And consider this the obligatory "please search for old issues, including closed ones" remark, as this issue has been brought up several times before in this issue tracker.
