### ISSUE TITLE
API creating redirect loop

### ISSUE THREAD

**Issue by SystemUpdate** [YOURLS/YOURLS#2008]
Hello,

When manually visited the YOURLS API in my browser, it works perfectly fine. However when I visit it via a Java Application I made, it returns this:

`<html><head><meta http-equiv="Refresh" content="0; URL=[reducted]"></head><body></body></html>`

The URL= value is the same that was requested making it into a loop, this is really annoying and is happening with user / pass and without it. 

It is also happening with https://github.com/minecrafter/Shortify

**Comment by ozh** [comment]
I blame the Java app you made then. Sorry, can't help ...

**Comment by SystemUpdate** [comment]
The issue isn't just happening with the app that I made, it's happening with another publicly available one, which I'm sure the developer wouldn't have posted a fault app.

**Comment by ozh** [comment]
There are numerous client using the YOURLS API that work fine.

What I might be able to help with would be specific enquiries such as "the YOURLS API behaves like this and that when requested like this and that, instead of the expected such and such". Definitely not with a broad vague request "it doesn't work with application Something".

Again: sorry, can't help.
