### ISSUE TITLE
Admin not protected after setting YOURLS_PRIVATE to true

### ISSUE THREAD

**Issue by aajkaal** [YOURLS/YOURLS#2010]
Using Apache web server
After setting  YOURLS_PRIVATE to true in config.php /admin is still accessible to everyone
Just checked the date and time stamp of every file and nothing has been modified except config.php

httpd.conf has
DirectoryIndex index.html index.html.var index.php

AccessFileName .htaccess

.htaccess has been created as per yourls install wiki doc

**Comment by ozh** [comment]
If you checked the timestamp of files to detect a potential intrusion, that's useless. If you suspect one, reinstall files (& change passwords)

Closing because I'm confident this is not a YOURLS defect but a misconfiguration on your end. First, reinstall fresh files, and try again. Also set YOURLS_DEBUG to true in config.php and see if any notice appears.
