### ISSUE TITLE
Bookmarklets work only if logged in?

### ISSUE THREAD

**Issue by GeriSoft** [YOURLS/YOURLS#2015]
Hi, I tried to use the bookmarklets for yourls, but seeing it only works if I logged in. If not, it redirects to login page.
It is a bug, or there is any hidden setting for this?
Thanks
Peter

**Comment by dgw** [comment]
If your YOURLS installation requires a login to shorten URLs via the dashboard, then it will also require being logged in when using a bookmarklet to do so.

**Comment by GeriSoft** [comment]
Do you mean private/public option? It requires login for the admin site, and unfortunately the bookmarklet is calling the admin/index.php.
Is there an option to make the admin site protected by password, but the bookmarket is unprotected? The basic url shorten front page is open for everyone (using the template)

**Comment by GeriSoft** [comment]
functions.php line:1273
function yourls_maybe_require_auth() {
............
Actually, by modify this module and add the verify for bookmarklets parameters, it can generate the shortlink, but can be dangerous for long term usage.

**Comment by ozh** [comment]
If you run a private YOURLS setup, bookmarklets works only if authenticated by design : you don't want any jackass to add any link by simply using a bookmarklet.

If you have a public interface that's free to use by anyone, there are bookmarklets available in the sample provided. Use this one in that case.

**Comment by GeriSoft** [comment]
You are right, master :)
Just noted, the default bookmarklets worked without logging in to admin (as they are pointng to the default public area, and using the full url in the variable url), meanwhile the social bookmarklets pointing to the admin/index.php and using up ur and us variables by splitting the url. and was wondering if there is any option make the social bookmarklet work without logging in.

**Comment by ozh** [comment]
Splitting the URL using variables `ur` `up` and `us` has nothing to do with being authed or not. It's just a matter of not passing a full URL in the query (`blah.php?meh=http://something`) because some servers identify this as an attack and block the request. If I had thought about it, I should have updated the public bookmarklets too... But that's left as an exercise for the reader if needed.

Regarding social stuff and authentication, same answer as above.

If you want your public interface to handle other bookmarklets than those provided in the sample, you'll have to code it
