### ISSUE TITLE
Count/Update the Click per Visit or per Click

### ISSUE THREAD

**Issue by jairus0893** [YOURLS/YOURLS#2076]
Hi. Just wanna ask i want to count the click every visit or click but think yourls limiting the click per user i think or per IP. I want like goo.gl it counts every click

Thanks.

**Comment by dgw** [comment]
NONE of the instructions in the issue template were followed. There's not even enough information here to figure out what the actual bug is.

**Comment by jairus0893** [comment]
Hi. Just wanna ask i want to count the click every visit or click but  think yourls limiting the click per user i think or per IP. I want like goo.gl it counts every click


Thanks.

**Comment by ozh** [comment]
YOURLS counts every visit it can. Period. Anything not counted is because of browser cache.

**Comment by BstName** [comment]
> Anything not counted is because of browser cache.

Yes! 

It might be worth mentioning that the reason why some users see this problem (while others do not) is due to a special kind of browser caching, namely the caching of HTTP 301 redirects. 

301 responses are cacheable by default unless otherwise specified. Because of that, on subsequent accesses of the short URL, the browser jumps to the destination URL directly, whithout ever accessing the server running the URL shortener, giving YOURLS no chance to ever count any but the first click. An even more severe problem is that some browsers cache them 'infinitely' or 'virtually uncachable' (such that one can only get rid of them by use of the dev tools, i.e. a simple Ctrl F5 doesn’t clear it):

http://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s
http://getluky.net/2010/12/14/301-redirects-cannot-be-undon/

It seems that YOURLS currently does nothing to prevent 301 caching. Therefore, the problem needs to be solved outside YOURLS, i.e. by an appropriate server-side configuration. E.g., if your web host has configured the server in such a way that caching is globally prevented anyway, you will never face this problem.

It might in fact be a good bad to consider preventing 301 caching within YOURLS, e.g. like so:

`yourls_redirect` in functions.php:
	...
```
	if( !headers_sent() ) {
		yourls_status_header( $code );
		// Temp. fix to prevent caching of 301 redirects:
		header( 'Expires: Thu, 23 Mar 1972 07:00:00 GMT' );
		header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s' ) . ' GMT' );
		header( 'Cache-Control: no-cache, must-revalidate, max-age=0' );
		header( 'Pragma: no-cache' ); 
		// End of temp. fix
		header( "Location: $location" );
	} else {
```
	...

I tested this, and it fixed the outlined problem as reproduced on an apache 2.4.7 webserver, with a configuration that should be pretty much the default one on ubuntu 14.04. A `curl -I` on one of our short URLs now yields:

```
HTTP/1.1 302 Found
Date: Thu, 31 Mar 2016 11:15:28 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Expires: Thu, 23 Mar 1972 07:00:00 GMT
Last-Modified: Thu, 31 Mar 2016 11:15:28 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Pragma: no-cache
Location: http://the-destination.com
Content-Type: text/html
```

and all is well, clicks are counted. Another possibility might be to use mod_rewrite/.htaccess, following the solution outlined at:

http://mark.koli.ch/set-cache-control-and-expires-headers-on-a-redirect-with-mod-rewrite

(But, so far, I have not been trying that, as I'd prefer the above solution anyway).

BTW, I am not suggesting to (permanently) hack the core here (!!!) - this is just for testing purposes, and also to initiate a discussion. Hope, that helps :)

**Comment by jairus0893** [comment]
@BstName Wow.. it works ur such a hero.. Thank you :+1:   and also 2 @ozh Thanks :+1:

**Comment by BstName** [comment]
@jairus0893: Thanks for trying that out, and I am glad that it actually resolved your problem!
@ozh: Just let me know if I can be of any further help.

**Comment by ozh** [comment]
I think the best approach is to make a plugin to aggressively not cache the redirects and count multiple hits for the same client (hooking into `'pre_redirect'` and passing the `header()` calls you suggest using)

**Comment by BstName** [comment]
OK, I'll have a go at it. Thanks for your feedback!

**Comment by BstName** [comment]
Done, can be found under [every-click-counts](https://github.com/BstName/every-click-counts).
@jairus0893: Would you like to be the first beta tester:-? When you try it out, please do not forget to first revert the temporary changes in `yourls_redirect` in functions.php which I had proposed to you for testing only and as a temporary fix. Thanks in advance!

**Comment by ozh** [comment]
@BstName added to the plugin list, :pizza: !

**Comment by BstName** [comment]
Thanks for adding, and for ... *remainingwordsdrownedoutbygiantsmacks* :yum:
