### ISSUE TITLE
add a new plugin to Plugin List

### ISSUE THREAD

**Issue by dennydai** [YOURLS/YOURLS#2079]
please add https://github.com/dennydai/yourls-preview-url-with-qrcode
to https://github.com/YOURLS/YOURLS/wiki/Plugin-List
 Thanks~

**Comment by LeoColomb** [comment]
Could you please improve your README to match our [guidelines](https://github.com/YOURLS/plugin-sample/blob/9a66ad444ede10256a0935112e7c3d596b2ae47f/README.md)?
Thanks! :smiley:

**Comment by dennydai** [comment]
@LeoColomb improved

**Comment by ozh** [comment]
Also improve the code: you're using functions and stuff prefixed with "ozh_", while I'm honored with the reference it will eventually lead to conflicts between plugin, especially when the functions have the exact name.... More: https://github.com/YOURLS/YOURLS/wiki/Coding-Standards#naming-conventions

Also, since your plugin is about showing a preview screen, it might be interesting to show what this looks like in the readme and show how it differs from the original Preview URL plugin

Added to the list anyway, thanks for letting us know (but no need to file an issue AND mail me the same stuff)
