### ISSUE TITLE
how to completely supress/override/replace core functions?

### ISSUE THREAD

**Issue by My1** [YOURLS/YOURLS#2100]
I read some stuff about dont modify core, make plugins etc, but I found a question where I have no answer yet.
How can I suppress a function from core or replace it?
in this case I need to somehow throw the function yourls_html_logo into oblivion or replace it.
the intresting question is how to do that? I cant really use die() because that completely kills the page.

if it isnt possible with a plugin yet then I would like to request a plugin hook for branding and stuff

while asking this it might also be nice to have a hook or something that allows us to hide version info so that script kiddies dont get bad ideas like googling for hacks/exploits or whatever for version x.

**Comment by ozh** [comment]
You can replace functions that have an action or filter that allow to shortcut the function. [Example](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L165-L169)

Out of the box `yourls_html_logo()` isn't shortcutable (simply because there haven't been a need for it) but you could simply hook into `'html_logo'` to print some CSS that hide the `#header` or anything you don't want to have displayed.

To hide YOURLS version we would need a filter in the various applicable places.

Rule of thumb: if you think a filter is missing and could be of value for others, please open a pull request :)

One thing about hiding version, though. Mostly, it's completely useless. Script kiddies don't test a page to see if it's version XX of software YY and then try hack ZZ. They just try hack ZZ. Saves a useless step.

**Comment by My1** [comment]
well for the logo thing, shorting it out would be nice because that (obviously) is unnneeded traffic even if it isnt displayed.

**Comment by Zitt** [comment]
@ozh, I also have the desire to replace _yourls_html_logo()_ but in ver 1.7.2 there still isn't any mechanism that I can see to do this. Hidding really isn't possible because the <h1> doesn't have an id for the script to hide.  As you pointed out there isn't any mechanism to short circuit the base function.

Am I missing something obvious?

**Comment by Zitt** [comment]
this is what I came up with to hide the yourls_html_logo(). This basically hides the original logo with a display:none span and subsititues my own via a plugin.

'
//Zitt themeing
global $myYourls_logo_s;
global $myYourls_logo_l;

yourls_add_filter( 'pre_html_logo', 'zitt_spanpre_htmllogo' );
function zitt_spanpre_htmllogo() {
?>
 <span id="hideYourlsLogo" style="display:none">
<?php
}

yourls_add_filter( 'html_logo', 'zitt_html_logo' );
function zitt_html_logo() {
 $myYourls_logo_s = yourls_site_url() . "/images/". 'pinball.click201x90.gif';
 $myYourls_logo_l = yourls_site_url() . "/images/". 'pinball.click2.gif';
?>

 </span>
 	<h1 id="yourls.logo">		
		<a href="<?php echo yourls_admin_url( 'index.php' ); ?>" title="Pinball.Click"><span>
     <img src="<?php echo $myYourls_logo_s; ?>" alt="Pinball.Click logo" title="Pinball.Click" border="0" style="border: 0px;" /><br />Pinball.Click</span>: - Pinball URL Shortner<br/></a>
	</h1>
<?php
}
'
