### ISSUE TITLE
Getting Uncaught TypeError: b.$headers.find(...).andSelf is not a function(…) on admin interface, always

### ISSUE THREAD

**Issue by danimvijay** [YOURLS/YOURLS#2172]
### Technical details

* YOURLS version: v 1.7.1
* PHP version: 5

### Reproducible Bug Summary 

Always getting Uncaught 'TypeError: b.$headers.find(...).andSelf is not a function(…)' on console and functions like edit, delete etc not working. This is from the time of install itself.

![bug](https://cloud.githubusercontent.com/assets/3250760/20645959/fe62587e-b494-11e6-9487-72a3a2d45cfe.PNG)

**Comment by ozh** [comment]
Sorry, cannot reproduce, and anyway such an obvious bug would also have attracted hundreds of bug reports before yours if it was confirmed.

Maybe update to latest [master](https://github.com/YOURLS/YOURLS/archive/master.zip) and see if that fixes? Anyway I don't think we've modified something in the javascript since quite long
