### ISSUE TITLE
Page title not scraped

### ISSUE THREAD

**Issue by stevep4** [YOURLS/YOURLS#2173]
* YOURLS version: 1.7.1
* PHP version: 7.0.9
* Windows Server 2016 / IIS 10

Sorry to be slightly useless with this bug report, I realise it may go against guidelines with not enough detail.

My yourls works fine for scraping the title off pages usually.... except for my blog which is the main use for the shortner. It used to work fine... but now no title is scraped from it any longer.

Other sites served from the same server still scrape fine, it's just this one site, so I think server can be discounted (hopefully).

The main change the site which no longer gets scraped from is that it now uses Cloudflare (and is mushed up by Cloudflare with auto minimised javascript, css and html).

Maybe it's the minify that's making the pages too long (all one line or whatever) that's stopping the title scrape happening?

Here's hoping someone else has found something similar.

An example URL that shortens ok, but gets no title scraped is: https://www.somersetwhisky.com/review-ardbeg-21-year-old/

Thanks.

**Comment by ozh** [comment]
Yep, you guessed it correctly, the minification stuff results in the HTML page being so big that the `<title>` tag isn't found in the first 32000 bytes, which I though was already a [very conservative measure](https://github.com/YOURLS/YOURLS/issues/2005#issuecomment-165896722) :)

In your case, instead of fetching the first 32KB of the page, we need to get the first **90KB** of the page, which is quite huge :)

For the moment, this simple plugin will do the trick for you :
```php
<?php
/*
Plugin Name: Dig Deeper For Titles
Plugin URI: https://yourls.org/
Description: Get page title even if it's buried deep in the page
Version: 0.1
Author: Ozh
Author URI: http://ozh.org/
*/
// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

// The trick
yourls_add_filter('get_remote_title_max_byte', function(){return 100000;});

```

Create a subdirectory in `user/plugins`, eg `digdeeper`, and put this code above in a file named `plugin.php`

In the future if there is more demand we could simply include this in core but since you're the first one to report this Cloudflare problem, no need for everyone to download more of the pages to fix a problem they don't have :)

Oh, also, nice touch linking your site with an article about a bottle of Ardbeg. You knew it's my favorite whisky, admit it! ;)

**Comment by stevep4** [comment]
Aww dude, that's fab, thanks... fixed it in one. :-)
And good call with being an Argbeg man, great whisky!
Thanks for your work with Yourls... it's letting me use whis.ky as a short domain, sweet!
