### ISSUE TITLE
1.7.1 Installer Error + Workaround

### ISSUE THREAD

**Issue by jwkite** [YOURLS/YOURLS#2182]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5
* MySQL 5.5.52-cll

### Reproducible Bug Summary 
I had a site running YOURLS v1.6 but could not install a second site running 1.7.1

1. Follow instruction steps, including making appropriate config.php changes; set DEBUG to true
2. Go to <http://mydomain.co/admin> and tail the error_log
3. Receive an error page indicating too many redirects; error log reads: Table 'databasename.options' doesn't exist SELECT `option_name`, `option_value` FROM `options` WHERE 1=1 in /path/...//includes/ezSQL/ez_sql_pdo.php on line 165

After a fair amount of trial and error I copied the 1.6 admin directory to my new site, and it worked.

So I don't know the specific issue in the installer, but it seems that the 1.7.1 installer was not actually building the tables, but the 1.6 installer did.

**Comment by ozh** [comment]
Definitely cannot reproduce, and I think if the installer was broken the issue would have been raised a couple dozens of thousands installs earlier...

"After a fair amount of trial and error" makes this report invalid, though, since we don't know what happened and what you did.

For the record, getting a notice about "databasename.options doesn't exist" during first install is completely normal and expected.
