### ISSUE TITLE
admin page alteration?

### ISSUE THREAD

**Issue by joshp23** [YOURLS/YOURLS#2183]
Is there a way to alter the output of `yourls_html_addnew();` as it appears in the admin page? I have been digging about and cannot seem to find a way to add some options to this.

I am writing a plugin that adds expiration dates and/or a maximum click count to links. I would like to be able add these options right to the admin interface, and cannot seem to find a way to change that input field, and would prefer not to hack core.

Thanks

**Comment by ozh** [comment]
Indeed the whole content of the function is not filterable, as a few other functions. Not sure if we really need to, since there are several ways to add stuff to the form

A simple option would be to hook into action `'html_addnew'` and output extra fields. Another option is to inject JS code in the head to add extra fields to the form, like [this plugin does](https://github.com/katzwebservices/google-analytics-for-yourls/blob/master/plugin.php#L294)

**Comment by joshp23** [comment]
I really appreciate the simplicity of 
```
yourls_add_action('html_addnew', 'my_script');
function my_script(){
	echo "<script src=\"". yourls_plugin_url( dirname( __FILE__ ) ). "/assets/expiry.js\" type=\"text/javascript\"></script>" ;
}
```

Thanks!
