### ISSUE TITLE
How to setup the preview plugin like tiny.url

### ISSUE THREAD

**Issue by pepa65** [YOURLS/YOURLS#2196]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.0
* Caddy 0.9.5 web server
* On a Ubuntu 16.04 KVM VPS

### Question

I'm successfully using the Preview-URL plugin. On its wiki page it is hinted (under **more**) that TinyURL-like preview (with a preview.domain.com subdomain) can also be accomplished by modifying your server virtual hosts settings.
I have added a subdomain called preview.
_I was wondering what other steps are needed to make this work,_

**Comment by joshp23** [comment]
### Subdomain example

This explains how to configure an Apache web server to use a subdomain, such as https://preview.example.com instead of https://example.com/V~ to display your preview pages.

#### Part one: The virtual host

To use a subdomain for previews, we first need to add it in to the YOURLS virtual host conf file in Apache using the ServerAlias directive. Your conf file should look something like the following; notice that we are making use of the subdomain "preview".

```
<VirtualHost *:80>

	ServerName example.com
	ServerAlias preview.example.com
	
	DocumentRoot /var/www/YOURLS/
	<Directory /var/www/YOURLS/>
		Options -Indexes +FollowSymLinks +MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel info
	ErrorLog /var/log/apache2/error.log
	CustomLog /var/log/apache2/access.log combined
	
</VirtualHost>
```
You might find your Apache default virtual host config file at /etc/apache2/sites-available/000-default.conf.

Once you have made your adjustments make sure to save the file and restart Apache.

#### Part Two: YOURLS .htaccess file

The following rules need to be added in to the very top of the YOURLS .htaccess file. They make use of both mod_rewrite and mod_proxy, so both of these modules need to be enabled on your server.

```
RewriteEngine On

#  PREVIEW
RewriteCond %{HTTP_HOST} ^preview\.(example\.com)$ [NC]
RewriteRule ^/?([a-zA-Z0-9]+)$ https://%1/$1~ [P]
```
Any differences in your setup (eg. example.com) will necessitate an alteration of these rules in your particular system.

NOTE: If you are using SSL on your site, make certain to set SSLProxyEngine on in your virtual host, otherwise these proxies will fail. Else, you will have to adjust the above code accordingly.

**Comment by ozh** [comment]
\o/
Huge cheers to @joshp23

**Comment by pepa65** [comment]
I assume you're only supporting Apache... That doesn't solve my problem, but it's a pointer. I have given up on this for now.
