### ISSUE TITLE
Status of release

### ISSUE THREAD

**Issue by NanneHuiges** [YOURLS/YOURLS#2219]
While there is some activity on this project, but the last release seems to be `Dec 5, 2015`, which is quite a while ago.

This makes me wonder, what is the status of that release, and in broader sense, this project?

**Comment by ozh** [comment]
The master build is the way to go for people concerned about getting sporadic bug fixes. It's always as stable as possible because that's what I use on all my live YOURLS instances.

The status of the release is still "it works, has some bugs, can try the master" as always. The status of the project is still "it moves, slowly, but it moves" as always.
