### ISSUE TITLE
Remove trailing slash from YOURLS_SITE

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2244]
We should be more forgiving with noobs who cannot RTFM (or maybe don't understand English) and define their `YOURLS_SITE` with a trailing slash (eg `http://sho.rt/` instead of `http://sho.rt` as advised)

This is a very minor bug but it produces discrepancies in links, href and src's. For instance javascript and stylesheets are included correctly (`<script src="https://sho.rt/js/jquerybleh"`) but some other links are not (`var ajaxurl  = 'https://sho.rt//admin/admin-ajax.php';` or internal links such as `<a href="https://sho.rt//admin/tools.php">`)

For the record, roughly 4% (!!!) of YOURLS users misconfigure this variable with a trailing slash.

**Comment by TuKod** [comment]
**Solution One**

Calculate `YOURLS_SITE` and ignore the config file entry.

In YOURLS-PV (the multisite version I'm working on) I removed `YOURLS_SITE` from the config file.  (It is only needed for those using a subdirectory YOURLS, which I think is few).  Since PV allows YOURLS and WordPress to share the root-directory address, there is no need for sub-directory YOURLS anymore.

I then calculate what `YOURLS_SITE` should be. I also split `YOURLS_SITE` into `YOURLS_SITE` (mainly for the Admin stuff to build the shortened URLs), and `YOURLS_ABSURL` (which is used to build URLs for CSS, JS, etc.).

This allows YOURLS to move to its own directory (anywhere under the document root).  Likewise, it allows one YOURLS to service multi-domains (as if it were many standard installs) as well as coexist peacefully with WordPress in the domain root.

I am also considering changing `YOURLS_SITE` to `YOURLS_SITE_NAME` which would allow me to test and use `YOURLS_SITE` on existing installs, only if it is a sub-directory.  This requires no action by site Admins (other than updating their code).

Because both of these are calculated, it totally avoids the "very minor bug" of the extra slash.

**Solution Two**

**A More Complex Solution** would be to replace `YOURLS_SITE` in the config file with $yourls_site. 

`define( 'YOURLS_SITE', 'http://your-own-domain-here.com' );`
`$yourls_site = 'http://your-own-domain-here.com'`

Then rtrim right slashes just before writing this into `YOURLS_SITE`.
`define( 'YOURLS_SITE', rtrim( $yourls_site, '/' ) );`

I say **_more complex_** because you would need to get every YOURLS Admin, on every site, to make this change.

**Solution Three**

A little less problematic than Solution Two, but not as good as Solution One, this solution would be to change  `YOURLS_SITE`  to  `YOURLS_SITE_NAME` throughout YOURLS code (but NOT in the config file).  Then just after loading the config files, add this line...

`define( 'YOURLS_SITE_NAME', rtrim( YOURLS_SITE, '/' ) );`

This solves the problem at hand without forcing Admins to take action, but it is not as good of a long-term solution as Solution One.

**Comment by PopVeKind** [comment]
**This is what I did** in YOURLS-PV...

In **load-yourls.php** - right after the **config.php** file is loaded, I added...

```
// Check if config.php - YOURLS_SITE has a trailing slash error.
// W3C - Valid HTML5 - Valid CSS3 - Valid Links
if( defined( 'YOURLS_SITE' ) && '/' == substr( YOURLS_SITE, -1 ) )
	die( '<!DOCTYPE html><html><head><title>Configuration File Error</title><meta charset="utf-8" />
		<style type="text/css" media="screen">code.tt {	background:#ff8; padding:0 2px; }</style>
		</head><body><h1>Configuration File Error</h1>
		<p>Remove the last (or right) slash "/" for <code class="tt">define( \'YOURLS_SITE\'</code>.
		<br />This is in the <code class="tt">config.php</code> file for your site.</p></body></html>' );
```
This basicall works like:
`// Check if config.php was properly updated for 1.4`

If there is a trailing slash error in YOURLS_SITE, it dies with a Configuration File Error and gives information so the site Admin can fix the error.

The output of this test has been W3C Validated for HTML5, CSS3, and Links (in this case none!).

==========

_**Notes & Thoughts:** In PV, YOURLS_SITE is automatically calculated and YOURLS_SITE is only needed in config.php for backward compatibility, in the case of subdirectory sites. We are considering throwing an error in PV for any config.php defined YOURLS_SITE that is _not_ a subdirectory. Configuring YOURLS_SITE seems to be problematic for some people, and most of the time YOURLS_SITE is not needed in PV. It seems better to just remove it._

**Comment by PopVeKind** [comment]
YOURLS-PV (https://github.com/YOURLS/YOURLS/issues/2320) handles it this way...

In `Config.php`
Near the top of `public function define_core_constants()`
We add:
```
    // YOURLS-PV Check if config.php - YOURLS_SITE has a trailing slash error.
    if( defined( 'YOURLS_SITE' ) && '/' == substr( YOURLS_SITE, -1 ) ) {
        throw new \YOURLS\Exceptions\ConfigException('Config Error. YOURLS_SITE has a trailing slash error. Check config-sample.php and edit your config accordingly');
    }
```
Note: !defined YOURLS_SITE does **NOT** throw an Exception at this point as YOURLS_SITE is automatically configured later in the code.  We removed YOURLS_SITE from $must_haves as it is unnecessary and prevents auto-configuration.

**Comment by PopVeKind** [comment]
I might suggest removing `YOURLS_SITE` from the config file of most sites!

Splitting YOURLS_SITE - Added Features #2335 automatically calculates `YOURLS_SITE` so noobs don't have to do it.

**Comment by ozh** [comment]
What about those who don't fall into the "most sites" category?

**Comment by PopVeKind** [comment]
Good question @ozh - these would be those in the advanced user category! :)

## Short Answer
1. https in shorten URLs and 
2. subdirectory installs.

I'm slightly opposed to using code bloat, on every request, to catch config errors. In the install instructions, I would direct users to a diagnostic tab in the Admin area for checking their install _(the **final step** in the install and a **must use step** before writing a support issue)_.

## In-depth Information

In the [same comment ](https://github.com/YOURLS/YOURLS/issues/2335#issue-280374898)(see number 8 on the **List of Benefits**), I propose an **_Admin Diag Page Plugin_** (Noob Friendly!) _Personally, I believe this should in the core for all to use._

- **Adds a diagnostic tab** to the admin area

- Helps user fix the trailing edge slash configuration error

- **Provides Technical Details:** A list, regarding the environment, to **_copy/paste into issues_** - like server version, PHP version, database version, plus constants like YOURLS_ABSURL and YOURLS_SITE **_Examples:_**
Apache Ver = 2.x.x
PHP Ver = 7.0.2
MariaDB Ver = x.x.x
YOURLS_ABSURL = `https://sho.rt/yourls/`
YOURLS_SITE = `https://sho.rt` - Perfect!
~ ~ ~ **_OR_** ~ ~ ~
YOURLS_SITE = `https://sho.rt/y/` - **_WARNING_**: Remove the last (right) slash. (in Red)
~ ~ ~ **_OR_** ~ ~ ~
YOURLS_SITE = `https://sho.rt/y` - **_WARNING_**: Subdirectory sites must be in the same phyical directory. Rename the /yourls/ directory to /y/ and adjust .htaccess as follows... (in Red)

- **Fixing Noob Errors:** Offers easy advice!
**_Examples:_**
YOURLS_DB_PASS = your db password - **_WARNING_**: Check or Correct This. (in Red)
YOURLS_DB_PREFIX - **_MISSING_** : use config-sample.php to create a new config file. (in Red)

-  **Best Practices:** Gives advice like how to convert from a single site to Multisite.
 _(This assumes the **_MultiSite Plugin_** is activated and the site domain name is_ `sho.rt` _- this is automatically detected)._
**_Example:_**
**For MultiSite:** Rename config.php to sho.rt-config.php in the /user/ directory.

**Comment by ozh** [comment]
What @majordome says.

**Comment by PopVeKind** [comment]
Good question @ozh - these would be those in the advanced user category! :)

**Short Answer**
1. https in shorten URLs and 
2. subdirectory installs.

I'm slightly opposed to using code bloat, on every request, to catch config errors. In the install instructions, I would direct users to a diagnostic tab in the Admin area for checking their install _(the **final step** in the install and a **must use step** before writing a support issue)_.

**Long Answer** - See [In-depth Information](https://github.com/YOURLS/YOURLS/issues/2244#issuecomment-350398039)

**Comment by ozh** [comment]
I don't understand what you mean with "https in shorten URLs" regarding users for which all server vars $_SERVER, on which you heavily rely, don't populate as expected

**Comment by PopVeKind** [comment]
@ozh
## "https in shorten URLs"
`https://sh.ort/abc` vs `http://sh.ort/abc` This is not about admin pages.

HTTPS would still require YOURLS_SITE to be defined. I'd consider HTTPS an advanced user configuration. From issues I have read, it seems HTTP is used the majority of the time.

This patch uses YOURLS_SITE **_only_** in the formation of short URLs.   I changed the "YOURLS installation URL" part of the purpose.

YOURLS_ABSURL becomes the _"YOURLS installation URL"_ This allows _backward compatibility_ for config.php users with YOURLS_ABSURL defined.  I changed the "YOURLS installation URL" part of the purpose

Splitting the two purposes of YOURLS_SITE is absolutely required for many features, including multisite. Changing the "formation of short URLs" purpose of YOURLS_SITE would have made a smaller patch.  It
would also force every admin to modify their config.php - I do not consider that acceptable.

I would suggest catching the trailing slash error with a diag page in the admin area, not in bloated active code.

**Comment by PopVeKind** [comment]
## Special Syntax
In config.php YOURLS_SITE is the **_ONLY_** constant that has a _Special Syntax!_

The _Special Syntax_ of YOURLS_SITE is what causes the trailing slash error.

**Comment by PopVeKind** [comment]
## Shop Rules for Config Files.
_The shops I worked in had rules for config files._

Defined constants must be defined with either:
- **No Syntax**
- **Copy/Paste Syntax**

### No Syntax
Consider defining the parts of YOURLS_SITE `https://sho.rt/y` into three constants:
- **http or https** (protocol)
- **sho.rt** (domain)
- **y** (directory)

Although this method has three constants instead of one, without _Special Syntax_, it is much _less likely to be wrong._ YOURLS could adopt this even now, with cleaner results like an admin protocol override or directory.

It sounds like more options = more complexity.  However, most actual errors in config files are caused by _Special Syntax_. 

### Copy/Paste Syntax
The exception to the above are things which are copy/paste.
1. **_Type_** `edition.cnn.com` into a browser (I use Firefox and Chrome), and view the site.
2. Highlight and **_Copy_** `edition.cnn.com` from the browser address bar.
3. **_Paste_** into a text editor.
4. Results: `http://edition.cnn.com/` - **FAIL!**

**Comment by PopVeKind** [comment]
## $_SERVER Doesn't Populate Correctly!

As a University Professor, I cannot tell you the hundreds or even thousands of times I have heard this.  You can read this all over the Internet, even on php.net!  However, it is simply **not true!**

What people actually mean is Apache, IIS, and Nginx may populate $_SERVER differently.
To quote you,

> $_SERVER, on which you heavily rely, don't populate as expected

**_Expected by who?_** Did they actually read the Web Server Manuals? Or did they expect it because someone said it somewhere on some website, and it was quoted by a million other people?

Because you are talking about me, and the code I "heavily rely" on, I assume we are talking about $_SERVER being populated **as I expect it!**  I'm not a noob. I expect $_SERVER to be populated with the environmental server vars passed to PHP from the web server. I expect Apache to pass Apache vars, IIS to pass IIS vars and Nginx to pass Nginx vars - as defined in their respective manuals.  Likewise, I never expect Apache or Nginx to pass IIS vars!

Of course, different servers may pass different (confusing) vars into PHP.  A self-respecting coder would structure his code to not allow this to change the output from one server to another.  Here is an example:

1. $_SERVER[ 'HTTPS' ] is empty (does not exist or value equals **FALSE**) when **Nginx** detects HTTP.
2. The same condition (HTTP) in **ISS** is equal to **TRUE** and off!
3. In **Apache**, this returns '0' 'off' or **FALSE**.
- Obviously empty or 'off' means **_this test_** is not HTTPS _and further tests are needed._
- Likewise, 'on' or '1' after !== 'off' is always **_conclusive proof_** of HTTPS.
- Additionally, TRUE, FALSE, and '0' cannot determine if **_this test_** is HTTPS and further tests are needed.

```
if ( !empty( $_SERVER[ 'HTTPS' ] ) && $_SERVER[ 'HTTPS' ] !== 'off' ) {
    // good in IIS and Apache
    if ( 'on' == strtolower( $_SERVER[ 'HTTPS' ] ) ) define( 'YOURLS_PROTOCOL', 'https://' );
    if ( '1' == $_SERVER[ 'HTTPS' ] ) define( 'YOURLS_PROTOCOL', 'https://' );
}
```
**$_SERVER is Populated Correctly** and I can rely on results expected, based on the server manules.

I will absolutely agree with you that there are some _"noobs who cannot RTFM!"_ I had plenty in my PHP classes who thought all they needed was the PHP manual. They never even consulted the manuals for IIS, Apache, Nginx, etc, to see what was being populated in $_SERVER.

**Comment by PopVeKind** [comment]
@ozh

It might interest you to know that Define YOURLS_PROTOCOL was written and thoroughly tested, on different web servers, over a six month period by 18 experienced PHP programmers working together.

The need for this was due to an unreliable WordPress function `is_ssl()`, also based on $_SERVER.  This function fails in many places, like behind load balancers and reverse proxies, and in some IIS HTTPS servers.

Much of this faulty WP function now exist in function `yourls_is_ssl()` It likely doesn't matter on basic Apache and Nginx servers.  YOURLS is already relying on $_SERVER.

**Comment by PopVeKind** [comment]
# Patch Solution

@ozh - I believe we are very near an acceptable solution regarding this patch. It appears this is now just a matter of opinion, so let's work out a way forward.

## Opinions
1. For more than 15 years I have demonstrated that $_SERVER elements are 100% reliable and populate as expected, **_based on the web-server manuals_** (apache, etc.).

- Yet, StackOverflow posts abound like this one:
[Why is PHP's “SERVER_PROTOCOL” showing HTTP/1.1 even when using https?](https://stackoverflow.com/questions/16825243/why-is-phps-server-protocol-showing-http-1-1-even-when-using-https).  It is impossible to discern why this person expected `$_SERVER['SERVER_PROTOCOL']` to equal `'https'`?

2. I won't speak for your opinion. However, it does seem fair to say you appear apprehensive to use all $_SERVER elements because you believe some _"don't populate as expected."_

**THEREFORE**, we should rewrite the patch to remove as many $_SERVER elements as possible.

## Getting Help
My former student offered to post this on the _Alumni Newsletter_ (about 3,000 working programmers who, at one point or another, were my students in University). It would be helpful if you would first approve some ground rules.
## Proposed Ground Rules
1. Avoid Code Bloat, as much as possible, by putting new features into Plugins.
2. $_SERVER elements already used in the YOURLS Core Code are considered safe to use.
3.  $_SERVER elements currently used in the WordPress Core Code are considered safe to use. (75 Million WordPress websites have thoroughly tested these,)
4. Reduce or eliminate other $_SERVER elements as much as possible.
5. For security, I would also like permission to _freeze_ the `$_SERVER['HTTP_HOST']` with the following code in the early part of Config like this...

```
    // freeze the HTTP_HOST
    if ( !defined( 'YOURLS_HTTP_HOST' ) )
        define( 'YOURLS_HTTP_HOST', $_SERVER[ 'HTTP_HOST' ] );
```

**Comment by PopVeKind** [comment]
# Patch Rewrite

@ozh - I think we are near an acceptable solution regarding this patch. Based on your comment we should rewrite the patch to remove as many $_SERVER elements as possible. I will have my former students look into this. I would like your approval of these three _Instructions_ I will include for them.

## Proposed Rewrite Instructions
1. Avoid Code Bloat, as much as possible, by putting new features into Plugins.
2.  $_SERVER elements used in the WordPress or YOURLS Core Code are considered safe to use.
(75 Million WordPress websites have thoroughly tested these,)
3. May we have permission to _freeze_ the HTTP_HOST with the following code in the early part of Config. 

```
    // freeze the HTTP_HOST
    if ( !defined( 'YOURLS_HTTP_HOST' ) )
        define( 'YOURLS_HTTP_HOST', $_SERVER[ 'HTTP_HOST' ] );
```

**Comment by ozh** [comment]
To fix the trailing slash issue, I was more on something trivial like trimming YOURLS_SITE whenever it's used, not introducing yet another constant. There are already too much consts in YOURLS. Constants are nearly impossible to test in unit tests, and they cannot be modified by plugins.

**Comment by PopVeKind** [comment]
I see what you mean about unit tests.

1. Wouldn't it be better to **add a diagnostic page** to the admin area and fix the problem?

**_On install_**, it would help noobs get it right!
**_Run before support request issues_**, it could catch all kinds of errors and give solutions (reduce support requests) and provide a copy/paste into issues for environments like PHP Version, etc.

This would allow existing error checking code, that runs on every page load, to be removed.  The result would be some small performance boost and less error checking code bloat.

2. Another idea would be to **build an install page**, like WordPress uses, to build the config.php file.

Either or both of these would be easy enough to build.

**Comment by LeoColomb** [comment]
> build an install page

#1254 

> Either or both of these would be easy enough to build.

Let's do a Pull Request! 😄 🎉

**Comment by PopVeKind** [comment]
> _We should be more forgiving with noobs_ - [ozh](https://github.com/YOURLS/YOURLS/issues/2244#issue-225795584)

To really **_help noobs_** the most, we should move the core config options from config.php to the database.  A config page in the admin area could then ask human questions, that could be selected with a mouse click, and be properly stored in a machine-friendly format.  Here is a work-in-progress idea **_for noobs_**.

## Trivial Trimming
> _To fix the trailing slash issue, I was more on something trivial like trimming YOURLS_SITE whenever it's used, not introducing yet another constant._ - [ozh](https://github.com/YOURLS/YOURLS/issues/2244#issuecomment-351838782)

By my count, there are **42 Places** YOURLS_SITE is used.  Meaning 42 places we would need to add the trim function. It also means, when we move YOURLS_SITE to the DB, those 42 trim functions will not be needed and will contribute to _Code Bloat!_
## A Cleaner Trim
I suggest, **for noobs**, we rename YOURLS_SITE to YOURLS_SITE_URL and keep YOURLS_SITE in config.php **TEMPORARILY**, as we **_transition_** to putting the Config settings in the DB.  The Config class could trim YOURLS_SITE to define YOURLS_SITE_URL.

YOURLS_SITE (in config.php) would retire forever when moved into the DB.
## Split YOURLS_SITE Patch
> `$_SERVER`_, on which you heavily rely, don't populate as expected_ - [ozh](https://github.com/YOURLS/YOURLS/issues/2244#issuecomment-350537253)

I am currently making tests, and final adjustments, on the latest version of the **_Split YOURLS_SITE Patch #2335_**. Per @ozh comment above, this version does **not** _heavily rely_ on `$_SERVER` Eleven of the 42 YOURLS_SITE constants will be converted to YOURLS_ABS_URL and populated automatically.  If you want, I could easily change the other 31 to YOURLS_SITE_URL, as in _A Cleaner Trim_ transition (above).

- YOURLS_SITE = Transition to DB to be retired.
- YOURLS_SITE_URL = For building short URLs (Ex. `http://sho.rt`)
- YOURLS_ABS_URL = For building links to files (Ex. `http://sho.rt/yourls`) Needed for MultiSite and other Plugins as stated in #2335

**Comment by PopVeKind** [comment]
Moving the `Core Options` to the database would automatically fix this, see
DB Config Page and Installer Project #2380

Also, notice the **Ten Core Constants** this Retires (eliminates), and how they are replaced in the DB (`$ydb`) at the bottom of this working demo page...
[http://a.fil.net/s/admin/db-config.php?dev=notes](http://a.fil.net/s/admin/db-config.php?dev=notes)

- **YOURLS_SITE** is eliminated and so is the trailing slash problem.

`Core Constants` eliminated include:
1. YOURLS_HOURS_OFFSET (eliminated DST/Summertime offset problem)
1. YOURLS_LANG
1. YOURLS_UNIQUE_URLS
1. YOURLS_PRIVATE
1. YOURLS_COOKIEKEY
1. YOURLS_URL_CONVERT
1. YOURLS_DEBUG
1. $yourls_reserved_URL (array)
1. YOURLS_ADMIN_SSL (https code bloat)
1. YOURLS_SITE (trailing slash problem)

Constants are a problem for many plugins under developement.

**Comment by PopVeKind** [comment]
The **[HTTPS Plugin](https://github.com/YOURLS/YOURLS/issues/2391)** (and PR) will totally eliminate the trailing slash error. **https://github.com/YOURLS/YOURLS/issues/2391#issuecomment-382681179**
