### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by dipenpatel235** [YOURLS/YOURLS#2245]
How to upgrade from 1.7.1  to 1.7.2 ?

i have try to hit below link but not worked
https://myhost/admin/upgrade.php

getting below message
Upgrade not required. Go back to play!

**Comment by LeoColomb** [comment]
This issue lacks of details. Please re-open *this* issue if it still occurs, with reproducible steps and system details. Check this element's [Contributing Guidelines](CONTRIBUTING.md) for an example.

**Comment by ozh** [comment]
As stated in the blog post, you just drop files and overwrite and you're done.

**Comment by dipenpatel235** [comment]
Yes..
I have override all files.

Then I goto admin
And still say yours 1.7.2 is available.

I have 1.7.1

On May 10, 2017 6:19 PM, "྅༻ Ǭɀħ ༄༆ཉ" <notifications@github.com> wrote:

As stated in the blog post, you just drop files and overwrite and you're
done.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YOURLS/YOURLS/issues/2245#issuecomment-300471564>, or mute
the thread

**Comment by dipenpatel235** [comment]
Yes..
I have override all files.

Then I goto admin
And still say yours 1.7.2 is available.

I have 1.7.1

**Comment by ozh** [comment]
Not sure I understand. "still say yours 1.7.2 is available" and "I have 1.7.1" : well, that's what's expected. If you have 1.7.1, then it's normal if you're seeing a message about 1.7.2 being available...

Feel free to rephrase, I think we don't understand your problem.
(Also, please, a clean and doubled checked reply here, instead of a quick email with approximate English and typos, would surely help. See point 7 in [Bug Report](https://github.com/YOURLS/YOURLS/wiki/Bug-Report). Thanks.)
