### ISSUE TITLE
YOURLS_COOKIEKEY not being honored

### ISSUE THREAD

**Issue by michaelplemmons** [YOURLS/YOURLS#2255]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.0.16
* Alpine Linux: 3.5
* Nginx Server: 1.10.3
* PHP-FPM: 7.0.16-r0
* Browser: Chrome on Mac 58.0.3029.110

### Reproducible Bug Summary 

1. Add a cookiekey to config.php
2. Start php-fpm and nginx
3. Login to admin page
4. Go to tools and look at the signature

The signature I see listed on the Tools page does not match the value of the COOKIE_KEY line in config.php.

define( 'YOURLS_COOKIEKEY', 'cookiekey');

**Comment by michaelplemmons** [comment]
I have done some minor modifications to 
`function yourls_salt( $string )`
and write out to a file what cookiekey is used in that function.  I see the cookiekey I have in config.php but why do i not see the same value on the Tools page?

**Comment by ozh** [comment]
That's not what it's for.

The cookie key is used to encrypt the auth cookie, and you're supposed to make it long, complex, unique, and absolutely not memorable because you don't have to memorize it. Something like http://api.yourls.org/services/cookiekey/1.0/

What you're looking at on the Tools page is a secret key that you don't define but will be unique, short, and based on your cookie key.

**Comment by michaelplemmons** [comment]
Okay.  That makes sense but was not clear to me from the documentation.  Thank you.
