### ISSUE TITLE
Add hook for <head> area directly after opening <head> tag

### ISSUE THREAD

**Issue by billdacat** [YOURLS/YOURLS#2256]
YOURLS version 1.7.2
PHP version 5.5

Using this on an intranet that has compatibility mode on. With jQuery 2, this causes an error once a URL is submitted and the table tries to reload..

Object doesn't support property or method 'addEventListener'

This can be worked around by forcing it out of compatibility mode with the meta tag:
&lt;meta http-equiv="X-UA-Compatible" content="IE=edge"> 

But that meta tag has to come immediately after the head, and there's no hook there to tie into.

https://msdn.microsoft.com/en-gb/library/jj676915(v=vs.85).aspx

"The X-UA-Compatible header isn't case sensitive; however, it must appear in the header of the webpage (the HEAD section) before all other elements except for the title element and other meta elements."

Request:  add a hook point after the opening head tag so that this code can be inserted via a plugin instead of touching the core.

Thanks!

**Comment by dgw** [comment]
Happy to implement this if @ozh is willing to include it.

**Comment by ozh** [comment]
Actually not really needed since it appears you can make the server send the X-Whatever header instead of adding it to HTML source, and there are [plenty of hooks](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L28-L67) to do so

> The X-UA-Compatible header isn't case sensitive; however, it must appear in the header of the webpage (the HEAD section) before all other elements except for the title element and other meta elements.

> A web server can also be configured to specify the X-UA-Compatible header. If a web server specifies the header and the header also appears within the content of a webpage, the header in the webpage takes precedence over the one specified by the server.

How do do that in PHP in a plugin: `header('X-Whatever-OMG: LOL');`

Anyway, adding a meta tag hook would not hurt. The cleanest way I think would be moving the `<link rel="shortcut icon">` below all meta tags and adding a hook after all the meta tags, to end up with something like:

```html
<!DOCTYPE html>
<html <?php yourls_html_language_attributes(); ?>>
<head>
    <title><?php echo $title ?></title>
    <meta http-equiv="Content-Type" blablah />
    <meta name="generator" blablah />
    <meta name="description" blablah />
    <meta name="referrer" content="always" />
    <?php yourls hook, something with a name like `html_head_meta_tags` ?>
    <link rel="shortcut icon" blablah />
    <script src="blabla">
```

This way you could easily add, or even simply overwrite, meta tags.

@dgw Fancy a PR ? :)

**Comment by dgw** [comment]
Why yes, I do: #2258
