### ISSUE TITLE
Short domain selection option?

### ISSUE THREAD

**Issue by iTayGNR** [YOURLS/YOURLS#2271]
Hi,
I have lots of websites and I have just installed YOURLS on my general, personal domain.
Is it possible to have a domain selector for the shortened URLs? Because I have so many.

(for example, from the same admin panel, i will be able to short a url to domain1.com/abc OR domain2.com/abc)

Thanks!

**Comment by gmolop** [comment]
All that domains you have are already working? I mean, if you manually change the domain URL you get the same instance of yourls?  
You have already set up your server to point to the same root
Like:

- domain1.com/abc -> http://example.com/some_page
- domain2.com/abc -> http://example.com/some_page

If so, I write a plugin for that [yourls-domain-swap](https://github.com/gmolop/yourls-domain-swap). Same instance of yourls, different domains.
It has a dropdown in main interface to change domain and a config page where you can add new domains.
Let me know if this can be helpful for you.

If you mean different domain (same short) takes you to different target:

- domain1.com/abc -> http://example.com/some_page_1
- domain2.com/abc -> http://example.com/some_page_2

Then I presume you need two installations of yourls, with different databases.

**Comment by iTayGNR** [comment]
@gmolop is it possible with your plugin to have the same URL code but different domains?

for example, if I own domain.com and example.com, will I be able to have different destinations for `example.com/this` and `domain.com/this`?

**Comment by gmolop** [comment]
No, different targets (any part) for the **same short** is not possible.
The database `yourls_.yourls_url` has the `keyword` (without domain) and `url` that's the target.

I can't imagine how two equal shorts can take you to two different targets.
When has to redirect to one and when to the other?

I have another plugin for that but is basically an A/B tester, one short takes you to different target based on a percent of traffic... But is not what you require I presume.

**Comment by dgw** [comment]
I suppose one way would be to create a plugin that maps the domain and keyword to a prefixed keyword internally (e.g. `domain1.com/this` internally looks up the keyword `domain1_this`; `domain2.com/this` internally looks up `domain2_this`, etc.).

But it's probably easier to just set up separate instances of YOURLS with their own databases or database table name prefixes. You can share most of the files with hardlinks or symlinks in the file system 
(assuming your OS supports them), or point all the Apache/nginx/whatever hosts to the same YOURLS directory and `include()` the site-specific pieces (if any) in `user/config.php`, since it works just like any PHP file.

**Comment by LeoColomb** [comment]
All seems to be said, 3 options:
* One install per domain;
* One install for all with unique keyword-target;
* One install for all with plugin to map domain.

Thanks guys! @dgw @gmolop
