### ISSUE TITLE
Possible to see UNIQUE clicks?

### ISSUE THREAD

**Issue by Thomas3520** [YOURLS/YOURLS#2274]
Hello!
It would be helpful, to see unique clicks...

Can someone make a plugin? :-)

**Comment by dgw** [comment]
The clicks that YOURLS tracks should already be pretty unique, unless you're running a plugin that changes the redirect type. By default, YOURLS uses HTTP 301, which is considered "permanent", and therefore browsers and other clients will cache them for a long time. So, a single client opening one of your short URLs will likely only get counted once (unless their cache is cleared or something).

If you're trying to track "unique clicks" based on the user, not the client, that's not possible. Users may use different browsers, different devices, move from one network to another (and get a new public IP), and so on. A subset of these applies to tracking unique devices, since multiple browsers might coexist on a single device, without sharing a redirect cache.

**Comment by Thomas3520** [comment]
Wow, what a fast reply... (^<>^)
Well, I clicked on an url 3 times (from the same beowser), and it displays 3 clicks...
Isn't it possible to see unique clicks based on the ip? And most of the time, users don't switch browsers...

**Comment by LeoColomb** [comment]
> Well, I clicked on an url 3 times (from the same beowser)

Depending of your browser settings and how you "clicked". 🔍 

> Isn't it possible to see unique clicks based on the ip?

Yes, everything is possible, but you may have a lot of false positives: eg. every terminal on my university network is behind one of the 3 shared public IPs for the all university…
So second excellent @dgw answer, it will not be very relevant.

> And most of the time, users don't switch browsers

Ha ha, you can't imagine how much! 😆 

---

Closing: plugin request

**Comment by gmolop** [comment]
In the way we use the system, we also need the unique IP counter, in our case, by country.
I have add a new query and modified the graphic to add and show something like this...

    "SELECT `country_code`, COUNT(distinct `ip_address`) AS `count` FROM `$table` WHERE `shorturl` $keyword_range GROUP BY `country_code`"

Hope that you can be helpful for you.

![](https://monosnap.com/file/BW63V5HkFR8SR7INmCjsnKEZQmlWYD.png)
