### ISSUE TITLE
Installation teething problems - URL forwarding to my hosted directory breaks the Admin panel

### ISSUE THREAD

**Issue by Auselan** [YOURLS/YOURLS#2296]
Thank you in advance for your advice - I have now spent ~2 hours trying to crack this config issue, including reading the readme, wiki and searching the forums - time to ask for help.  I think it is probably quite simple.

My installation is good and works without issue.
Installation folder is http://p1-preview.agilityhoster.com/tomnichols.com/YOURLS-1.7.2
Config.php is set up as:
`define( 'YOURLS_SITE', 'http://p1-preview.agilityhoster.com/tomnichols.com/YOURLS-1.7.2' );`

I have invested in a new domain name, occg.info and I am using Framed Redirection for the domain, pointing to my YOURLS installation folder as above and it works perfectly, showing me the root directory with http://occg.info in the address bar in my browser.

I thought that I could simply change the configuration line to 
`define( 'YOURLS_SITE', 'http://occg.info' );`

When I do so and try to log in to the panel, the formatting of the page has been lost - the PHP renders in the top left hand corner, and I am unable to log in.  I suspect this is because the hosted files need to access the Database from what 'appears' to be a local file, not from an external URL referrer.

Surely there must be some way around this and I wonder if anyone knows immediately how?

**Comment by ozh** [comment]
This won't work. You're using a frame: it means it's just "framing" every request into HTML code.

While this works for a URL you'll want to access with your browser, eg http://occg.info/admin/, this won't work for anything that's included by code, eg `<script src="http://occg.info/js/some.js" />` because `http://occg.info/js/some.js` get converted as `<html>...<frame src="http://p1-preview.agilityhoster.com/tomnichols.com/YOURLS-1.7.2/js/some.js....` which isn't something that can be included.

So : "redirection frame" **won't** work.

**Comment by Auselan** [comment]
Thank you

Although it isn't perfect, all I have to do is paste the short URL alias after my domain name, and it will parse it without issue e.g. although my long link is http://p1-preview.agilityhoster.com/tomnichols.com/YOURLS-1.7.2/Proformas I can just manually create the link http://OCCG.info/Proformas and it will work fine.

Having searched even further, there is a Plugin which says that it should allow this function:
https://github.com/adigitalife/yourls-allow-aliases

I can't get the plugin to Activate though and I think it may be 'broken'
