### ISSUE TITLE
Strange question

### ISSUE THREAD

**Issue by DataDrug** [YOURLS/YOURLS#2308]
Hello guys,

I have a doubt and I have the hope that someone can clarify me.

So I have a service, and on that service I'm required to sell newsletters daily, and amazon links are an extra income. The issue is that amazon affiliates are forbiden to be sent by newsletter, hence, I started using YOURLS!

However, I need to have a script on the page that links my costumers to the amazon country of their preference. In a normal site this would be on the page where a certain affiliate link is placed, however since I use YOURLS for the shortning and redirecting, I'm wondering I need to past this script here.

I'm really tired so excuse me if this didn't made any sense but I don't know what else to do.

Thank you all!

**Comment by dgw** [comment]
I'm not sure there's enough detail here to offer a real solution (what does the script do, is it run for all links or only for "a certain affiliate link", where is the customer's country preference stored, etc.). This might be plugin territory, or it might be solvable with JavaScript in the right place, I don't know.

I am going to close the issue though, because it's not a YOURLS bug—but feel free to continue the thread, even if it's closed!

**Comment by DataDrug** [comment]
Hi again,

Basically this is what the script does:

With our new service, “OneLink”, you now have the ability to monetize international traffic from the United Kingdom (UK) and Canada (CA), while offering your visitors an improved shopping experience by automatically redirecting them to their local Amazon storefront to complete their purchases.

the issue is that this won't work with shortened links, mainly because I do belive that when the link goes from shortened to original link the script is missing there.

I do believe it's totally solvable by having the little script in the right place, I was hoping to have some lights on where.

Anyway, thank you for your time.

**Comment by dgw** [comment]
OK, so the thing is, oneLink's JS can't interact with YOURLS's redirection at all, because the redirect happens before any page content is even loaded, let alone scripts. (It's sent in a header field.) You're right that the script is missing, because there's no place to put it.

The best idea I can think of is creating an interstitial page that YOURLS will show instead of redirecting the user (something like [this plugin](https://github.com/joelgratcyk/yourls-interstitial-plugin/blob/master/plugin.php), perhaps), and on that interstitial page include the real affiliate link, the oneLink script, and some code snippet to send a `click` to the link once oneLink has done its job.

Of course, you could also port the oneLink JavaScript code to a plugin written in PHP somehow. Intercepting the redirect URL is trivial with the plugin API; the real work would be getting a working PHP implementation of Amazon's code, and keeping it updated if they change how the JS version works.

**Comment by DataDrug** [comment]
> The best idea I can think of is creating an interstitial page that YOURLS will show instead of redirecting the user (something like this plugin, perhaps), and on that interstitial page include the real affiliate link, the oneLink script, and some code snippet to send a click to the link once oneLink has done its job.

> 

From a scale from 1 to 10, how hard would this to be for someone with the average knowledge in this languages to create ?

**Comment by DataDrug** [comment]
Hi again, sorry for the dumb question. I made sense of it, just needed to take a new look after resting.

It's working, and the interstitial just pops for like 3seconds displaying a redirect gif. 

Perfect.

**Comment by DataDrug** [comment]
Coming back with some news.

Even though it seemed working, the urls are not being forwarded to the domain extension. 

I was expecting that the " refresh:5;url=%url%" did the trick, but perhaps i need something like that in the body section. Any idea on how to do it?

Thank you again for the help.

**Comment by dgw** [comment]
I haven't the patience to dig through the minified OneLink JS, but I very much doubt that it touches meta-refresh tags.

What I had in mind yesterday was putting a regular link on the interstitial page, along with the script, then triggering a `click` event on that link with your own JavaScript after a few seconds. Bonus points for finding a way to detect when the OneLink code has loaded and finished running. The downside is that redirects won't really work at all for browsers without JavaScript turned on, but you can still put a longer timeout than what your JS uses in a meta-refresh tag as a fallback I guess.

Sorry for not being as clear as I could have been! :smile_cat:

**Comment by DataDrug** [comment]
Can you please point me to a good example of a timed click? I've seen so many examples and I'm not sure what is the best one!

**Comment by dgw** [comment]
Simplest approach AFAIK is something like this, assuming you give the `<a>` tag with the link to be rewritten an `id` attribute:

````JavaScript
function clickIt() {
    document.getElementById('thelink').click();
}
window.setTimeout(clickIt, 5000);
````

Been a while since I did anything like this, and I'm just scribbling untested code on my phone, but that's the general idea at least :)
