### ISSUE TITLE
Multiple Domains? Plugin maybe?

### ISSUE THREAD

**Issue by stevenmcastano** [YOURLS/YOURLS#2319]
I was doing a little research and didn't find anything specific about multiple domains. I have a YOURLS install that's working great load balanced between a few servers and backed by a nice size DB cluster and instead of doing multiple installs, I was wondering if it's possible to support multiple domains with a single install?

I know I can just map multiple hostnames and certificates through my nginx front end, but I'm working if there's anyway to have the short links be sorted and/or create with a different root domain?

For instance, if I create https://link.example.com/abcd, I'm sure I could also access it from https://link.anotherdomain.org/abcd, but all the reporting, share functions, etc, all would point to the original domain when I'm looking at them. Is there any better of sorting and displaying things?

**Comment by ozh** [comment]
Virtually anything is possible with a plugin.

Regarding multiple domain support, there are [MTOWTDI](https://encrypted.google.com/search?q=yourls+multiple+domains) as the Perl monks say, because in the end it really depends on your server config (vhost config, name aliases, directory structure and directory permissions, tweaking things at PHP level or htaccess or nginx file level, etc...)

For starters I think you may dig into the Google search I mentioned above, maybe [that plugin](https://github.com/YOURLS/YOURLS/wiki/Plugin-List#allow-aliases), and maybe issue 2306 where someone explains in just 30,000 lines of comments what they did regarding this very specific matter

**Comment by ozh** [comment]
(and, yes, the correct way to do so, no matter the logic behind, should be a plugin)

**Comment by mashirozx** [comment]
I think it cloud be more easy using a Nginx proxy:
```nginx
server {
	...
	location / {  
		proxy_pass https://the,main.domain/;  
	}	
	...
}
```

**Comment by developersteve** [comment]
@mashirozx thats how i do it, running a few sites on the same yourls instance. In config.php under user directory you need to do the following for the yourls site listing (makes the config dynamic)

```
define( 'YOURLS_SITE', 'https://'.$_SERVER['SERVER_NAME'] );
```

**Comment by hetzbh** [comment]
@mashirozx I just tried your tip, but it does not allow admin login from the new domain...
