### ISSUE TITLE
Suggestion: Keep the number of displayed links as the default in all current/future sessions.

### ISSUE THREAD

**Issue by YLSnewb** [YOURLS/YOURLS#2339]
Hi.

Quick request for a feature.  The default page length of 15 "links" is annoyingly small.  I'd like to set a new default length, and have it persist between sessions.  For example, if I log in, I get the first 15 links.  If I switch that to 50 then click 'Search', add a few links, then click on the 'Admin Interface' link at the top, it reverts back to 15 items per page.  

I'd prefer that there was either an easily accessible pop-up menu, or configuration variable to set the default number of links to show -- either from a short list of prechosen values (50 100 200 ALL) or a user defined value.

Thanks.

**Comment by YLSnewb** [comment]
I resolved this issue by editing this line in admin/index.php:

$perpage         = ( isset( $_GET['perpage'] ) && intval( $_GET['perpage'] ) ? intval($_GET['perpage']) : yourls_apply_filter( 'admin_view_per_page', 15 ) );

and changed 15 to 99.

**Comment by PopVeKind** [comment]
The code you wrote has a filter, this makes it easy to make a plugin to do what you want.  Why not write a plugin that will benefit everyone?

You should not hack core files for things you can put in a plugin.

**Comment by YLSnewb** [comment]
I didn't write that line of code, I simply changed the default number.   I'm totally NOT qualified to be writing PHP, hence the hack.  While it would be nice to have this as a configurable parameter in future versions, if someone else has a similar complaint, they now know how to do it.  That someone will probably be me when I upgrade YOURLS to the latest-and-greatest release.

**Comment by ozh** [comment]
There won't be a configurable parameter for this in any future version, because there are 10,000 people who think that tiny option and this little feature should be a parameter, and we would end up with a mammoth setting page.

That's exactly why there is a plugin API: to [keep things light](https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin#keeping-things-light)

Also, while it's perfectly understandable that you don't think you qualify to write a plugin, just be aware why [you should not hack core files](https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core).

Regarding @PopVeKind's comment, yes a very simple plugin would do, would have been nice if he even wrote that simple plugin, what do you think? :)

Simple plugin : 

```
<?php
/*
Plugin Name: Custom number of displayed links
Plugin URI: http://yourls.org/
Description: Custom number of displayed links
Version: 0.1
Author: Ozh
Author URI: http://ozh.org/
*/

yourls_add_filter( 'admin_view_per_page', 'ozh_custom_number_of_displayed_links' );
function ozh_custom_number_of_displayed_links() {
    return 99;
}
```

See how simple it is? I'm sure that if you know how to skim the source and edit a simple stuff, you should read a couple wiki pages and make simple plugins like this.

**Comment by PopVeKind** [comment]
YES! @ozh - That's pretty much the plugin I had in mind! :) I might have made it 50 lines and allowed a custom constant to change it to any number defined.

I must admit, I do like some of his plugin ideas!
1. I don't like looking at 10-15 items out of hundreds or thousands.  For example, when I log in to work on domain names, I look at 100-200 per page! Or I search!
2. You helped him write a plugin #2341 and I admit, it might have value to me. One of the sites I'm designing will be a YouTube channel with a webpage for resources and more info, per video (lots of YOURLS work!).  Three people will work on the project, but all have the same IP, our network address.  Having a column full of the same IP might trigger someone!

As I stated, some good plugin ideas!  Thanks for asking my opinion.  I might even revisit these two plugins next year after I finish the YOURLS_SITE patch, the six plugins I am committed to, and the full-fledged installer! :)
