### ISSUE TITLE
Diagnostic Page Project

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2340]
# The Project
_**The Diagnostic Page Project** is actually a companion to the **Full-fledged installer Project**_ #1254

**_Their purposes are as follows:_**
1. To make configuring YOURLS easy.
2. To eliminate configuration errors.
3. To reduce code bloat caused by catching, or fixing, configuration errors.
4. To Improve YOURLS Performance!
_No code is faster than no code!_

Whereas the Full-fledged installer works during installation, the Diagnostic Page is for existing sites, including manual modification of the config page.

**Comment by PopVeKind** [comment]
## The Diagnostic Page
**_The Diagnostic Page would be located in the Admin area and would contain the following sections._**
1. ERRORS: Repairing The Configuration
2. WARNINGS: Possible Problems
3. Technical Details Regarding My Environment

**Comment by PopVeKind** [comment]
## ERRORS: Repairing The Configuration
**_This Section produces advice to fix detected errors._**

The Output would be something like this:
- YOURLS_SITE = `https://sho.rt/y/` - **ERROR:** Remove the last (right) slash.
- config.php file found in `/includes/` directory. **ERROR:** Move to `/user/` directory.
- YOURLS_DB_PASS - **ERROR:** MISSING - use config-sample.php to create a new config file.
- YOURLS_DB_USER - **ERROR:** MISSING - use config-sample.php to create a new config file.
- YOURLS_DB_NAME - **ERROR:** MISSING - use config-sample.php to create a new config file.
- YOURLS_DB_HOST - **ERROR:** MISSING - use config-sample.php to create a new config file.
- YOURLS_DB_PREFIX - **ERROR:** MISSING - use config-sample.php to create a new config file.

**Comment by PopVeKind** [comment]
## WARNINGS: Possible Problems
**_This Section produces advice on detected warnings. These may or may not be errors._**

The Output would be something like this:
- YOURLS_DB_PASS = `your db password` - **WARNING:** Check and/or Correct This.
- YOURLS_DB_USER = `your db user name` - **WARNING:** Check and/or Correct This.
- YOURLS_DB_NAME = `yourls` - **WARNING:** Check and/or Correct This.
- YOURLS_DB_HOST = `localhost` - **WARNING:** Check and/or Correct This.
- YOURLS_DB_PREFIX= `yourls_` - **WARNING:** Check and/or Correct This.

**Comment by PopVeKind** [comment]
## Admin Default Suggestion
I suggest that when it is completed, we make the Diagnostic Page the default page after login.  This will help a lot of noobs find the problems with their sites.

**Comment by LeoColomb** [comment]
@PopVeKind Wow wow wow, please keep in mind each time you're posting a new comment you're sending a mail to about 300 people following this repo.
So please keep it simple and please keep it in a single post as much as possible.

Thanks! 👍

**Comment by ozh** [comment]
All of this isn't stupid ideas at all, but I don't think this is something we need.

Regarding what you call errors: they should simply halt at install. There's no need to code something to produce output and analysis, let's just die with an error message as it's done now.
- Extra trailing slash is just a cosmetic issue ;
- config in /includes/ instead of /user/ is legacy but OK (98.3% in "/user" as of writing: let's not code something to deal with less than 2% of installs, most of which may probably be abandoned or dead since this setting goes back to the very first versions);
- DB settings errors just won't work anyway.

Regarding what you call warnings, I don't think of one single thing that we should output as a warning. Either it works, then fine, or it doesn't, then die with an error.

Regarding the technical details: I think that's typically plugin territory. But most errors make YOURLS die before it can even load plugins. Also, the very very vast majority of users simply never open a support request or trouble issue (roughly 2000 issue vs more than 100K install, again let's not code something for less than 2% of users)
