### ISSUE TITLE
Suggestion:  Allow the "IP" address column to be hidden when YOURLS is configured in 'private' mode.

### ISSUE THREAD

**Issue by YLSnewb** [YOURLS/YOURLS#2341]
Hi.  One more little suggestion.  I'm running YLS in 'private mode' - so I'm the only one creating links.   I'd love to have the option to collapse / hide / omit the "IP" column from displaying in the default display.  This looks like it might be a little harder than my previous suggestion, but it would be nice to have.  I'll play with the code and post any insights / hacks I come up with for the community.  :)

Thx.

**Comment by YLSnewb** [comment]
Wrote this:  

<?php
/*
Plugin Name: Remove the IP Address column from the admin interface
Plugin URI: http://example.com
Description:  Remove IP column from admin interface.
Version: 0.01
Author: YLSnewb
Author URI: http://example.com
*/

// If you run a 'private' YLS, the IP probably isn't important to you.
yourls_add_filter( 'yourls_table_head', 'psychotix_omit_ip_header' );
function psychotix_omit_ip_header() {
unset($cells('ip'));
return $cells;
}

yourls_add_filter( 'table_add_row_cell_array', 'psychotix_omit_ip_column' );
function psychotix_omit_ip_column() {
unset($cells('ip'));
return $cells, $keyword, $url, $title, $ip, $clicks, $timestamp;

}

Got this:
2017/12/16 03:09:16 [error] 5511#5511: *9565 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Can't use function return value in write context in /var/www/YLS/user/plugins/no-ip-address/plugin.php on line 14
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/YLS/admin/plugins.php:0
PHP message: PHP   2. yourls_activate_plugin() /var/www/YLS/admin/plugins.php:25" while reading response header from upstream, client: 24.52.52.93, server: example.co, request: "GET /admin/plugins.php?action=activate&plugin=no-ip-address&nonce=5357b04755 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "example.co", referrer: "https://example.co/admin/plugins.php"

The intro to plugins doesn't give an example of modifying contents of an array (just a single variable) and being new to PHP, I find the error message indecypherable.

**Comment by ozh** [comment]
Accessing an array in PHP is `$myarray[$index]` or `$myarray[19]` or `$myarray["omg"]` or `$cells['ip']`, not with parenthesis as you wrote `$cells('ip')`. Parenthesis are function calls.

Also, the problem is that your function `ylsnewb_omit_ip_column()` doesn't accept any argument, hence cannot unset or return anything.

The [filter on this line](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L608) passes various arguments to any function hooked into it (namely: `$cells, $keyword, $url, $title, $ip, $clicks, $timestamp`), so eventually this line can act as  `$cells = somefunctionthatmodifies($cells, $keyword, ...)`

In your case you want to modify $cells regardless of other parameters, so your function should be passed only $cells, modify it, and return it. Something like:

```php
function ylsnewb_omit_ip_column($cells) {
    unset($cells['ip']);
    return $cells;
}
```

Same for `ylsnewb_omit_ip_header()`.

Another option would be to simply output some CSS in the header and hide the IP column.

Important tip: please format your code output, using ` ``` ` or ` ```php` at the beginning of a code block, otherwise it's not very readable. [Syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

**Comment by YLSnewb** [comment]
And the working plugin for any future people who might appreciate it:

```<?php
/*
Plugin Name: Remove the IP Address column
Plugin URI: http://example.com
Description:  Remove IP column from admin interface for 'private' YLS installs where this info isn't likely to be useful.
Version: 0.01
Author: YLSnewb
Author URI: http://example.com
*/

// If you run a 'private' YLS, the IP probably isn't important to you.
yourls_add_filter( 'table_head_cells', 'ylsnewb_omit_ip_header' );
function ylsnewb_omit_ip_header($cells) {
unset($cells['ip']);
return $cells;
}

yourls_add_filter( 'table_add_row_cell_array', 'ylsnewb_omit_ip_column' );
function ylsnewb_omit_ip_column($cells) {
unset($cells['ip']);
return $cells;
}

**Comment by ozh** [comment]
:+1: Now give this plugin its own repo and get it listed on the list of all [YOURLS plugins](https://github.com/YOURLS/YOURLS/wiki/Plugin-List) :)
