### ISSUE TITLE
Plugin Skimlinks has no working download link

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2347]
Maybe someone have this plugin installed or downloaded? 
The author is not response to my messages :(

http://www.mattytemple.com/2010/12/yourls-plugin-skimlinks/

**Comment by PopVeKind** [comment]
@seventhsite 
I've been thinking about what to do with abandoned plugins?

I am writing a change that will move the config.php settings into the database for easier use, especially for noobs,  This is sort of a five-pronged project.
1. Move the settings
1. Create an admin config page to adjust the settings
1. Adjust the code to use an object instead of constants
1. Build a full-fledged installer
1. Make this major change simple and easy for noobs (like WordPress).

This may cause some poorly written plugins to fail.  And what about plugins that have been abandoned or cannot be downloaded from the original source?  Or what about plugins that simply fail due to changes in the core code?

As you said///

> The author is not response to my messages :(

Should we maintain a more detailed list regarding Plugins and Core version compatibility?
Should we maintain a backup download location?

**Comment by PopVeKind** [comment]
I found this:
https://github.com/mattytemple/YOURLS-Plugin--Skimlinks

And backed it up (forked it) here so it won't get lost:
https://github.com/PopVeKind/YOURLS-Plugin--Skimlinks

Does anyone else think we need a place to backup all plugins listed on the YOURLS website?

**Comment by ozh** [comment]
@seventhsite you can submit a PR to the plugin list with the updated location
@PopVeKind mirroring a plugin, unless explicitly mentioning it, means you'll offer support to it
