### ISSUE TITLE
YOURLS is compatible with Firebase database ?

### ISSUE THREAD

**Issue by 15r** [YOURLS/YOURLS#2349]

**Comment by dgw** [comment]
"Firebase helps you build better mobile apps and grow your business." YOURLS is not a mobile app, and does not run any database code in JavaScript. Firebase's database service offers SDKs for Android, iOS, and JavaScript only, as far as I know.

Since you didn't provide any context, that's the best answer I can give you. I don't know why YOURLS would be compatible.

@ozh What happened to @majordome? This should have gotten an auto-response because the issue template was ignored, then removed.

**Comment by ozh** [comment]
@dgw I don't know why majordome didn't answer. Maybe @LeoColomb has pulled the plug on his bot :)

Regarding Firebase, there's probably a way to make YOURLS work with it. There's a [PHP SDK](https://github.com/kreait/firebase-php/). So, no, out of the box, YOURLS isn't "compatible" with Firebase, but it's clearly possible to make a plugin for it.

**Comment by dgw** [comment]
Making a plugin would be trickier than a normal job to support a new database engine because Firebase is NoSQL (it stores and retrieves JSON). But yes, it is clearly possible.

**Comment by SachinSAgrawal** [comment]
Five years later ... has anyone managed to do this? If so, how?
