### ISSUE TITLE
Massive spam issue even though domains are blacklisted and only admin or API can shorten

### ISSUE THREAD

**Issue by olenoerby** [YOURLS/YOURLS#2353]
### Technical details regarding my environment

* YOURLS version: 1.7.2
  * Plugins enabled: 404 Redirect, Anti spam, Google Analytics, Force Lowercase, Change error messages, Mass remove links, Random backgrounds, Random keywords, SSL for SSL, Yourls Abusedesk, reCaptcha.

* PHP version: 7.1
Running on a Ubuntu 17.10 with quite a bunch of subdomains - a lot running PHP, but none of them having been hacked before.

### Bug description 

My instance of YOURLs gets a lot of spam domains or malwareridden domains by many different IP's and countries even though the domains they shorten are banned.
Example: 
It's not even possible to shorten big sites such as YouTube, yet still a link or two appears daily in my administrative panel with multiple clicks already on it. 

HOW does this happen and how do I block it if even administrator-login, captcha and regeneration of the API key doesn't block it?..

**Comment by ozh** [comment]
URL ?

**Comment by afahmiparidin** [comment]
Hi @ozh ,

this is to share probably the same concern as @olenoerby 's post.

This is my POC for yourls.org -> http://tlkm.my/

i closed the form, however there's still unidentified input in url created.

![image](https://user-images.githubusercontent.com/5966211/38475534-6b0a7456-3bdb-11e8-81b0-e1ebadd62e2b.png)

if we see the ip, it's an invalid ip format

1.1 4709a868646bacc9738100003797f08a d

so, there's somewhere that spammer can get to create the link without form.

Thank you,
**Fahmi Paridin**

**Comment by ozh** [comment]
@afahmiparidin : most likely this isn't added to the YOURLS DB using standard input, since in that case the IP would be determined by the system, yet here it appears the value is being submitted. I suggest you change your secret key (see https://github.com/YOURLS/YOURLS/wiki/PasswordlessAPI) and your server passwords (MySQL, FTP)

**Comment by afahmiparidin** [comment]
Dear @ozh, thanks for the reply. 

For sure .. will do as per recommended. however, if i find out anything wrong, i'll let you know.

**Comment by PopVeKind** [comment]
@afahmiparidin - Hi Fahmi!
I agree with ozh, it looks like someone got into your site,  It is hard (pretty much impossible) to fake the IP from outside of a system because it is used to return the reply.  So... it looks like your system was comprised from inside, rather than outside.

Beside the secret keys ozh told you about, and things like usernames, passwords, and YOURLS_COOKIEKEY (in config.php) there are more passwords you really need to change/strengthen. You may want to take a look at the tips on this page http://a.fil.net/s/admin/setup-config.php?step=0

Beyond MySQL and FTP passwords, you may have a password to admin your server from a webpage.
Likewise you may have a password for something like PHPMyAdmin with a ridiculously simple password (or no password from within the website). Your hosting company may have set this up without you even knowing it.  With access to a PHPMyAdmin account, for your server, I could change everything in your YOURLS database!  And never even get close to your website form!

Finally, when a cracker gains access, he might not want to lose it!  Most crackers will add hidden code to files you expect to be there.  The easy way to fix this is to copy all the core files onto your server again.  The standard files will not have the extra code and will therefore wipeout any added codes.  Just be aware of your custom files.  For example, config.php. Any file you made any change to manually, you will want to save before you upload the new files.

I hope this helps you Fahmi

**Comment by afahmiparidin** [comment]
@PopVeKind yeah, well that helps.

> Finally, when a cracker gains access, he might not want to lose it! Most crackers will add hidden code to files you expect to be there. The easy way to fix this is to copy all the core files onto your server again. The standard files will not have the extra code and will therefore wipeout any added codes. Just be aware of your custom files. For example, config.php. Any file you made any change to manually, you will want to save before you upload the new files.

forgotten already about this tip. Thanks for reminding me.

**Comment by dgw** [comment]
Since this sounds like the result of a compromised server, I'm going to close it. We can reopen if it turns out that the entry point was YOURLS after all.
