### ISSUE TITLE
Order by Title

### ISSUE THREAD

**Issue by 271289** [YOURLS/YOURLS#2356]
Is there any possibility to order by title in the admin interface?

At the end of admin interface you can order by
- Short URL
- URL
- Date
- IP
- Clicks

...but not by "Title".

My titles look like this
- "Product 1 > Link 1"
- "Product 1 > Link 2"
- "Product 2 > Link 1"
- "Product 2 > Link 2"

...and it would be nice to see them in this order.

I tried to add the line
`'title'   => yourls__( 'Title' ),`
below
```
// Second search control: order by
$_options = array(
    'keyword'      => yourls__( 'Short URL' ),
    'url'          => yourls__( 'URL' ),
```
in the file /includes/functions-html.php ...but that doesn't do the trick :(

**Comment by ozh** [comment]
Indeed, it's not possible out of the box. Someone should make a pull request to add this feature.

**Comment by dgw** [comment]
Why does @majordome only chime in on tickets that are missing the issue template because they're feature requests? (Just kidding, but it's funny to see when it does and doesn't post.)

@ozh I'm going to reopen and assign this to myself. That "someone" might as well be me, and keeping the issue open will keep it on my issue dashboard until I actually make the PR.

**Comment by LeoColomb** [comment]
@dgw Regarding majordome, it's because I host the bot on zeit now, which kill the server after some time of inactivity. The restart is 2 sec too long for GitHub webhooks, then we got request timeouts.
So, depending of the repo activity, it will reply if the server is still active.
I'm considering changing to a new lambda free host, I just need some free time! 😄

**Comment by dgw** [comment]
Yes, that ticket reference means I'm working on an implementation of this. :grin:

PR tomorrow, probably. Barring any explosions once I pull the patch to my server for testing, that is. My PHP is pretty rusty, after all. :smirk:
