### ISSUE TITLE
Stats entries in yourls_log table stopped being added

### ISSUE THREAD

**Issue by triplejay** [YOURLS/YOURLS#2363]
### Technical details regarding my environment

* YOURLS version: 1.7/1.7.2
  * Plugins enabled: Allow Forward Slashes in Short URLs 1.0, Allow Hyphens in Short URLs 1.0, Case Insensitive, ~~iOS URL Schemes 1.3.1 - Deactivated~~
* PHP version: 5.4.17

### Bug description 

**What is the current behavior?**

We've been using Yourls since July 2013. It's been great, thank you!

We haven't made use of the stats for a while and I only now noticed that despite a number of clicks listed on the main admin screen for each short URL when going to the stats screens we see 'No clicks yet. Get some clicks first!'. 

I've checked through the yourls_log table and can see the most recently recorded entry was on 28/7/2016 22:36:06. Going back to those earlier short URLs via the admin interface and I can see those stats are still displaying correctly.

I've checked logs, modified dates on files, and email trails to see if there's anything I did around that time that may have stopped the stats recording but can't find a thing.

I updated from 1.7 to 1.7.2 before submitting this issue but that didn't resolve the problem.

Any suggestions of where I could look to troubleshoot further?

Thanks!

**Comment by ozh** [comment]
Create a new short URL and get some clicks from different IP and different clients : any stats collected?

There isn't any code in YOURLS that make stats act differently based on how old the link is. YOURLS acts very stupidly at this point : [short URL requested = stat recorded](https://github.com/YOURLS/YOURLS/blob/master/yourls-go.php#L19-L29).

If stats aren't populated any longer, it's most probably because...
- there isn't any "new" click on a short URL (with "new" being "new client that hasn't stored the redirection in its cache and then really requests the short URL from YOURLS")
- there is some sort of limit in writing or sizing your log table
- some other MySQL problem
- something else ...
