### ISSUE TITLE
Add underscore to yourls links - avoid adblocker

### ISSUE THREAD

**Issue by jcass1** [YOURLS/YOURLS#2369]
Hi, 

I would just like to know how to add underscore to YOURLS links - i can't  find any information on this but i have done it on an old project. 

I would like to create a link as below example:
examp.le/_test > example.com/offer
examp.le/test > example.com/offer

This is to attempt to get around ad blocker as i use YOURLS for affiliate links. 

Please can someone point me in the right direction?

**Comment by jcass1** [comment]
Template didn't really fir in with the request, saw it as simpler to post as i did

Thanks, 
Jake

**Comment by dgw** [comment]
I don't understand, are you trying to make duplicate shorturls that point to the same long link, or make it so underscores are ignored?

Allowing underscores is simple enough, just take the `hyphens-in-urls` plugin that ships with YOURLS and tweak it to tack on `'_'` instead of `'-'` to the allowed characters. To allow duplicate long URLs, see [this comment](https://github.com/YOURLS/YOURLS/issues/2360#issuecomment-359236902) for a quick and dirty plugin to do so.

Ignoring underscores is similarly possible with a plugin, something involving the `sanitize_string` filter, probably.

**Comment by jcass1** [comment]
Hey there, 

so i have use YOURLS previously where we masked affiliate links with YOURLS, then added a _ after the first /

This then brought up a blank screen saying ' you are being redirected to ....[ original URL] , then the affiliate page would load shortly after
I'm hoping i can replicate this with my new YOURLS account

Let me know if you have an ideas thanks

**Comment by dgw** [comment]
Oh, I see, you want an interstitial. The code for https://github.com/joelgratcyk/yourls-interstitial-plugin ought to get you started, at least. Combined with the code for the Preview URL plugin (https://github.com/YOURLS/YOURLS/wiki/Plugin-=-Preview-URL) you should be able to hack that together.
