### ISSUE TITLE
Add option to stop saving personally identifiable information YOURLS does not need/use

### ISSUE THREAD

**Issue by ian-kelling** [YOURLS/YOURLS#2386]
As far as I can tell by looking in the user interface, as stored in the
db, ip_address, and user_agent are unused and click_time is only used to
the day, but stored is seconds. Without that data, the data stored in
the db is pretty safe to call not personally identifiable, which is what
I want, and seems like a good config option that other users would want.

I know there is an option to not store anything in yourls_log, but the
data that appears to be actually used, like country, and day of click,
is generally not personally identifiable, so I should be able to keep
that data.

Also, after implementing this, a way to remove old data would be good
too.

### Technical details regarding my environment

* YOURLS version: 1.7.2
  * Plugins enabled: none
* PHP version: doesn't matter

### Bug description 

**What is the current behavior?**

see above

**What is the expected or desired behavior?**

see above

### Reproducible bug summary 

see above.

**Comment by ozh** [comment]
The general philosophy of the project is not to add options. Where possible we're more prone to *remove* options, actually, and let users adapt YOURLS behaviour to their liking with plugins.

**Comment by ian-kelling** [comment]
If it's not an option, it should be the default then.  This should
be reopened.

Look at what a, maybe the, most popular free software for traffic
analysis does for ip address privacy: https://matomo.org/docs/privacy/

The current situation is frankly a horrible default for privacy and
should have been made that way in the first place, and it's still worth
correcting.

Afaik, what I've suggested is not possible with the plugin api.

**Comment by LeoColomb** [comment]
With the coming law regarding data collection ([GDPR/RGPD](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation)), I've to admit that YOURLS is not compliant at all out the box. IP collection, location gathering, etc. which are, merged with timestamp data, personally identifiable information.

I remember me suggesting to move location resolution in a plugin, this is a new ***strong*** argument.
Regarding IP, this is more complicated, but yes, it should be dropped or moved to anonymized fingerprints.

**Comment by PopVeKind** [comment]
Just wondering if anyone knows how the big names are handling this?  One big draw of all shorteners is the data collected.  What do Google and Bitly do? Did they stop collecting this kind of data? It seems many YOURLS data collection features are in some way copied from the big boys.

**Comment by ian-kelling** [comment]
@ozh https://github.com/sas101/yourls-pseudonymize is good but it
doesn't do enough. It would need to drop more ipv6 and ipv4 data, reduce
time resolution, get rid of user agent.  But I guess I was wrong about
what is possible with a plugin. Also, the YOURLS plugin list has 0
plugins, and google searches didn't lead me to that plugin. So, I didn't
know about that plugin at all.

Right now for GPDR, my best guess is to turn on the option to not store
anything in yourls_log, archive the YOURLS html pages that show
aggregate analysis, then wipe out yourls_log. Then I will look and wait
for a url shortener which can do more analysis while only storing
aggregate data and not personally identifiable data. It's not something
I have the time to implement myself.

**Comment by ian-kelling** [comment]
*GDPR (i don't use the post edit features because it requires nonfree javascript)

**Comment by ian-kelling** [comment]
Oh, and one of my coworkers pointed out, I was probably wrong about
YOURLS not using ip data. It probably uses it to identify visitors for
deduplication. Is that right? It shouldn't be too hard to just turn that
off and still collect number of visitors per day and the country they
are from.

**Comment by ozh** [comment]
IP of URL submitter is also stored but I think that's out of the scope (if concerned people could just display on their public interface a warning like "if you shorten a URL your IP will be stored and you're OK with this")

**Comment by LeoColomb** [comment]
> if concerned people could just display on their public interface a warning like "if you shorten a URL your IP will be stored and you're OK with this"

Ha ha, good try, but that does not match GDPR rules! 😉 
In all cases, IP storage is avoidable by doing all IP-processing before putting it in the DB, i.e. on the fly.

**Comment by Tekl** [comment]
What about this? https://github.com/fenuz/yourls-anonymize-log

**Comment by dg-wfk** [comment]
@Teki: Thanks, this is a quick hack, which overrides the filter for getting IPs and user agents and makes them return empty strings. Alas, geolocation is not possible any more and so no country code will be stored. But it is in my opinion enough to anonymize YOURLS, since a precise click time is no personal data without IP and/or user agent.

**Comment by dg-wfk** [comment]
Cool, this is perfect. But you don't need to add it to anonymize-log since you override the database insert which actually logs the redirect data and now stores only blank fields except for the time and the keyword. This would also have the advantage of generating and storing the country code.

Additionally, one could make the timestamp more inexact, like the OP suggested.

**Comment by Tekl** [comment]
I added it to the Plug-in because I don't want to alter the core.

**Comment by dg-wfk** [comment]
Of course you should not alter the core. I meant your code is already a complete working plug-in (without meta header), so you don't need to *add* it to anonymize-log, but you can simply *overwrite* it.

**Comment by Tekl** [comment]
But then adding new short URLs would still record IP addresses.

**Comment by dg-wfk** [comment]
Which IP is stored where? Adding a new short URL stores my (admin) IP address, yes. But I don't see where IP addresses by using (old or new) short ULRs are stored. Could you please elaborate?

While typing I've got an idea what you could mean. If you let users add short URLs then their IPs would be logged in the table 'yourls_url'. Therefore, you have to hook additionally to the action "insert_link" (https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L163) an remove the storing of the IP address.

Since I am not letting any users add links I don't need to do this. But for the sake of completeness it should be added to the plug-in, when storing country codes.

**Comment by Tekl** [comment]
That's exactly what I meant. If you are the only one who can add links it doesn't matter for you.
