### ISSUE TITLE
yourls installed in sub-directory - menu not reached

### ISSUE THREAD

**Issue by wci-aw** [YOURLS/YOURLS#2407]
- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [x] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

**Describe the bug**
I have used your instructions to install yourls into sub-folder
https://github.com/YOURLS/YOURLS/wiki/.htaccess
but now having the issue of menu items are not loading while clicking on main menu. They are missing the additional sub-folder structure.

**To Reproduce**
installed yourls
setup subfolder "yourls"
setup htaccess file settings according instructions

````
# BEGIN YOURLS - https://github.com/YOURLS/YOURLS/wiki/.htaccess
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /yourls/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls/yourls-loader.php [L]
</IfModule>
# END YOURLS
````

**Expected behavior**
while clicking in menu item it uses core link destination without sub-folder structure according setup
`mydomain/admin/plugins.php`
instead of subfolder setup mentioned in .htaccess
`mydomain/yourls/admin/plugins.php`

**Screenshots**
> https://www.screencast.com/t/xTwpkdMO

**Environment (please complete the following information):**

    YOURLS version: 1.7.2
        Plugins enabled:
        Allow Hyphens in Short URLs; Fix Long URL; Force Lowercase; Google Analytics; Google Safe Browsing; Popular Links; QR Code Short URLS
    PHP version: 5.6
    Other relevant details depending on the context (
    server version perl 5.16.3, cpanel vers. 72.0 (build 7), appache 2.4.33, Linux
    MySQL version, 5.6.39
    browser version, …)

**Comment by wci-aw** [comment]
Hi dgw,

thanks for respond, but the information you gave still not solved my problem.

The submenu items are not reached by clicking on them as the sub-folder is missing.
Within httaccess the rule is set RewriteBase /yourls/
Still missing the /yourls/ sub-folder in link to click on 
Screenshot > https://www.screencast.com/t/6tOHN8321p

Looking forward to solve this issue too.

Best, Alex

**Comment by dgw** [comment]
You didn't answer my questions at all. What is `YOURLS_SITE` set to in the config?

I haven't used Apache in about five years, so someone else will have to debug your .htaccess, I think.

**Comment by dgw** [comment]
OK, from the .htaccess wiki page:

> **Note:** as stated in various places such as the readme, YOURLS **cannot share** its root directory with another .htaccess rewrite rules driven app such as WordPress. The `.htaccess` file should contain YOURLS directives and no other rewrite rule.

That's problem number one, you're trying to share the same `.htaccess` file between YOURLS and WordPress, which is not supported as @LeoColomb stated a few days ago in #2406.

The other issue is that YOURLS expects `YOURLS_SITE` to be the full path to its installation, not just the protocol and host/domain name. In your case that's `https://2share.info/yourls`, because you've installed YOURLS in the `/yourls` subdirectory. It should work fine if you move YOURLS's section from `public_html/2share.info/wp_yourls/.htaccess` to `public_html/2share.info/wp_yourls/yourls/.htaccess`, though your short URLs will be like `https://2share.info/yourls/keyword`.

If you want short URLs without the subdirectory, I would advise creating a subdomain (e.g. `s.2share.info`) and moving YOURLS to the root of that domain instead.

I will close this because it seems to be a configuration issue, rather than a bug, but feel free to continue the discussion.
