### ISSUE TITLE
Stop redirecting from 404 to /s/

### ISSUE THREAD

**Issue by iGerman00** [YOURLS/YOURLS#2425]
Version: 1.7.2
Plugins:
404-redirect | 1.4
Allow Hyphens in Short URLs | 1.0
Change Password | 1.0
Fix Long URL | 2.0
Sleeky Backend | 2.0

I also have Sleeky frontend installed. It's located at /s/

/s/.htaccess:

```
 # BEGIN YOURLS
 <IfModule mod_rewrite.c>
 RewriteEngine On
 RewriteBase /s/
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^.*$ /yourls-loader.php [L]
 </IfModule>
 # END YOURLS
```

/.htaccess:

```
# BEGIN YOURLS
<IfModule mod_rewrite.c>
 RewriteEngine On
 RewriteBase /s/
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^.*$ /s/yourls-loader.php [L]
 </IfModule>
 # END YOURLS
```

I am really not competent to any of this, i think maybe the problem is in /.htaccess, but if i commment all the yourls lines, my short links stop working. 

The issue is, if i go to website.com/example-nonexistent-page, it instantly forwards me to website.com/s. It doesn't show me the 404 page. And i don't want that.

**Comment by dgw** [comment]
Nonexistent short URL keywords redirect to `YOURLS_SITE`. That's hard-coded in YOURLS, unless a plugin overrides it.

You listed 404-redirect in your plugins, so if it's not working please double-check [the documentation](https://github.com/1Conan/404-redirect-YOURLS/blob/master/README.md) and ask for help from its maintainer if it still doesn't work properly.

Before you head over there, though, I noticed that your `/.htaccess` file references `/s/` in a couple of places, including loading YOURLS through `/s/yourls-loader.php` instead of `/yourls-loader.php`. That doesn't seem right to me (but I haven't done any digging into Sleeky).

**Comment by iGerman00** [comment]
I think you didn't understand me correctly. I'm not talking about nonexistent short URLs, they're absolutely fine and if i go on, say, `website.com/s/nonexistent-url`, it will give me my custom 404 page, because I installed the 404-redirect plugin. **BUT**. If I, say, go to `website.com/nonexistent-nonshort-url`, it will redirect me to `YOURLS_SITE`, and i really do not want that. I want it to redirect me to 404 in both cases, if i go to a nonexistent short url and a nonexistent site url. I hope I made it clear, I am not a native English speaker.

**Comment by dgw** [comment]
You're right, I wasn't clear on what you were asking. But this still sounds like an issue with Sleeky, not YOURLS, and I can't really provide support for a third-party plugin. (But I can try…)

What is the directory structure of this site? YOURLS is installed in `/s/`? What's in `/`, if anything?

**Comment by iGerman00** [comment]
In `/`, there are a a couple of my pages which work fine if i open them:
```
/404/
/site1/
/site2/
/s/
```
in `/s/`:
```
/s/admin
/s/assets
/s/css
/s/images
/s/includes
/s/js
/s/pages
/s/user
/s/.htaccess
/s/CHANGELOG.md
/s/composer.json
/s/config.php
/s/CONTRIBUTING.md
/s/footer.php
/s/header.php
/s/index.php
/s/ISSUE_TEMPLATE.md
/s/LICENSE.md
/s/readme.html
/s/README.md
/s/sample-public-api.txt
/s/sample-public-front-page.txt
/s/sample-remote-api-call.txt
/s/sample-robots.txt
/s/yourls-api.php
/s/yourls-go.php
/s/yourls-infos.php
/s/yourls-loader.php
```
YOURLS was accidentally installed to '/url/', but then i found everything relating to /url and eventually moved it to '/s/'. If i can, maybe i can uninstall and reinstall YOURLS into the correct directory? I doubt it will help, I'm thinking it's it's intended behaviour.

**Comment by dgw** [comment]
So YOURLS is installed in `/s/`, but you are also directing requests that ask for a nonexistent path under `/` to YOURLS' loader? I think I see the issue.

YOURLS does not understand these requests. It looks for `YOURLS_SITE` and removes it from the beginning of the request; if part of the request does not match `YOURLS_SITE` (for example, `https://your.site/not/yourls/`) then it will try to process the whole URI and not find it—which means YOURLS then redirects to its own homepage (`/s/` in your setup).

Your `.htaccess` in `/` probably should not send requests to YOURLS, or if you want YOURLS to handle requests in `/` (the root) you should move it there instead of its current subdirectory. If no other application in `/` requires an `.htaccess` file, YOURLS will work just fine there. Existing static files in `/site1/`, `/site2/`, etc. will still work because YOURLS' redirection only kicks in if the requested URI is not on disk (that's what the lines `RewriteCond %{REQUEST_FILENAME} !-f` and `RewriteCond %{REQUEST_FILENAME} !-d` do).

It's also possible with a plugin to filter the URL before YOURLS processes it (with the `get_request` filter).

**Comment by iGerman00** [comment]
Okay so i *kind of* understood what you meant. And now i tried to comment 
```
# RewriteCond %{REQUEST_FILENAME} !-f
# RewriteCond %{REQUEST_FILENAME} !-d
```
It doesn't change anything. If i set RewriteEngine to Off, it now behaves like i want it to, except short links do not work. I am talking about `/.htaccess` file.

**Comment by dgw** [comment]
Setting `RewriteEngine Off` disables rewriting, as YOURLS is taken out of the loop.

If you want to use short URLs like `http://your.site/keyword` it would be best to put YOURLS in `/`. That said, probably someone who knows Apache can give you an edited .htaccess for that. (I use nginx for my YOURLS and haven't run Apache for anything in almost a decade, so any suggestions I might throw out for making it work with Apache would be untested guesses. :smile_cat:)

**Comment by iGerman00** [comment]
I think i didn't quite explain it good enough. I ***want*** YOURLS to be in `/s/`. I ***want*** nonexistent pages to give me a 404 error. I ***don't*** wan't them to redirect me to /s/, no matter where they are not located, in /, or in /s/

**Comment by iGerman00** [comment]
I don't want my short urls in root, `my.site/keyword` is not what i want. `my.site/s/keyword` ***is*** what i want, though.

**Comment by iGerman00** [comment]
Nope. As you saw in my previous messages, this is my `/.htaccess` contents:
```
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /s/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /s/yourls-loader.php [L]
</IfModule>
# END YOURLS
```
And if i dare touch it, for example, comment a single line, it will all break and short urls will stop working. Maybe somehow it's reading from that .htaccess and not the one in `/s/` directory. Can i change it anywhere in yourls config?

**Comment by dgw** [comment]
My Apache is a bit rusty, as previously mentioned, but I think it should use the closest `.htaccess` to the request URI. So if you ask for `your.site/s/shortword` it should use `/s/.htaccess` and ignore `/.htaccess`…

What happens if you (make a backup copy and) remove `/.htaccess` entirely? You really shouldn't need it at all, assuming that the contents you pasted above are the entire file.

**Comment by iGerman00** [comment]
Those are not the full contents. it also has a 404 page config. I will try though... Nope. Short URLs give me 404 now.

**Comment by dgw** [comment]
I've reached the limit of my Apache knowledge, at this point. I'll leave this ticket open in case another contributor can try to help you, though.

**Comment by LeoColomb** [comment]
> all you need to do is remove the YOURLS lines from `/.htaccess`

Not necessary, in your case we don't care at all of the root `.htaccess`.

---
For the `/s/.htaccess`:
```apacheconf
 # BEGIN YOURLS
 <IfModule mod_rewrite.c>
 RewriteEngine On
 RewriteBase /s/
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^.*$ /s/yourls-loader.php [L]
 </IfModule>
 # END YOURLS
```

Actually cut the `/.htaccess` and paste it to `/s/.htaccess`. This is exactly of the [official documentation](https://github.com/YOURLS/YOURLS/wiki/.htaccess#case-yourls-installed-in-subdirectory) recommends to do.

Let us know if it's working. If not, please provide your Apache version.

**Comment by iGerman00** [comment]
That seems to be working . Somehow I missed it while looking through the official documentation. Thanks to anyone who helped! ~~*i am so incompetent*~~

**Comment by JialuZhang** [comment]
In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
