### ISSUE TITLE
Per-country redirect URL (using nginx built-in GeoIP)

### ISSUE THREAD

**Issue by tobozo** [YOURLS/YOURLS#2426]
Hello and thanks for this great project!

I currently have a long URL supporting geo-redirections with some basic rules like:
- if the country of the visitor is 'GB', redirect to the *.co.uk* URL
- if the country of the visitor is 'FR', redirect to the *.fr* URL
- if no previous rules are met, redirect to the *.com* URL

I've shortened the URL to that page, but the result is chaining redirections and it isn't that good.
Also maintaining the Geo redirection rules in one place and the short URL in another doesn't feel right.

What I want is get rid of this extra redirection while keeping maintanability of the default and geo-urls in the same place.

Adding an extra field to store per-entry geo rules or reference the keyword field in a foreign table seems too invasive, so I guess a plugin is the way to go.

What would be the best approach to achieve that?

**Comment by ozh** [comment]
Simple easy thing that comes right off my head:

- create shorturl "abc-uk" that points to "longurl.co.uk/something"
- create shorturl "abc-fr" that points to "longueurl.fr/lachose"
- create shorturl "abc" that points to "longurl.com/default"
- have a plugin that checks shorturl and country prior to redirection, if the request is for "abc" and an "abc-[country]" exists and the location seems to be that [country], redirect to "abc-[country]", otherwise redirect to "abc" as requested
- the plugin can also ease the process of creating multiple regional short urls, with a form where you input short URL and different long URLs

Simple, easily scalable, future proof, and should you delete any country specific short URL everything will still work.

**Comment by tobozo** [comment]
currently testing this in yourls-go.php, I'm not using the built-in GeoIP as this instance is behind a reverse-proxy that already injects the country code of the visitor (had to use the 302-instead plugin too):

```

// commented this one out
$url = yourls_get_keyword_longurl( $keyword );

// added this
$GeoKeyword = $keyword .'-'. strtolower($_SERVER['HTTP_X_GEOIP_COUNTRY_CODE']);
$GeoLongURL = yourls_get_keyword_longurl( $GeoKeyword );

if(!empty($GeoLongURL)) {
  $url = $GeoLongURL;
} else {
  $url = yourls_get_keyword_longurl( $keyword );
}
```

Next steps should be to set this as a plugin using the 'pre_redirect' action but it's already declared by the 302-instead plugin, not sure where to go from there.

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core

I think it would be easier that instead of using the `pre_redirect` **action**, you'd use a **filter**. For instance [`get_request`](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L1981) that is called from [very early in the flow](https://github.com/YOURLS/YOURLS/blob/master/yourls-loader.php#L21). See bullet point number 4 of my reply above, this describes how a filter would change a value and return it. See the wiki about actions and filters, also.

**Comment by tobozo** [comment]
duly noted, thanks for the hints, I've created a repo for the plugin:

https://github.com/tobozo/YOURLS-GeoShortURL

I'll need more time to figure out how to integrate the short-url creation and editing processes.

**Comment by tobozo** [comment]
Spotted a problem where I can't display the default Geoized short-url statistics, will investigate, but I'm quite sure the pre_redirect filter interfers when trying to access the stats, will investigate.
