### ISSUE TITLE
Is it possible to pull data from YOURLS and show it in a client dashboard?

### ISSUE THREAD

**Issue by punctulica** [YOURLS/YOURLS#2451]
I'd like to create a dashboard for clients to see their clicks without having them to log into YOURLS so that everything is easy to read for a non-tech person. 

I looked at the YOURLS API but it doesn't say anywhere that something like this can be done.

So, I'm asking here: is it possible to pull data from YOURLS and show it in a easy to read client dashboard?

**Comment by Zimbu98** [comment]
Create user names and passwords for them to log into YOURLS with a lower permission level than admin; that way, they can't screw with other data; they can only see their click data.

-I know that you mentioned that you would prefer users to **not** have to log into YOURLS, but I think that might be a bit too open and too risky. In addition, even non-tech people know how to log into a simple website, is I think requiring a login would not be a big barrier.
-You would need to add the [YOURLS AuthMgrPlus plugin](https://github.com/joshp23/YOURLS-AuthMgrPlus), to limit people to only seeing their own data. Again, this is the reason you must have a login, otherwise you have no idea who is viewing the data.

The other way to do it would be with custom php files running on your regular website (not within YOURLS). This is what I did for my purposes, but it is quite complicated.

**Comment by ozh** [comment]
"is it possible to pull data from YOURLS and show it in a easy to read client dashboard" : yes. Use the API, and add custom plugins so that the API produces just what you need. Example: https://github.com/YOURLS/API-action
