### ISSUE TITLE
Install docs are dated - any chance of an update?

### ISSUE THREAD

**Issue by dylanh724** [YOURLS/YOURLS#2464]
The guides (nginx setup) were meant for Ubuntu 14 many years ago -- Following the guide now, I can't seem to get it to work (I had it working years ago when the guide was new: It seems like the guide is finally dated).

An updated guide would rock.

**EDIT: Got it working, but only after several hours of _external_ (Google) sites rather than the install guide.**

**Comment by LeoColomb** [comment]
Thanks for your report @dylanh724!

There isn't any official guide how to install on a specific operating system. 🤔  
I'm not sure but I think you used the link "How to Install YOURLS on Ubuntu 14.04" in the "list of some (unofficial) install guides" on the `readme.html`.
As described, it is non-official and do not take preference over official docs like the [wiki](https://github.com/YOURLS/YOURLS/wiki).

> An updated guide would rock.

That said I agree, this readme can definitely be rewritten to refer to more updated ressources. 👍 
If you've succeeded to get it working after some hard work, would you document your way and suggest your own guide there? Thx!

**Comment by dylanh724** [comment]
Actually, your wiki guide is just fine in my nginx setup:

https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration

That wiki is actually awesome and up to date, but down low and Google and no where on that install page -- The wiki link belongs front+center of that /install page! Honestly, that would do just fine. You can keep those old guides, but preferably tag them "possibly outdated" below the wiki

**Comment by LeoColomb** [comment]
@dylanh724 OK, thanks a lot for your feedback, appreciated.

We are definitely opened for a PR to reflect your awesome suggestions! 👍

**Comment by LeoColomb** [comment]
> I had to restore a backup and now I'm back to 403 forbidden

@dylanh724 That's totally unrelated to this issue! 😉 

> what should the main chmod -R be? And I heard /admin should have a different one?

??
As any other php app, all files should be available for reads and writes for the same user used by the web server (and the PHP interpreter) (often www-data).

**Comment by PopVeKind** [comment]
**Does anyone use EasyEngine with their YOURLS?**

I don't know if it will help you, but I just moved my YOURLS sites from pair.com (Ubuntu, Apache, MySQL) to linode.com (Debian, Nginx, MariaDB).  I just started a Debian 8 image, then EasyEngine, then YOURLS.  EasyEngine did most of the work for me (pretty much copy/paste two lines!).  I then added only two lines of configuration and it worked fine! Thank You EasyEngine!

@dylanh724 The EasyEngine route to install YOURLS would allow EasyEngine to maintain the underlying packages of YOURLS.

I think we should make YOURLS easier for noobs to load and maintain so that someone with no PHP experience can quickly get a site running perfectly and can easily maintain it with simple copy/paste skills.

If anyone woud like it, I can write _a simple noob guide to installing YOURLS via EasyEngine!_ There are other VPS that this should work on besides Linode, such as Digital Ocean, I just prefer Linode, and have not tested the others.
