### ISSUE TITLE
How to harden private YOURLS install for maximum OPSEC and avoid getting hacked

### ISSUE THREAD

**Issue by crazimoskito** [YOURLS/YOURLS#2482]
Hello,

We've recently had our YOURLS installation hacked and the _ez_sql_core_yourls.php_ injected with your typical, highly obfuscated Webconsole malware plus malicious .ico and index.php files which proliferated into all YOURLS directories (incl. css and javascript folders). Note that this was on a server that does not run anything else, so we're still rather unclear about the exact attack vector at this time but suspect either a POST attack or SQL injection of some way or another.

However, the purpose of my post here is to get advice **on how to harden a new private YOURLS installation** (where only admin users can create new links and only these links are given out to the public), to not run into any chance of it getting hacked again, **i.e. preventative measures and good maximum OPSEC** especially on your run-of-the-mill shared hosting server where you can't do much in the way of Web Application Firewalls and such things.

1. Which permissions (chmod) should the files and directories have (lowest possible)? Are there any files which need special permissions and are there files which I can chmod 000 if I don't use them in a scenario like the one mentioned above (where admin users create links via the webinterface and guests only click on links and never interact with YOURLS directly)?

2. How can I **protect the admin area and all other folders with htaccess basic authentication**? Except for the scripts that are required to expand the links to anyone accessing them on the web (which scripts are these?). (Unfortunately, limiting access to a certain IP address range via a htaccess file in all folders is not an option due to several admins with dynamic IPs and htaccess protection only the admin folder may not make a big difference, as it still leaves the SQL scripts and other parts potentially open to exploitation).

If /css, /images, /user, some from /includes and all other directories only needed for the admin console were actually sub-directories of /admin, it would be much easier to htaccess-protect the admin console (or admin directory). However, I now can't put htaccess basic auth files in all of these folders or I will face three, four identical password prompts when trying to open my-yourls.xy/admin

Do you have any recommendations to this effect, i.e. how to properly harden admin console access so that at most one htaccess basic auth prompt is required (which is an inconvenience for admin users, as they still would have to login a second time in the actual admin console, but better than 4 prompts - or none, I guess).

3. Is there any definitive way to **protect YOURLS (files, scripts, folders)** against malicious SQL injections, directory traversal, malicious HTTP POST requests and other potential attacks on the parts that are always necessarily public-facing (the loader etc.)?

4. Is it theoretically possible to **hand over malicious commands to YOURLS** through invalid shortened links, i.e. (simplified example, something like):
`https://my-yourls.xy/linkthatdoesntexist<?php>badcode...`
or has this been fuzzed and are all such inputs correctly sanitized?
I suppose if that were the case, it would be impossible / irresponsible to run YOURLS on any publicly accessible webserver...

5. Last but not least, some security by obscurity might be good but I know from reading various requests to that effect, that **changing the admin login path and renaming all files, directories and variables** in order to obscure what's actually running and hamper automatic scripts scraping for certain vulnerabilities etc. is not an option. However I just want to add my +1 in the hope that this might be possible with a **"white-label" plugin** that just totally obscures everything in the code at some point in the future (like they exist for e.g. Wordpress).

### Technical details regarding my environment

(general questions, apply to latest version of YOURLS, private setup, running on any shared hoster with Apache/MySQL)

Sorry for the long post but it reflects some of my thoughts on security of YOURLS and I hope to get some guidance on which steps to take on a new, clean install now to ensure that YOURLS can't be compromised again even if it has possible vulnerabilities.

Thank you!

**Comment by ozh** [comment]
Hello there

At this point, fingers crossed but we're rather confident there is no SQL injection possible in YOURLS, assuming you're running the latest version available. We're confident because various and independent security consultants or auditors regularly send us security audits and reports, and SQL or other injections are something we covered from the ground up with serious coding best practices a couple years ago (in other words, every input and means of submitting it is considered potentially unsafe and sanitized the hard way)

Vector attacks on shared hosting can be pretty anything, and the infected filename doesn't reflect its vulnerability (I changed this issue title to reflect this and help others searching on the same subject)

**Wiki page https://github.com/YOURLS/YOURLS/wiki/Spam has several very important things to read**. There are also a couple plugins dealing with alternate ways of authentication, check https://github.com/YOURLS/awesome-yourls

Regarding chmod and protecting directories with another password, https://codex.wordpress.org/Hardening_WordPress#Hardening_Recommendations is also a very good read, but things may depend on how your webhost configures stuff and segregate users.

Don't overlook YOURLS plugins, most are very basic and exploit free but if you don't need one, get rid of it.

I hope that will help, feel free to comment further on as needed
