### ISSUE TITLE
Plugins :Allow Hyphens in Short URLs， Does not work

### ISSUE THREAD

**Issue by zhoumin** [YOURLS/YOURLS#2515]
Hi,
After opening Allow Hyphens in Short URLs, open a short URL with a forward slash and a 404 error will occur.
Thank you!
![js-w](https://user-images.githubusercontent.com/2437974/54123815-ad22a980-443b-11e9-952e-6770336a63d4.png)
![404](https://user-images.githubusercontent.com/2437974/54123980-17d3e500-443c-11e9-934c-79f0108e3e2c.png)

- YOURLS version: v1.7.3
- Plugins enabled: Allow Hyphens in Short URLs、Mass Remove Links、QR Code Short URLS、Random Keywords
- PHP version: PHP-7.0
- MySQL version: 5.7

**Comment by ozh** [comment]
I'm pretty confident that after all these years and all the dozens of thousands YOURLS installs running this plugin, it actually works. (I'm assuming that instead of "open a short URL with a forward slash" you meant "with a hyphen")

If you can reproduce the problem, something else is at cause here, and you'll probably have to pin point the problem with various tests. The server error log might help. Feel free to comment on with more reports so maybe we'll be able to help

**Comment by zhoumin** [comment]
The above may be incorrectly described. I enabled the plugin "Allow Hyphens in Short URLs". The short link contains a hyphen. Opening it will cause a 404 error. I tested it on another server, and the same phenomenon. Can you tell me how to deal with it, I need your assistance very much, thank you!

**Comment by ozh** [comment]
See http://ozh.in/i-think-it-works and then my previous answer
