### ISSUE TITLE
Chaturbate URLs don't send back a title when shortened, and behave funkily

### ISSUE THREAD

**Issue by moonsbtt** [YOURLS/YOURLS#2529]
I  build a private url shorten service for myself with the newest code~~
everything works great but today I have a problem with a long URL:

https:// xxxx.com  /in/?track=default&tour=LQps&campaign=GfeR8&room=testaff
The xxx should be  "chaturbate" (it's an xcam affiliate link)

Here is a very strange thing:

1:  It don't work this this "chaturbate" domain
It do generate a short url but  the long url of this generated short url will be blank. Sorry for my English, hope you can understand!

2:  If change the the domain to others, such as Google or Youtube or something else, it works!
I have tested with some random words, and it works!

**Comment by ozh** [comment]
I think that's because the page sends an [X-XSS-Protection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) header that prevents from accessing the URL from a shortener (that's mostly useless and dumb). Or maybe it's another header they send/

Interestingly, the shortened URL behaves funnily: works for me if I click it with left button but not if I mid-click it to another tab: http://yourls.org/e8. This behavior seems to be browser dependant.

Anyway, I don't know. Leaving this open if anyone wants to dig in.

**Comment by LeoColomb** [comment]
> Interestingly, the shortened URL behaves funnily: works for me if I click it with left button but not if I mid-click it to another tab: http://yourls.org/e8. This behavior seems to be browser dependant.

This is a common behavior for ad blockers. They prevent accessing some domains when opened in a new tab (i.e. not a direct access).

Ad blockers may be the "issue" for the whole report. Can you check @moonsbtt?

**Comment by ncaos** [comment]
I use uMatrix, which only blocks all external JavaScript by default, and your URL works as it should @ozh. @LeoColomb is correct and you should close the ticket since @moonsbtt never replied anyway.

**Comment by LeoColomb** [comment]
Thanks a lot for your review @ncaos, really appreciated! 👍 

Indeed, let's close this ticket.
