### ISSUE TITLE
nginx configuration about 403 forbidden

### ISSUE THREAD

**Issue by IcedOtaku** [YOURLS/YOURLS#2549]
[https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration](url)
i followed this nginx configuration and i get 403 forbidden
here is the solution:
replace 
try_files $uri $uri/ /yourls-loader.php$is_args$args;
by
index /yourls-loader.php;
bingo!

**Comment by dgw** [comment]
I have `try_files $uri $uri/ /yourls-loader.php;` in my config and it works fine.

**Comment by IcedOtaku** [comment]
thanks i got another issue about redirecting
can u help me
already report in another issue

**Comment by axelsimon** [comment]
Not sure why this issue is closed. This is something that's not properly explained in the docs i think.
From what i understand, the default nginx confi *intends* to return 403 forbidden on the base domain used for YOURLS.

This is the idea:
https://yourls.yourdomain.net/ --> 403
https://yourls.yourdomain.net/short-url --> 301 --> redirect to short link target

If you want to have YOURLS return someting on the base domain (https://yourls.yourdomain.net) then you should "install a public interface in the root directory", cf. https://github.com/YOURLS/YOURLS/wiki/Private-Or-Public.

**Comment by LeoColomb** [comment]
> Not sure why this issue is closed.

The reporter has closed the issue himself, mostly meaning the issue is resolved on their side. 

> This is the idea:

Exactly! This is the expected behavior. 🙂

**Comment by axelsimon** [comment]
Could we please then improve the wiki, i'm thinking especially of the [Nginx config page](https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration), which should say the following (feel free to copy and paste):

> - Note: By design, this configuration will throw an error 403 "forbidden" your YOURLS `server_name` domain: it will not answer with an index file on the bare domain, nor on any lower directory (such as `/admin`, unless you manually specify `/admin/index.php` (such as `https://your.yourlsdomain.tld/admin/index.php`).
> - If you'd like to have YOURLS answer on your bare domain, you likely want to have a look at the [Private or Public page](https://github.com/YOURLS/YOURLS/wiki/Private-Or-Public).

**Comment by ozh** [comment]
Thanks @axelsimon, I've updated the docs as you recommend
