### ISSUE TITLE
Wrong docs regarding JSONP callback parameter

### ISSUE THREAD

**Issue by jesobreira** [YOURLS/YOURLS#2566]
Sorry for removing the bug report template, but I believe this is too simple.

The [docs](https://api.yourls.org/doc) state that, for using JSONP, it's needed to add a "jsonp" parameter with the callback function name.

> **JSONP support:** add a JSONP callback with a `jsonp` parameter (eg query string `?jsonp=my_callback`)

However the [source code](https://github.com/YOURLS/YOURLS/blob/master/yourls-api.php#L45) looks for a variable named `callback` instead.

```php
if( isset( $_REQUEST['callback'] ) )
	$return['callback'] = $_REQUEST['callback'];
```

Indeed, requests that follow the docs (with `?jsonp=`) do not work (the response comes without the callback name), whereas if we use `?callback=` instead, it works.

**Comment by dgw** [comment]
Assuming the others agree that `callback` is a fine name for the parameter (I think it is better than `jsonp`), this would make a great Hacktoberfest issue for someone wanting to get involved in the YOURLS project! Possibly you, if you're interested. :smile_cat:

**Comment by LeoColomb** [comment]
LGTM
Great suggestion for the Hacktoberfest! 👍

**Comment by bluemorbo** [comment]
This might like sound a daft question to a GitHub newbie, but where do the docs live? I can't find a reference to the code in this repo. Thanks in advance :smile:

**Comment by ozh** [comment]
Hold on, might not be just this. We have a `jsonp` callback param [here](https://github.com/YOURLS/YOURLS/blob/master/admin/index.php#L183-L184) when used with a bookmarklet.

Maybe it's a case of consistency between API and bookmarklet

**Comment by ozh** [comment]
@bluemorbo in the wiki for some more advanced stuff, yourls.org for the basics

**Comment by bluemorbo** [comment]
Since it appears it's more likely an inconsistency between `jsonp` and `callback`, we've a few different options:

1. Update docs to reflect the inconsistency
2. Add support for both parameters to the API so the docs are correct while still remaining backwards compatible
3. Update API to only reference a jsonp parameter, with the understanding that existing uses of the JSON-P functionality would break.

I'm inclined to 2 myself, but happy to implement whichever changes are preferred. Let me know :)

**Comment by ozh** [comment]
Same for me, option 2
