### ISSUE TITLE
Stats page has link to admin interface, which works even when not being logged in

### ISSUE THREAD

**Issue by ytlevine** [YOURLS/YOURLS#2600]
When clicking the "Admin interface" link on a stats page (link with the + sign at the end), the user will be logged in to the admin interface directly, even if they weren't logged in previously.
Not sure when this started being an issue, but I just updated to 1.7.6 today, and noticed it.
I have YOURLS_PRIVATE set to true and YOURLS_PRIVATE_INFOS set to false.

Thanks!

**Comment by dgw** [comment]
Are you sure it's not a password manager (built into your browser or otherwise) immediately filling in the login form? A quick glance at the revision history didn't reveal any changes to files that obviously affect authentication behavior.

My personal instance isn't quite up to 1.7.6 yet, and I don't have a moment right now to set up a test one, but I find it hard to believe that YOURLS would suddenly allow access to the admin area without actually logging in first.

**Comment by ytlevine** [comment]
I just switched the YOURLS_SITE parameter to use https, and updated to 1.7.6, but otherwise didn't change anything.
Just tested again in a Firefox private window (I normally use Chrome, and tested there first), and it's doing the same thing.
Might be something with my config, but I don't think I have anything unusual running...

**Comment by dgw** [comment]
Right then, I found a moment to set up YOURLS 1.7.6 in XAMPP over lunch. With the same privacy settings you specified (`YOURLS_PRIVATE` true, `YOURLS_PRIVATE_INFOS` false), I can't reproduce this behavior. Visiting stats for one of the default short links, `http://localhost/ozh+`, I am prompted to log in as expected after clicking the "Admin interface" link in the page header.

Of course my test install has no plugins enabled, no CDN in front of it, and no configuration other than the default `.htaccess` that ships with YOURLS. I'm afraid you'll need to dig deeper into your configuration and environment to figure out what's happening! 🙏

**Comment by ytlevine** [comment]
Thanks!

Was going to try to setup a test installation, thanks for finding the time to do that.

Just went through my plugins, and I see that there was an update for the AuthMgrPlus plugin (https://github.com/joshp23/YOURLS-AuthMgrPlus) that I was using, with a few mentions of permission fixes, and now I think it might be working correctly, and prompts me to log in, so that might have been the plugin, instead of any other changes - going to test further, but I'm probably fine - thanks for all your help, and for pointing me in the right direction, and sorry for opening the issue when I should have checked my setup more closely first!

**Comment by dgw** [comment]
Oh there's [a commit](https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/1a1886483034f1a3d0eaa08dafaeef7fe7f47f40) to that plugin from November 2019 mentioning INFOS specifically. Maybe… 🤔

If you don't mind, I'll close this out as "invalid" (just means it isn't YOURLS' fault, not that the issue is wrong) but you can still keep us updated. 😸

**Comment by ytlevine** [comment]
Yep, should have closed it myself...

Thanks a lot!
