### ISSUE TITLE
yourls

### ISSUE THREAD

**Issue by FreelanceGeek** [YOURLS/YOURLS#2712]
I am wondering if it is/will be possible to change the generated preview of a yourls link in iMessage?

Along these lines: https://developer.apple.com/library/archive/technotes/tn2444/_index.html

At present it appears to show the site Favicon. 

Love yourls btw - thank you!

**Comment by ozh** [comment]
Don't know iMessage but if anything the preview of a YOURLS link in any tool should be the preview of the end URL. Tool generating previews should follow links, unless you have a plugin telling it to do otherwise.

All in all, yes, it is certainly possible to do what you're seeking: see https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
