### ISSUE TITLE
cURL error 6 after LDAP plugin activation

### ISSUE THREAD

**Issue by Adriviere** [YOURLS/YOURLS#2735]
Hi,

I'm trying to use the ldap plugin but after its activation, I can't use LDAP authentication.
So I enabled YOURLS_DEBUG (in /user/config.php) and i saw this on the login page :

Connected to database yourls on localhost 
SQL: SELECT option_name, option_value FROM yourls_options WHERE 1=1 (0.00059 s)
cURL error 6: Could not resolve host: api.yourls.org (POST on https://api.yourls.org/core/version/1.0/)
SQL: UPDATE yourls_options SET option_value = 'O:8:"stdClass":4:{s:15:"failed_attempts";i:104;s:12:"last_attempt";i:1596462082;s:11:"last_result";s:0:"";s:15:"version_checked";s:6:"1.7.10";}' WHERE option_name = 'core_version_checks' (0.00545 s)
Check for new version: no

First, I would like to solve the cURL error 6. I think I should add api.yourls.org in /etc/hosts but I can't find the IP address of this site.
I use a proxy but it's correctly registered in my system.
Can someone help me please? :)

**Comment by dgw** [comment]
By "ldap plugin" I assume you mean [this one named "LDAP"](https://github.com/k3a/yourls-ldap-plugin) (and linked from [our "Awesome list"](https://github.com/YOURLS/awesome-yourls)). LDAP functionality is not maintained by the YOURLS team, and we must ask you to seek help with it from that plugin's developer(s).

Inability to resolve the `api.yourls.org` hostname also sounds like a problem caused by something outside YOURLS' control. 🙁

**Comment by Adriviere** [comment]
Alright. I'll ask some help to the plugin's developer.

Thank you!
