### ISSUE TITLE
Need info to update 302 plugin

### ISSUE THREAD

**Issue by tinjaw** [YOURLS/YOURLS#2742]
You all have recommended the 302 plugin several times

https://github.com/EpicPilgrim/302-instead/blob/master/plugin.php

However, it doesn't seem to work. What do I need to update to get it to work with the latest version? I will update and post PR.

**Comment by dgw** [comment]
"it doesn't seem to work" is very vague. Is there an error? Does it just get ignored (and links redirect with default status 301)?

You can see the relevant action and filters here: https://github.com/YOURLS/YOURLS/blob/c1517f1f84baf55e76db0f97814ceb49ffd34bfa/includes/functions.php#L232-L234

In modern YOURLS it's probably better to filter the `redirect_code` than for the plugin to redirect itself. That would be a good PR for you to make! (I'm not involved with that plugin's maintenance, of course. This is just my opinion. :)

**Comment by tinjaw** [comment]
> Does it just get ignored (and links redirect with default status 301)

Yes.

I'm new to the codebase, but I will try. What RTFM material should I look to for help?

**Comment by tinjaw** [comment]
Found https://github.com/YOURLS/YOURLS/wiki/How-to-make-Plugins

I'll take a stab at it.

**Comment by dgw** [comment]
Start by reading the Actions and Filters sections in [our wiki page for developers](https://github.com/YOURLS/YOURLS/wiki/How-to-make-Plugins#actions). There's actually example code there that relates to custom redirect status codes.

There might also be some configuration detail of your setup that prevents YOURLS from altering the default status because the headers get sent too soon (i.e. output buffering is turned off in PHP), but I haven't dug into that yet.

**Comment by tinjaw** [comment]
This is what I have come up with but it doesn't work. How can I debug?

Thanks.

https://gist.github.com/tinjaw/74168463984fc713c7440b45aa31cbe0

**Comment by tinjaw** [comment]
BTW FYI, the main purpose of my YOURLS site is to allow downloading the latest version of a file using the same URL.

**Comment by dgw** [comment]
Ah, hmm. I think the `redirect_code` filter expects just the code to be returned by filters; the `$location` (`$args[1]`) is provided only for context. Your gist tries to return multiple values.

Changing the redirect location is its own filter, `redirect_location`, which receives the `$code` as context despite no filters being able to alter the code yet. (Wait a sec… @ozh, is that really useful? 😹)

**Comment by tinjaw** [comment]
I updated the gist, but it still doesn't work

**Comment by dgw** [comment]
The function must either accept both arguments, or register using the `accepted_args` argument to `yourls_add_filter()` to specify how many of the filter's arguments it expects. Try:

```php
function 302_redirection( $code, $location ) {
    return 302;
}
```

(All of this is kind of guesswork on my part because I haven't worked with YOURLS plugins in a while, and can't currently try stuff myself to see what works.)

**Comment by dgw** [comment]
Also, PHP identifiers can't start with a digit. Try naming the filter `tinjaw_302_redirection` instead.

**Comment by tinjaw** [comment]
Updated gist. Still not working.

Am I correct in assuming the PHP file gets parsed every use? Or do I need to do something to force a "refresh"? This particular instance is on a hosting provider.

**Comment by dgw** [comment]
The PHP file should, yes. But assuming the code works now, if your browser or any caching/CDN layer in between YOURLS and your client has fetched a 301 link once, when the plugin wasn't working, it probably won't ever go back to the origin server during testing. One must jump through some hoops to disable all caching, or test each iteration with a different shortlink name to bypass any cached redirects.

**Comment by tinjaw** [comment]
I have been testing unused URLs. And I can create a new one for testing. I will now, but I don't think things are working properly.

**Comment by tinjaw** [comment]
Just created a new link and I get 301.

Sorry, I really didn't think this would take up much of your time. I appoligize.

**Comment by dgw** [comment]
Since we've reached the point of checking _everything_ just in case: You've made sure to activate this plugin from `<your_domain>/admin/plugins.php`, right?

And it's still possible that your server or PHP configuration is sending the headers before this filter gets a chance to run, meaning the status code can't be overridden in time. Check PHP's output buffering settings, for a start.

**Comment by tinjaw** [comment]
> Since we've reached the point of checking _everything_ just in case: You've made sure to activate this plugin from `<your_domain>/admin/plugins.php`, right?

That was it !!! Doh! Thankfully it was just that simple.

OK, thank you so much for your help. I will make this all look nice and pretty and ready for primetime and then I will formally announce it as publicly available. And you can start sending people to my plugin if they want 302.

If I find the time, I will add some logic for choosing between 301 and 302.

Thank you so much.

**Comment by ozh** [comment]
@dgw is such a support champ :)

**Comment by tinjaw** [comment]
Now public as a Gist.

https://gist.github.com/tinjaw/5da8ef61d91b73ca928256bb51200117

Please link to it if you feel it is worthy.

Thanks again for your help @dgw & @ozh

**Comment by dgw** [comment]
@tinjaw Proposed: YOURLS/awesome-yourls#70 😸
