### ISSUE TITLE
Long URL not taking ?

### ISSUE THREAD

**Issue by fbcwebdev** [YOURLS/YOURLS#2746]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

System will not take a ? at the end of the URL.  It acts like it will take it but it strips off the ? Gives an error "Error updating http://192.168.64.2:1000/portal (Short URL: logon)"

The Proper link should be http://192.168.64.2:1000/portal?

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. Go to /admin
2. Make new short url /logon for long url http://192.168.64.2:1000/portal?
3. System saves everything except the ? at the end.

**Expected behavior**

I made one of these a couple years ago that actually is correct!

**Actual behavior**
What actually happens.

The ? is gone!

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.

Powered by YOURLS v 1.7.9 

Also, please include:
* The OS and what version of the OS you're running. - MAC OS 10.14.6
* Plugins or extensions activated if applicable. - None activated

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ozh** [comment]
When submitted, URLs are first sanitized to make sure they are properly formed. We have a quite extensive [test collection](https://github.com/YOURLS/YOURLS/blob/master/tests/tests/format/urls.php) to make sure YOURLS works fine with all kind of legit URLs

In your case of an empty query string, the trailing `?` is indeed stripped. Not sure this is a real problem though because that is the same URL anyway? Or do you have a different use case ?

**Comment by ozh** [comment]
No feedback, closing. Feel free to comment on.
