### ISSUE TITLE
Unable to Include Hashtag in Facebook Link when using YOURLS

### ISSUE THREAD

**Issue by stoneric** [YOURLS/YOURLS#2750]
**Describe the bug**
Short description of Feature or Problem:
Unable to Include Hashtag in Facebook Link when using YOURLS

**To Reproduce**
To include a hashtag in a Facebook link, the link must include
"&hashtag=%23Text" for the hashtag to work.  Even if you encode, double encode, or triple encode the hashtag sign (i.e. "&hashtag=%2523Text"), the result is the same.

**Expected behavior**
Include working hashtag no matter what 

**Actual behavior**
When using a YOURL in a webhook to create the link, the link generated by the YOURL includes "&hashtag=#Text" which doesn't work.

**Screenshots**
N/A

**Versions**
1.7.9
Ubuntu 18.04
Nginx

**Comment by ozh** [comment]
Your using the template indicates, amongst other things, that you are referring to using latest release as opposed to current master.

Hence my answer: this is fixed in the next release (no ETA), see example link http://yourls.org/el 

![image](https://user-images.githubusercontent.com/223647/93521602-98787900-f930-11ea-8a19-9a4f0c70f725.png)

By the way, this issue has tons of duplicates, that you can easily find when searching in past issues because there is a pinned issue about this
![image](https://user-images.githubusercontent.com/223647/93521867-edb48a80-f930-11ea-9009-89a40d0335b6.png)
