### ISSUE TITLE
Instead of 404 redirect to company home page

### ISSUE THREAD

**Issue by hemangajmera** [YOURLS/YOURLS#2818]
For home page and other urls which are not configured, it will be good if all those can be redirect to default website. Let me know if you need more information.

**Comment by dgw** [comment]
This is so simple, it doesn't even require a plugin. I'm fact, it's so simple I had to do a `find ... -exec grep ...` on my server to find why it works, because it doesn't even require editing the YOURLS config file. 😂

Create `index.php` at the root of your YOURLS install with this content:

```php
<?php
// redirect to the main site
header('HTTP/1.1 302 Found');
header('Location: https://yourmain.site/');
```

Of course replace the Location with your main site URL.

If it doesn't work, make sure your web server is configured to look for `index.php` (it might only look for `index.html` or `index.htm` by default).

This works because the 404 you see isn't from YOURLS itself, but from your web server. If the link keyword YOURLS gets doesn't exist, it just redirects the user to the `$YOURLS_SITE` set in `config.php`, which doesn't exist unless you add an index page or reconfigure the web server to treat something else as one.

**Comment by bertrell** [comment]
Just wanted to add that in my installation, the root directory already
contains an index.php file.  I don't remember if I put it there, or not,
but it looks like this:

<?php
include_once('admin/index.php')
?>

That's still safe to have, I'm hoping.

If I didn't have a forward already in place, the code you showed would
probably have been a good alternative.

Thanks for the info.

**Comment by ozh** [comment]
Use a plugin, see https://github.com/YOURLS/awesome-yourls
