### ISSUE TITLE
App doesn't behave properly when deleting a link.

### ISSUE THREAD

**Issue by pblanton** [YOURLS/YOURLS#2959]
* [X] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [X] This request isn't a duplicate of an existing issue, opened or closed
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Describe the bug**
When I delete a URL, the page clears and shows {'success':1}. When I press the back button to go back to the admin page, I have to manually refresh it to get the URl entry tom show that it's been deleted.

**To Reproduce**
On the admin page, click the trashcan in the right column to delete a URL. 

**Expected behavior**
The URL should be deleted from the database and you should be redirected back to the admin page with the newly refreshed grid without the just deleted URL.

**Actual behavior**
After you click the trashcan, you are shown a blank page that says "{'success':1}"

**Versions**
1.8.1

**Comment by dgw** [comment]
If your browser is navigating to the ajax result JSON, that sounds like a server configuration problem. The link's click handler isn't being set properly, or the browser's default behavior is otherwise not being overridden as expected. Please check your browser's console and server logs for errors, especially 4xx or 5xx responses for files ending in `.js`.

----

I'll include some background you might find useful (as I did when investigating what _should_ happen).

You can see the JavaScript responsible for handling this action here:

https://github.com/YOURLS/YOURLS/blob/23d21fd996e771c4015f5d8b4ec1b06af122d60b/js/insert.js#L90-L120

The ajax request is handled on the backend by this block:

https://github.com/YOURLS/YOURLS/blob/23d21fd996e771c4015f5d8b4ec1b06af122d60b/admin/admin-ajax.php#L36-L40

**Comment by ozh** [comment]
> After you click the trashcan, you are shown a blank page that says "{'success':1}"

What is the URL of that blank page ? "you are shown" is vague.

Adding or editing links works?

YOURLS uses the [same ajax](https://github.com/YOURLS/YOURLS/blob/23d21fd996e771c4015f5d8b4ec1b06af122d60b/admin/admin-ajax.php) for adding, editing or deleting links. It doesn't make sense why the browser would be ok with `{"url":{...},"status":"success","message":"Link updated in database"}` and trip over `{"success":1}`

**Comment by pblanton** [comment]
Sorry for being vague. I have figured it out. 

When I saw dgw's comment, I tried to do some debugging from my laptop (which is a different machine than I had originally experienced my problem) and it worked fine.

So I moved back to my desktop and it failed again. It turns out to have been caused by the "NoScript" plugin on my browser. I was fooled by it though because I had been working with Yourls on GoDaddy for a client and everything had worked fine on his, then when I installed it for me on NameCheap is when I discovered the issue.

I have disabled my NoScript plugin and all is well again. This is clearly user error and I apologize for creating an issue on your GitHub account for something that  I should have caught on my own.
