### ISSUE TITLE
Document special files

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3045]
We could improve documentation about some special files:
- `user/db_error.php` : custom DB error page
- `user/maintenance.php` : custom maintenance page
- `user/favicon.(jpg|gif|png|ico|svg)` : custom favicon
- `user/cache.php` : "must use" plugin
- if blog post : reminder about Pages, see wiki

**Comment by dmchale** [comment]
@ozh What would you consider "improving" documentation? I'd like to help here but not sure what you think is best since I don't see any documentation for these listed files. 

I was thinking perhaps each file should have their own `-sample.php` file included in the /user directory by default. That would follow the pattern already established by config-sample.php and could be used to demonstrate how to set up the files. 

I suppose this doesn't work as well for the favicon though, so were you thinking of adding documentation notes elsewhere?

**Comment by dmchale** [comment]
That makes sense. Unfortunately the wiki itself doesn't appear to be part of the project, so I'm unsure how to proceed since I can't make a PR (or at least it's not straightforward, so I'm not sure how. Direction would be welcome) Cheers!
