### ISSUE TITLE
Yourls changes parameters

### ISSUE THREAD

**Issue by PerryCameron** [YOURLS/YOURLS#3171]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

I am using a URI builder in Java to make a URL and then send a GET request to make a shortened link in Yourls.

It works in the fact that the proper short link is made and the proper regular link exists. I did however notice that
if the short link is Member1 or Member2 it takes me back to /admin instead of redirecting. That is no problem because I simply make it Member01 or Member02 and it works, but that is a strange bug.
![Screen Shot 2021-12-25 at 8 02 19 PM](https://user-images.githubusercontent.com/30676310/147396371-c175c637-2de0-4770-9fd1-d4c693d1b783.png)

Now here is the bug that is the problem. If I click on the Original URL it works perfect. If I click on the shortened link, it does redirect me to the original link but it changes the parameters. Since the link is already made with a URI builder it does not need to be changed. Anyway here is an example of parameter changes.

It seems to add a 1 to them:

**Original Parameter**
workCredit=5
**After Change:**
workCredit=15

**Original Parameter**
winterStorage=0
**After Change**
winterStorage=1

Also the parameters seem to change order, which is no big deal but strange. Something like this may be changed by the site it is directing to but the parameter numbers listed above should not change.

 

### Expectation

I expected it to not change the original link.

**Comment by dgw** [comment]
YOURLS only saves and loads the long URL associated with a keyword. You can verify this by following the code path from `yourls-go.php` through to `includes/functions.php` where the redirect functions are defined.

However, note that any plugin can hook into the saving and loading stages at several points to modify the data being passed around. If the URL is generated as expected by your Java client, I suspect the actual culprit is a plugin.

**Comment by PerryCameron** [comment]
I'm not using any plugins.  Also, none of the ones included are activated. The link created by the java client is stored perfectly in the database. What I am doing is populating a SaaS application form with parameters. Now if I take that link that is stored in the database and copy and paste it into a browser it works perfectly. Maybe when I get some time, I will modify Yourls to print out the link to a text file as well. Then I can look at the text file and see what differences there are.  I believe whatever it is, is causing the SaaS application to try and correct it.

**Comment by dgw** [comment]
> I'm not using any plugins. Also, none of the ones included are activated.

I had to take a best guess because that fact wasn't specified in the original report. Plugins have been the main cause of weird bugs in my experience, so in the absence of a statement that no plugins were in use, it was the most obvious possibility.

As for troubleshooting the issue, I think you would find it useful to test one of the shortlinks that appears to be modified in cURL. You'll be able to see everything from the initial request to YOURLS and its response onward, and see where the `Location` header begins to deviate from what you expect. For this, I recommend the command line `curl -LsD - -o /dev/null SHORTLINK_HERE`.\*

----
\* — `L` to follow redirects, `s` to hide progress bars, `D` to dump headers to the specified file (here, `-` for stdout), and `-o /dev/null` sends the page contents to the void instead of your terminal because in this case all that matters are the headers.

**Comment by PerryCameron** [comment]
Thank you for the command line and thorough explanation of all its parts. The link under "Location:" was perfect. I removed the parameters where they began to become personal identifying data.

HTTP/1.1 301 Moved Permanently
Date: Sun, 26 Dec 2021 15:40:01 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Robots-Tag: noindex
Location: https://form.jotform.com/213175957272058?memid=52&membershipType=Regular&address%5Baddr_line1%5D=
Content-Length: 0
Content-Type: text/html; charset=UTF-8

HTTP/2 200 
access-control-allow-origin: *
cache-control: no-cache
cache-hit: 1
content-type: text/html; charset=utf-8
expires: Thu, 01 Jan 1970 00:00:01 GMT
server: CacheX v2.1
vary: Accept-Encoding
date: Sun, 26 Dec 2021 15:40:01 GMT
via: 1.1 google
alt-svc: clear

**From the admin panel:**
If I click on the "Short URL" I get the following in the address bar:
https://cdn.jotfor.ms/213175957272058?memid=52&membershipType=Regular&address[addr_line1]=

If I click on the "Original URL" I get the following in the address bar:
https://form.jotform.com/213175957272058?memid=52&membershipType=Regular&address%5Baddr_line1%5D=

If Yourls is redirecting the same URL, what could possibly be causing this?

So I went ahead and modified the link simply changing personal identifying information with fake data. Then I put it in using the admin panel and the short link worked.

**$** curl -LsD - -o /dev/null https://fakename.com/ecscurl/member53
HTTP/1.1 301 Moved Permanently
Date: Sun, 26 Dec 2021 16:51:14 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Robots-Tag: noindex
Location: https://form.jotform.com/213175957272058?memid=53&membershipType=Regular&address%5Baddr_line1%5D=3850%20Fake%20Road&address%5Bcity%5D=Indianapolis&address%5Bstate%5D=IN&address%5Bpostal%5D=46217&workCredit=5&winterStorage=0&primaryMember%5Bfirst%5D=Sam&primaryMember%5Blast%5D=Fakeame&primaryOccupation=Retired&primaryCompany&primaryemail=sfakename%40email.com&primaryPhone=123-456-7891
Content-Length: 0
Content-Type: text/html; charset=UTF-8

HTTP/2 200 
access-control-allow-origin: *
cache-control: no-cache
cache-hit: 1
content-type: text/html; charset=utf-8
expires: Thu, 01 Jan 1970 00:00:01 GMT
server: CacheX v2.1
vary: Accept-Encoding
date: Sun, 26 Dec 2021 16:51:14 GMT
via: 1.1 google
alt-svc: clear


I see no difference here. WTF?

**Comment by dgw** [comment]
> So I went ahead and modified the link simply changing personal identifying information with fake data. Then I put it in using the admin panel and the short link worked.

> I see no difference here. WTF?

If you haven't done anything to bypass your browser's cache when testing the shortlink, then it could be holding on to the result of some past invocation (since 301 redirects are "permanent", they usually get cached for arbitrarily long times; cURL doesn't implement this, so you'll generally see the true, current, target of a redirect every time).

Seeing the actual target SaaS domain let me do a search, and… At least one other user had odd redirects between those two domains and [asked about it](https://www.jotform.com/answers/2029734-redirect-to-cdnjotforms) a couple years ago. Might be worth contacting Jotform support if you're seeing behavior that interferes with the form's functionality.

**Comment by PerryCameron** [comment]
Well well well. After all that, it turned out to be the cache.

D'oh!

Thank you for all your help!
