### ISSUE TITLE
white spaces in URL will be deleted instead of escaped

### ISSUE THREAD

**Issue by jkischel** [YOURLS/YOURLS#3214]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

URLs with spaces will not be properly converted (e.g. with %20), instead the white spaces will be simply deleted resulting in an invalid link. Issue is reproducible.

### Expectation

Spaces will be converted and saved to browser compatible %20, e.g.
https://www.example.com/some%20path%20with%20white%20spaces%20here

### Reproduction steps

1. Simply shorten the link
https://www.example.com/some path with white spaces here
2. the saved long link will be
https://www.example.com/somepathwithwhitespaceshere
which is invalid, of course.

### Context

Expected was the stored long URL
https://www.example.com/some%20path%20with%20white%20spaces%20here

**Comment by ozh** [comment]
Go to `https://www.example.com/some path with white spaces here` then copy and paste the URL. Or properly encode the URL before passing it to the API, as stated in the readme.

This has been covered a few gazillion times in past issues here.

**Comment by jkischel** [comment]
May I ask a little challenging question?
If there are gazillion users running into the same issue, then why aren't things modified in order to improve the user experience? 

At the moment, the user is shortening a valid link and gets back an invalid link as a result. Modern browsers (try yourself with Chrome, Opera and Vivaldi) don't encode spaces in link when copying it from the address bar. Links with spaces - don't ask me why users think it's a good idea - seem to be very common when using Microsoft Sharepoint.

And for that, the users will bother me again and again and again as I am the server admin to fix this which is quite annoying over the time. 

However, if the job of yourls is not to extra encode it, d'accord. But in that case, just don't remove the space character from the URL.

However, I fixed this in my local installation by myself.

The solution is quite easy: 
Open functions-formatting.php and add a space character in line 500 of the allowed characters.

just two lines above the line
"// TODO: check if that was it too destructive"

**Comment by ozh** [comment]
That's a very valid question :)

There are dozens of issues about this because for a looong time (years) we've had a known encoding issue and we weren't dealing correctly with spaces, ampersands, UTF8 and so on. This issue has been fixed a couple releases ago (1.8)

The goal of YOURLS is to fully comply to the RFC that determines which character is allowed in an URI and which should be encoded, see RFC 3986 - section 2. We want to do so because people store absolutely any kind of URIs and URLs (not just `http` links) in YOURLS and we have to behave in a predictable and generic way.

Typically here your adding space to the list of allowed chars would have unwanted side effects for most people, because the internet and programs in general expect space in URIs to be %20, not space.
Also, this change will be overwritten the next time you update YOURLS, see https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core

**Comment by jkischel** [comment]
I don't want to steal your time ;) so just for information, I tried a little around:

Edge: replaces space with %20
Firefox: doesn't replace
Chrome: replaces
Opera: replaces
Vivaldi: doesn't replace

interesting.

**Comment by ozh** [comment]
For the record on my computer (win 10, latest FF) Firefox *does* replace spaces with %20. This is really the standard behavior.
