### ISSUE TITLE
Code coverage upload to scrutinizer-ci.com doesn't work

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3238]
Since converting from Travis to Github actions, the code that is supposed to upload stuff on https://scrutinizer-ci.com/g/YOURLS/YOURLS/ and run some code analysis & code coverage isn't working (despite claiming otherwise in the action report)

Low priority and low impact, but still.

**Comment by dgw** [comment]
I feel this. The biggest pain point in converting my primary Python project from Travis to GHA was getting coverage upload (via Coveralls, in that case) to work properly.

Have you reported the issue to https://github.com/sudo-bot/action-scrutinizer, or looked at alternative Actions to run instead?

**Comment by LeoColomb** [comment]
Indeed.
Scrutinizer being unmaintained since 2019 probably does not help.

I first tried to make the upload to be active when coverage is enabled only, but it seems you have to trigger an inspection to use the coverage results:

![image](https://user-images.githubusercontent.com/846943/157614426-63ad28a1-5cee-475c-98d6-aec687bf5ec0.png)

I cannot find any settings to enable the inspection automatically.

**Comment by ozh** [comment]
> Scrutinizer being unmaintained since 2019 probably does not help.

OK maybe we should just drop it then. I liked the code coverage badge and the little annotation in PR but nothing really mandatory or super useful :)

![image](https://user-images.githubusercontent.com/223647/157743363-520a2d7d-8ec9-4460-942d-7326dab50155.png)
