### ISSUE TITLE
Package metadata on Packagist is erroneous

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3256]
Garbage on https://packagist.org/packages/yourls/yourls (the " Fund package maintenance!" has crap -- I don't even know where it's pulling this info from) and the shields.io badges on the readme are broken

![image](https://user-images.githubusercontent.com/223647/159120415-50d5fff7-d945-47e3-9b92-425ddcb6028a.png)

**Comment by LeoColomb** [comment]
> the " Fund package maintenance!" has crap

Fixed by https://github.com/YOURLS/.github/commit/23ae0db3e1847ff45b81c5460f021dfb55afd87d.

> the shields.io badges on the readme are broken

Most probably fixed by https://github.com/YOURLS/YOURLS/commit/007882fac0a7b55a9b289826c65b2ffabaa8a758.
Previous version constraint for Aura.SQL (`"aura/sql": "~3."`) is invalid since Composer v2, on which shields.io parser is based on.
Not 100% sure this is the only reason why, but I can't find anything else so far.

**Comment by ozh** [comment]
Fix confirmed -- thanks
