### ISSUE TITLE
YOURLS Installation Reveals Database Information Including Database Name and Database User Name

### ISSUE THREAD

**Issue by punkajpk** [YOURLS/YOURLS#3388]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

I was just testing out my YOURS installation and deleted the database to check something, I found that the YOURLS installation reveals the database name and database user name in a error message like this:

_Incorrect DB config, or could not connect to DB
PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dbusernamexx'@'localhost' to database 'dbnameyy'_

T don't think anyone would want that to be revealed. I think you should fix it in the next update.

### Expectation

I didn't expect he YOURS instance to reveal my database information.

### Reproduction steps

1. Delete/rename the database (you're using for your YOURLS installation) in phpMyAdmin.
2. Acces your short URL admin (http://sho.rt/admin).

### Context

None

**Comment by dgw** [comment]
Will let other maintainers weigh in first, but I think the raw error appended in the code below could be gated behind e.g. `YOURLS_DEBUG == true`, so it's relatively easy to show the full error when actively troubleshooting but normal use won't reveal the DB details if e.g. the database server goes down for a bit.

https://github.com/YOURLS/YOURLS/blob/6da30dfab08700888d4403a8ce2abaaf47ec11c7/includes/Database/YDB.php#L166

**Comment by ozh** [comment]
When there is a fatal DB error, YOURLS just prints out the error.

I don't think it would sane to change this behavior : first, it should allow for clear understanding of what is going wrong, regardless of your technical knowledge. Second, different DB engines or server configuration should produce different error messages, possibly in different languages, so it's impossible to modify them on the fly. How to know if the server is going to respond "Access denied" or "Accès refusé" for example?

This said, it is already possible to shortcut this behavior and output a custom error message : just make a custom `/user/db_error.php` and it will be used instead of the generic mysql error : https://github.com/YOURLS/YOURLS/blob/05d1db1f1bdb482c01ed6352a2062a8b33e88bea/includes/Database/YDB.php#L149-L170
