### ISSUE TITLE
Yourls on docker + proxypass NGINX, /admin username&passwrd text plain

### ISSUE THREAD

**Issue by miavi** [YOURLS/YOURLS#3642]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

Print username & password in plain text, when use proxypass nginx

on the admin page in the login, when you send the username and password through post, and in nginx you have body_request activated

I clearly show what is important, not the entire log, when XXXXX is username and YYYY is password

`{"time_iso8601_custom_format": "\\2023/\\10/\\10 \\10:18:28", "scheme": "https", "server_name": , "status": "200", "request_time": "0.007", "request_method": "POST", "request_uri": "/admin/", "server_protocol": "HTTP/2.0", , "upstream_response_time": "0.008", ""http_user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0", "request_body": "username=XXXXXXX&password=YYYYYYYYY&nonce=d4eb441dfa&submit=Login"}`

**For security, the password should be encrypted.**

### Expectation

**For security, the password should be encrypted.**

### Reproduction steps

1. nginx enable custom_log --> body_request
2. access to page /admin and input username & passwowd, and put the botton login
3. check logs nginx Load Balancing, and event print the  request_body": "username=XXXXXXX&password=YYYYYYYYY&nonce=d4eb441dfa&submit=Login"}`

### Context

not print password in plain text,

**Comment by dgw** [comment]
Yes, if you configure nginx to log the POST data, it logs the POST data. How is this a YOURLS bug?

**Comment by miavi** [comment]
Why should the password not be sent clearly in a post.
I tried it in other applications and in the login message the password is encrypted

**Comment by dgw** [comment]
Replaying credentials is still possible even if the credentials are "encrypted" before sending them to the server, unless the hashing/encryption takes into account some unique attribute of each request, like the nonce field YOURLS already embeds in the login form.

I'm tempted to monitor what my banks' sites do next time I log in to each of them. Since they all encrypt the whole connection, I bet they just POST the login form contents directly, as YOURLS does.

Is it technically possible to create a unique-per-request hashed/encrypted version of a password field value? At the cost of significantly complicating both the client and server halves of the authentication flow, yes.

Is it worth doing? Given the existence of free TLS certificates, no. Just host YOURLS over HTTPS and your MITM/replay-attack risk drops to (practically\*) zero. That also protects your session cookie from being stolen, too.

Oh, and just _don't_ log the request body.

----

\* A sufficiently powerful adversary (think state actor) can MITM you even with TLS, but then you frankly have _much_ bigger worries.

**Comment by miavi** [comment]
I have it configured through https, published to the internet through a waf, but I still find myself in the log in the body_request this information is not entirely correct, I know that this error is in other web applications, but in others they have the password so that it does not travel in the clear and although they can steal the session with a cookie, at least the attacker will not have the password, only the post request

but if you do not consider this a security flaw, we leave it here.
It is not a question of hiding the body_request from the nginx logs, but rather that it comes encrypted

**Comment by dgw** [comment]
We do not consider misconfigured web server logging to be a security flaw in YOURLS. Logging simply should not be configured to capture so much unnecessary request data in production environments.

However, if credentials are being logged in plain text _by default_ in a Docker image or other package _published by YOURLS_, please open an issue against the relevant repository (e.g. https://github.com/YOURLS/images) directly.

**Comment by miavi** [comment]
I repeat, the web server is not misconfigured, I log more information, yes, but to say that it is misconfigured, these records for internal audit are essential.

**Comment by dgw** [comment]
If data you do not want to log is being logged, it is misconfigured.

There are ways to mask sensitive data in nginx logs, as described in places like [this Stack Overflow question](https://stackoverflow.com/q/37772306/5991).

I won't continue any further down this path, as we're getting well out of scope for this issue tracker—but I still wanted to hint at a simpler solution than "rewrite most of YOURLS' login code".
