### ISSUE TITLE
Implementation of Custom Pixels/Analytics for Advanced Remarketing Capabilities

### ISSUE THREAD

**Issue by ZYB7942** [YOURLS/YOURLS#3710]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Implementation of Custom Pixels/Analytics for Advanced Remarketing Capabilities before redirect to integrate with Facebook ads

### Motivation

There is no other free tool to task.

### Describe the solution

Dear YOURLS Developers,

I trust this message finds you well. I want to extend my appreciation for the remarkable work you've done with the YOURLS project, making it a reliable and feature-rich URL shortening tool.

I am writing to propose a feature enhancement that could significantly elevate YOURLS's capabilities, specifically in the domains of marketing and analytics. While I acknowledge the intricacies involved, I believe implementing custom pixels/analytics integration would be a valuable addition to the platform.

**Overview of the Proposed Feature:**
Enabling the integration of custom pixels/analytics scripts into short URLs would open up a multitude of possibilities for marketers. This feature would empower these scripts to load and track visits before initiating the redirect function, enabling advanced remarketing strategies.

**Significance of Remarketing:**
Remarketing is a powerful digital marketing strategy involving targeting users who have previously engaged with your website or content. By incorporating remarketing pixels into redirect pages, YOURLS could simplify the creation of custom retargeting audiences. Users clicking on a short link would be seamlessly added to remarketing lists, enabling targeted advertising campaigns without requiring control over the final landing page.

**Considerations and Proposed Solutions:**
While considering the implementation of this feature, it's crucial to address potential concerns associated with various methods:

1. **Possible Latency Increase:**
   Introducing features may impact loading times, potentially affecting the overall user experience.

2. **Transparency and Engagement:**
   Redirecting through any intermediary may reduce transparency, and there's a risk of users losing interest without clear value.

3. **Development Complexity:**
   Implementing new features may add complexity to the system, necessitating careful consideration of development and maintenance resources.

4. **SEO Impact:**
   Depending on the implementation, new features could have consequences for search engine optimization (SEO).

To address these concerns, I recommend exploring alternative methods, such as HTTP redirects via headers, and finding efficient ways to set cookies and pixels. This approach aims to find a balance between achieving remarketing goals and ensuring a fast and transparent user experience.

**Implementation of HTTP Redirects via Headers:**
Using HTTP headers for redirection offers advantages by ensuring a faster user experience and allowing for the capture of user data and pixel setting before the redirection takes place.

Incorporating a option that allows users to provide their consent for the use of remarketing pixels would be a valuable addition, aligning with the legal privacy requirements of GDPR, it would be optional and could be deactivated in certain campaigns.

I firmly believe that the addition of this feature would not only meet the needs of marketers but also enhance YOURLS's reputation as a versatile and forward-thinking URL shortening tool.

Thank you for considering this request, and I eagerly anticipate witnessing the continued success and evolution of the YOURLS project.

Best regards, ZYB7942

**Comment by dgw** [comment]
Not to speak for the rest of the maintenance team, but I have zero interest in making YOURLS any easier to use for advertising, especially Facebook ads. On top of that, this whole idea sounds like it belongs squarely in "[Possible with a plugin](https://yourls.org/docs/guide/extend/possible-with-a-plugin)" territory.

Whatever intermediate redirection step needs to happen for this to work can surely be accomplished using existing plugin hooks, as demonstrated by e.g. [the Toolbar example](https://github.com/YOURLS/YOURLS/blob/master/user/plugins/sample-toolbar/plugin.php) that ships with YOURLS itself.

Otherwise, there is no place to insert any kind of "pixel" during a normal YOURLS redirection. Unless interrupted as the Toolbar sample linked above does, YOURLS sends the client a 301 Moved Permanently header and the Location of the full URL. A 301 response's body is likely not to be displayed, or even parsed.

_(Among other clues, suggesting the use of HTTP redirection via headers makes it appear that you conscripted an LLM to create this feature request, because such a suggestion is fundamentally incompatible with the request's basic premise. It's very hard to take such self-contradictory proposals seriously.)_

**Comment by acelaya** [comment]
Just FYI. This smells a lot like an AI-generated message form a bot.

This account has created similar issues in other URL shortener repositories:

* https://github.com/cydrobolt/polr/issues/640
* https://github.com/thedevs-network/kutt/issues/732
* https://github.com/shlinkio/shlink/issues/1978

I have blocked and reported the account and would suggest doing the same.

**Comment by dgw** [comment]
@acelaya Don't have to tell me twice! This was never going to be a feature of core anyway.
