### ISSUE TITLE
Hangs on shorten or edit.

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#418]
This is a **COPY** of **Issue 418: [Hangs on shorten or edit.](http://code.google.com/p/yourls/issues/detail?id=418)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-07-30T01:33:33.000Z by [kraymitc...@gmail.com](http://code.google.com/u/111253753344044745753/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I couldn't find anything in a search, I hope I didn't miss anything.

After working fine for a long time, all of a sudden I can't create or edit short URLs anymore.

When I try and create one, I put my URL and custom short name in, and hit Shorten The URL, I get the progress spinner but nothing ever happens.

I get the same result if I try and change a URL.

I have not made any changes to anything and I am running 1.4.3.

Any ideas on how to fix this??

Thanks! and thanks for a great product.
```

**Comment by IllinoisMike** [comment]
Was there ever a fix for this problem?  I am having the same issue with v 1.7.2 after upgrading from 1.5.1.  
![screen shot 2018-02-15 at 10 03 34 am](https://user-images.githubusercontent.com/36511384/36267209-f97955bc-1238-11e8-990d-4c230def77a2.png)

Thanks for any help you can lend.

—Mike

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon

**Comment by ozh** [comment]
Also: https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps

**Comment by IllinoisMike** [comment]
The issue i am experiencing with the spinning icon is not present when I empty the yourls_url and yourls_log tables to 0 records.  I am able to shorten a URL with no issue.

Once I re-populate the "yourls_url" table, I get the spinning wheel when trying to shorten.  This is in 1.7.3, but was present in 1.7.2 as well.  That table has 3,627 rows.

I have been using YOURLS since 2010 on the same server, with no issues.  I have three installs running on three separate domain names, two are currently not able to shorten (the ones I upgraded to 1.7.2 last week), and one is working as before (1.7).  Are there internal methods/settings that would make 1.7 work but not 1.7.3?

Sorry if it is not appropriate to comment on a closed issue like this, but did not want to open a new one without clarification. Please advise, and thanks very much

**Comment by ozh** [comment]
Totally appropriate to comment on closed issues :)

The infinite spinning wheel occurs when a client side request (via javascript) is triggered and leads to a server side error (in PHP). Inspect the browser's response (see the wiki page about troubleshooting) and see response
